force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RTV_RP_Report_ShipToWhiteList.cls
@IsTest(isParallel=true)
public with sharing class Test_RTV_RP_Report_ShipToWhiteList {
    @IsTest
    public static void test() {
        RTV_Program__c program = new RTV_Program__c();
        insert program;
        
        RTV_Summary__c summary = new RTV_Summary__c();
        insert summary;
        
        ApexPages.currentPage().getParameters().put('programId', program.Id);
        RTV_RP_Report_ShipToWhiteList ctrl = new RTV_RP_Report_ShipToWhiteList();

        ApexPages.currentPage().getParameters().put('summaryId', summary.Id);
        ctrl = new RTV_RP_Report_ShipToWhiteList();
    }
}