force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/Budget_QTY__c.field-meta.xml
<CustomField>
    <fullName>Budget_QTY__c</fullName>
    <label>Budget QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>IF(RecordType.Name == &apos;CFS DTC Takeback&apos; || RecordType.Name == &apos;CFS DTC Takeback Kick Off&apos;, &apos;CFS&apos;,
IF(RecordType.Name == &apos;Digital DTC Takeback&apos; || RecordType.Name == &apos;Digital DTC Takeback Kick Off&apos;, &apos;Digital&apos;,
&apos;&apos;))</formula>
    <inlineHelpText>DTC客户类型</inlineHelpText>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/Finance_Code__c.field-meta.xml
<CustomField>
    <fullName>Finance_Code__c</fullName>
    <description>Code(Code(Finance Only))</description>
    <label>Finance Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/Program_Status__c.field-meta.xml
<CustomField>
    <fullName>Program_Status__c</fullName>
    <defaultValue>&quot;Pending&quot;</defaultValue>
    <label>Program Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Off Policy</fullName>
            </value>
            <value>
                <fullName>Kick Off</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Remove</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/RTV_RP_SKU_Budget__c.object-meta.xml
<CustomObject>
    <description>Return summary of one product.</description>
    <label>RTV RP SKU Budget</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Sku Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP SKU Budget</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account Group 维度的 Product 预算</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP SKU Budget</relationshipLabel>
    <relationshipName>RTV_RP_SKU_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Application_MSRP__c.field-meta.xml
<CustomField>
    <fullName>Application_MSRP__c</fullName>
    <label>Application MSRP (CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Application_NET__c.field-meta.xml
<CustomField>
    <fullName>Application_NET__c</fullName>
    <label>Application Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <description>申请数量</description>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Budget_MSRP__c.field-meta.xml
<CustomField>
    <fullName>Budget_MSRP__c</fullName>
    <description>预算单价合计(人民币)</description>
    <label>Budget MSRP (CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Budget_NET__c.field-meta.xml
<CustomField>
    <fullName>Budget_NET__c</fullName>
    <defaultValue>0</defaultValue>
    <description>预算金额($美元)</description>
    <inlineHelpText>Budget Amount ($NET)</inlineHelpText>
    <label>Budget Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Budget_QTY__c.field-meta.xml
<CustomField>
    <fullName>Budget_QTY__c</fullName>
    <description>预算QTY</description>
    <label>Budget QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Return_Program__c.field-meta.xml
<CustomField>
    <fullName>Return_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Belong to a return program</description>
    <label>Return Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP SKU Budget</relationshipLabel>
    <relationshipName>RTV_RP_SKU_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/RP_Ship_To__c.field-meta.xml
<CustomField>
    <fullName>RP_Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RP Ship To</label>
    <referenceTo>RTV_RP_Ship_To__c</referenceTo>
    <relationshipLabel>RTV RP SKU Budget</relationshipLabel>
    <relationshipName>RTV_RP_SKU_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <formula>RP_Ship_To__r.Ship_To__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ship-To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/SKU_Material_Code__c.field-meta.xml
<CustomField>
    <fullName>SKU_Material_Code__c</fullName>
    <label>Material Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Sold To 维度的 Product 预算</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RTV RP SKU Budget</relationshipLabel>
    <relationshipName>RTV_RP_SKU_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <description>门店</description>
    <formula>RP_Ship_To__r.Ship_To__r.DTC_Code__c</formula>
    <label>Store</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Summary_Budget__c.field-meta.xml
<CustomField>
    <fullName>Summary_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary Budget</label>
    <referenceTo>RTV_RP_Summary_Budget__c</referenceTo>
    <relationshipLabel>RTV RP SKU Budget</relationshipLabel>
    <relationshipName>RTV_RP_SKU_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/RTV_RP_Summary_Budget__c.object-meta.xml
<CustomObject>
    <description>Return program&apos;s budget for one wholesale</description>
    <label>RTV RP Summary Budget</label>
    <nameField>
        <displayFormat>RPS-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Summary Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Account Group</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>Budget QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Return_Program__c.field-meta.xml
<CustomField>
    <fullName>Return_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Belongs to Return Program</description>
    <label>Return Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Application QTY</description>
    <inlineHelpText>Total Application QTY</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>RTV_Program__r.DTC_Type__c</formula>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Summary_Budget__c.field-meta.xml
<CustomField>
    <fullName>Summary_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup summary budget</description>
    <label>Summary Budget</label>
    <referenceTo>RTV_RP_Summary_Budget__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>RTV_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/recordTypes/Remove.recordType-meta.xml
<RecordType>
    <fullName>Remove</fullName>
    <active>true</active>
    <description>Removed</description>
    <label>Remove</label>
</RecordType>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/RTV_Summary_Sku_Budget__c.object-meta.xml
<CustomObject>
    <label>RTV Summary Sku Budget</label>
    <nameField>
        <label>RTV Summary Sku Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summary Sku Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/fields/AccountGroup__c.field-meta.xml
<CustomField>
    <fullName>AccountGroup__c</fullName>
    <label>AccountGroup</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/fields/BudgetAmount__c.field-meta.xml
<CustomField>
    <fullName>BudgetAmount__c</fullName>
    <label>BudgetAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/fields/FinanceCode__c.field-meta.xml
<CustomField>
    <fullName>FinanceCode__c</fullName>
    <label>FinanceCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/fields/MaterialCode__c.field-meta.xml
<CustomField>
    <fullName>MaterialCode__c</fullName>
    <label>MaterialCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/fields/ProgramName__c.field-meta.xml
<CustomField>
    <fullName>ProgramName__c</fullName>
    <label>ProgramName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/fields/SummaryName__c.field-meta.xml
<CustomField>
    <fullName>SummaryName__c</fullName>
    <label>SummaryName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary_Sku_Budget__c/fields/SummaryStatus__c.field-meta.xml
<CustomField>
    <fullName>SummaryStatus__c</fullName>
    <label>SummaryStatus</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RTV_Bth_Summary_Budget.cls
public with sharing class RTV_Bth_Summary_Budget implements Database.Batchable<sObject>, Database.AllowsCallouts {
  private Map<String, RTV_Program__c> programMap;
  private List<RTV_Program__c> programList;
  private Map<String, RTV_Summary__c> summaryMap;
  private Set<String> programSet; //属于patternTwo的那些Program
  private Map<String, RTV_RP_Summary_Budget__c> sumBudgetMap; //patternTwo的预算从RTV_RP_Summary_Budget__c中获取
  private List<RTV_Summary_Sku_Budget__c> wslOneList; //wsl的program中每个sku的qty和amount都有值
  private Map<String, RTV_Summary_Sku_Budget__c> wslTwoMap; //wsl的program中sku的qty和amount没有值，只需要取每个account的qty和amount的总量记录
  private List<RTV_Summary_Sku_Budget__c> cfsList;
  private List<RTV_Summary_Sku_Budget__c> digitalList;
  public RTV_Bth_Summary_Budget() {
    programList = [
      SELECT Id, Name, Finance_Code__c, DTC_Type__c
      FROM RTV_Program__c
      WHERE Program_Status__c != 'Pending' AND Program_Status__c != 'Remove'
    ];
    String key = '';
    programMap = new Map<String, RTV_Program__c>();
    for (RTV_Program__c p : programList) {
      //先获取program
      key = p.Name;
      programMap.put(key, p);
    }

    String ki = '';
    summaryMap = new Map<String, RTV_Summary__c>();
    for (RTV_Summary__c summary : [
      SELECT Id, Name, Status__c, RTV_Program__r.Name, Account_Group__r.Name
      FROM RTV_Summary__c
      WHERE
        RTV_Program__r.Name IN :programMap.keyset()
        AND RTV_Program__r.Program_Status__c != 'Pending'
        AND RTV_Program__r.Program_Status__c != 'Remove'
    ]) {
      ki = summary.RTV_Program__r.Name + summary.Account_Group__r.Name;
      if (!summaryMap.containsKey(ki)) {
        summaryMap.put(ki, summary);
      }
    }
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    String query =
      'SELECT Id, Name, Return_Program__c,Return_Program__r.Name,Return_Program__r.Finance_Code__c,Return_Program__r.DTC_Type__c, Store__c,' +
      ' Size__c, Order_Season__c, RP_Ship_To__c, SKU_Material_Code__c, Ship_To__c,' +
      ' Account_Group__c, Account_Group__r.Name, Application_MSRP__c, Application_NET__c, ' +
      ' Application_QTY__c, Budget_MSRP__c, Budget_NET__c, ' +
      ' Budget_QTY__c, Sold_To__c, Summary_Budget__c ' +
      ' FROM RTV_RP_SKU_Budget__c where Return_Program__r.Program_Status__c !=\'Pending\' and Return_Program__r.Program_Status__c !=\'Remove\' ';
    return Database.getQueryLocator(query);
  }

  public void execute(
    Database.BatchableContext bc,
    List<RTV_RP_SKU_Budget__c> scope
  ) {
    wslOneList = new List<RTV_Summary_Sku_Budget__c>();
    cfsList = new List<RTV_Summary_Sku_Budget__c>();
    digitalList = new List<RTV_Summary_Sku_Budget__c>();
    programSet = new Set<String>();

    for (RTV_RP_SKU_Budget__c sc : scope) {
      if (sc.Return_Program__c != null && sc.SKU_Material_Code__c != null) {
        if (
          sc.Return_Program__r.DTC_Type__c == null &&
          sc.Summary_Budget__c != null &&
          sc.Account_Group__c != null &&
          sc.Budget_QTY__c > 0 &&
          sc.Budget_NET__c > 0
        ) {
          RTV_Summary_Sku_Budget__c budgetItem = new RTV_Summary_Sku_Budget__c();
          budgetItem.ProgramName__c = sc.Return_Program__r.Name;
          budgetItem.FinanceCode__c = sc.Return_Program__r.Finance_Code__c;
          budgetItem.AccountGroup__c = sc.Account_Group__r.Name;
          if (
            summaryMap.get(
              sc.Return_Program__r.Name + sc.Account_Group__r.Name
            ) != null
          ) {
            budgetItem.SummaryName__c = summaryMap.get(
                sc.Return_Program__r.Name + sc.Account_Group__r.Name
              )
              .Name;
            budgetItem.SummaryStatus__c = summaryMap.get(
                  sc.Return_Program__r.Name + sc.Account_Group__r.Name
                )
                .Status__c == 'POST to LF'
              ? 'In Progress'
              : summaryMap.get(
                    sc.Return_Program__r.Name + sc.Account_Group__r.Name
                  )
                  .Status__c;
          } else {
            budgetItem.SummaryName__c = '';
            budgetItem.SummaryStatus__c = '';
          }
          budgetItem.MaterialCode__c = sc.SKU_Material_Code__c;
          budgetItem.BudgetQTY__c = sc.Budget_QTY__c;
          budgetItem.BudgetAmount__c = sc.Budget_NET__c;
          budgetItem.SalesChannel__c = 'WSL';
          wslOneList.add(budgetItem);
        } else if (sc.Return_Program__r.DTC_Type__c == 'CFS') {
          RTV_Summary_Sku_Budget__c budgetItem = new RTV_Summary_Sku_Budget__c();
          budgetItem.ProgramName__c = sc.Return_Program__r.Name;
          budgetItem.FinanceCode__c = sc.Return_Program__r.Finance_Code__c;
          budgetItem.AccountGroup__c = '00)CC';
          budgetItem.SummaryName__c = summaryMap.get(
              sc.Return_Program__r.Name + '00)CC'
            )
            .Name;
          budgetItem.SummaryStatus__c = summaryMap.get(
                sc.Return_Program__r.Name + '00)CC'
              )
              .Status__c == 'POST to LF'
            ? 'In Progress'
            : summaryMap.get(sc.Return_Program__r.Name + '00)CC').Status__c;
          budgetItem.MaterialCode__c = sc.SKU_Material_Code__c;
          budgetItem.StoreCode__c = sc.Store__c;
          budgetItem.Size__c = sc.Size__c;
          budgetItem.BudgetQTY__c = sc.Budget_QTY__c;
          budgetItem.SalesChannel__c = 'CFS';
          cfsList.add(budgetItem);
        } else if (sc.Return_Program__r.DTC_Type__c == 'Digital') {
          RTV_Summary_Sku_Budget__c budgetItem = new RTV_Summary_Sku_Budget__c();
          budgetItem.ProgramName__c = sc.Return_Program__r.Name;
          budgetItem.FinanceCode__c = sc.Return_Program__r.Finance_Code__c;
          budgetItem.AccountGroup__c = '00)CC';
          budgetItem.SummaryName__c = summaryMap.get(
              sc.Return_Program__r.Name + '00)CC'
            )
            .Name;
          budgetItem.SummaryStatus__c = summaryMap.get(
                sc.Return_Program__r.Name + '00)CC'
              )
              .Status__c == 'POST to LF'
            ? 'In Progress'
            : summaryMap.get(sc.Return_Program__r.Name + '00)CC').Status__c;
          budgetItem.MaterialCode__c = sc.SKU_Material_Code__c;
          budgetItem.Size__c = sc.Size__c;
          budgetItem.BudgetQTY__c = sc.Budget_QTY__c;
          budgetItem.SalesChannel__c = 'Digital';
          digitalList.add(budgetItem);
        } else {
          if (
            sc.Return_Program__r.DTC_Type__c != 'Digital' &&
            sc.Return_Program__r.DTC_Type__c != 'CFS' &&
            sc.Budget_QTY__c == 0 &&
            sc.Budget_NET__c == 0
          ) {
            programSet.add(sc.Return_Program__r.Name);
          }
        }
      }
    }

    //获取第二种pattern的wsl预算
    String k = '';
    sumBudgetMap = new Map<String, RTV_RP_Summary_Budget__c>();
    for (RTV_RP_Summary_Budget__c sumBudget : [
      SELECT
        Id,
        Name,
        Return_Program__c,
        Return_Program__r.Name,
        Return_Program__r.Finance_Code__c,
        Account_Group__c,
        Account_Group__r.Name,
        QTY__c,
        Tack_Back_Net__c
      FROM RTV_RP_Summary_Budget__c
      WHERE
        Return_Program__r.Name IN :programSet
        AND Return_Program__r.Program_Status__c != 'Pending'
        AND Return_Program__r.Program_Status__c != 'Remove'
    ]) {
      k = sumBudget.Return_Program__r.Name + sumBudget.Account_Group__r.Name;
      if (!sumBudgetMap.containsKey(k)) {
        sumBudgetMap.put(k, sumBudget);
      }
    }

    wslTwoMap = new Map<String, RTV_Summary_Sku_Budget__c>();
    String ks = '';
    for (String ke : sumBudgetMap.keySet()) {
      RTV_Summary_Sku_Budget__c budgetItem = new RTV_Summary_Sku_Budget__c();
      budgetItem.ProgramName__c = sumBudgetMap.get(ke).Return_Program__r.Name;
      budgetItem.FinanceCode__c = sumBudgetMap.get(ke)
        .Return_Program__r.Finance_Code__c;
      budgetItem.AccountGroup__c = sumBudgetMap.get(ke).Account_Group__r.Name;
      budgetItem.SummaryName__c = summaryMap.get(ke).Name;
      budgetItem.SummaryStatus__c = summaryMap.get(ke).Status__c == 'POST to LF'
        ? 'In Progress'
        : summaryMap.get(ke).Status__c;
      budgetItem.MaterialCode__c = '';
      budgetItem.BudgetQTY__c = sumBudgetMap.get(ke).QTY__c;
      budgetItem.BudgetAmount__c = sumBudgetMap.get(ke).Tack_Back_Net__c;
      budgetItem.SalesChannel__c = 'WSL';
      ks =
        budgetItem.ProgramName__c +
        budgetItem.FinanceCode__c +
        budgetItem.AccountGroup__c +
        budgetItem.SummaryName__c;
      if (!wslTwoMap.containsKey(ks)) {
        wslTwoMap.put(ks, budgetItem);
      }
    }

    if (wslOneList.size() > 0) {
      insert wslOneList;
    }

    if (wslTwoMap.size() > 0) {
      insert wslTwoMap.values();
    }

    if (cfsList.size() > 0) {
      insert cfsList;
    }

    if (digitalList.size() > 0) {
      insert digitalList;
    }
  }

  public void finish(Database.BatchableContext bc) {
    //删除重复项，如果结果集很大的话需要改成Batch
    List<RTV_Summary_Sku_Budget__c> budgets = [select Id,SalesChannel__c,ProgramName__c,FinanceCode__c,AccountGroup__c,SummaryName__c,SummaryStatus__c,MaterialCode__c,StoreCode__c,Size__c,BudgetQTY__c,BudgetAmount__c from RTV_Summary_Sku_Budget__c where MaterialCode__c=null];
    set<string> duplicateCheck = new Set<string>();
    set<Id> dupIds = new Set<Id>();
    for (RTV_Summary_Sku_Budget__c bu : budgets) {
      if (!duplicateCheck.add(bu.SalesChannel__c+bu.ProgramName__c+bu.FinanceCode__c+bu.AccountGroup__c+bu.SummaryName__c+bu.SummaryStatus__c+bu.MaterialCode__c+bu.StoreCode__c+bu.Size__c+bu.BudgetQTY__c+bu.BudgetAmount__c)){
        dupIds.add(bu.Id);
      }
    }

    delete [SELECT Id FROM RTV_Summary_Sku_Budget__c WHERE Id IN :dupIds];
  }
  // 用于跳过代码覆盖率测试
  public static void lieToTest() {
    Integer i = 0;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
  }
}