force-app/main/default/objects/ConverseRMS__c/ConverseRMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Converse RMS Setting</description>
    <label>ConverseRMS</label>
</CustomObject>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_CS_Confirm_To_WSL_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_CS_Confirm_To_WSL_Confirm__c</fullName>
    <label>Offset Of CS Confirm To WSL Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Delivered_To_Insp__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Delivered_To_Insp__c</fullName>
    <label>Offset Of Delivered To Insp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Inbound_To_Completed__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Inbound_To_Completed__c</fullName>
    <label>Offset Of Inbound To Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Insp_To_CS_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Insp_To_CS_Confirm__c</fullName>
    <label>Offset Of Insp To CS Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Kick_Off_To_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Kick_Off_To_PTLF__c</fullName>
    <label>Offset Of Kick Off To PTLF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_PTLF_To_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_PTLF_To_Delivered__c</fullName>
    <label>Offset Of PTLF To Delivered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_WSL_Confirm_To_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_WSL_Confirm_To_Inbound__c</fullName>
    <label>Offset Of WSL Confirm To Inbound</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_BaoZun_Seeding__c/RTV_BaoZun_Seeding__c.object-meta.xml
<CustomObject>
    <label>RTV Baozun Seeding</label>
    <nameField>
        <label>RTV BaoZun Seeding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Baozun Seeding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_BaoZun_Seeding__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Earliest_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Delivery_Date__c</fullName>
    <description>最早提货日期</description>
    <label>Earliest Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Insp_CS_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_CS_Approve_Time__c</fullName>
    <label>Insp CS Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>WSL Takeback OR DTC Takeback</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WSL Takeback</fullName>
                <default>true</default>
                <label>WSL Takeback</label>
            </value>
            <value>
                <fullName>RTV Defective</fullName>
            </value>
            <value>
                <fullName>CFS DTC Takeback</fullName>
            </value>
            <value>
                <fullName>Digital DTC Takeback</fullName>
            </value>
            <value>
                <fullName>CFS DTC Defective</fullName>
            </value>
            <value>
                <fullName>Digital DTC Defective</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Baozun_Seeding__c.field-meta.xml
<CustomField>
    <fullName>RTV_Baozun_Seeding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Baozun Seeding</label>
    <referenceTo>RTV_BaoZun_Seeding__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Seeding_Status__c.field-meta.xml
<CustomField>
    <fullName>Seeding_Status__c</fullName>
    <label>Seeding Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST to LF</fullName>
                <default>true</default>
                <label>POST to LF</label>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <inlineHelpText>Please check if the address is right. 
If wrong, please correct it.</inlineHelpText>
    <label>Ship-To Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <label>Ship-To Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Outbound_Emails__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Outbound_Emails__c</fullName>
    <inlineHelpText>请输入Ship-To外部Email地址（逗号分割的1~5个地址）</inlineHelpText>
    <label>Ship-To Outbound Emails</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone1__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone1__c</fullName>
    <label>Ship-To Phone1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone2__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone2__c</fullName>
    <label>Ship-To Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Application QTY</description>
    <inlineHelpText>Total Application QTY</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Insp_CS_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_CS_Approve_Time__c</fullName>
    <description>CS审批Inspection的时间点</description>
    <label>Insp CS Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <defaultValue>&apos;ZRE&apos;</defaultValue>
    <description>SAP CSV固定值</description>
    <label>Order Type</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Order_StatusChange.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Order_StatusChange {
    @isTest
    public static void test() {
        RTV_Order__c order = new RTV_Order__c();
        insert order;
        
        // insert new ConverseRMS__c(
        //     Offset_Of_Kick_Off_To_PTLF__c = 1,
        //     Offset_Of_PTLF_To_Delivered__c = 1,
        //     Offset_Of_Delivered_To_Insp__c = 1,
        //     Offset_Of_Insp_To_CS_Confirm__c = 1,
        //     Offset_Of_CS_Confirm_To_WSL_Confirm__c = 1,
        //     Offset_Of_WSL_Confirm_To_Inbound__c = 1,
        //     Offset_Of_Inbound_To_Completed__c = 1
        // );
        
        // RTV_Program__c program = new RTV_Program__c();
        // insert program;
        
        // RTV_Summary__c summary = new RTV_Summary__c();
        // summary.RTV_Program__c = program.Id;
        // insert summary;
        
        // // wsl takeback
        // RTV_Order__c order = new RTV_Order__c();
        // order.Return_Summary__c = summary.Id;
        // order.Name = 'xxxxx';
        // order.Status__c = 'Pending';
        // order.Earliest_Delivery_Date__c = System.today();
        // order.Ship_To_Contact__c = 'xx';
        // order.Ship_To_Phone1__c = '13012341234';
        // order.Ship_To_Phone2__c = '13012341234';
        // order.Ship_To_Address__c = 'xx';
        // order.Ship_To_Outbound_Emails__c = 'xx@xx.xx';
        // order.Application_QTY__c = 123.45;
        // insert order;
        
        // order.Status__c='Ready';
        // update order;
        
        // order.Status__c='POST to LF';
        // update order;
        
        // order.Status__c='Delivered';
        // update order;
        
        // order.Status__c='Inspected';
        // update order;
        
        // order.Status__c='Insp Wait Approval';
        // update order;
        
        // order.Status__c='Insp Confirmed';
        // update order;
        
        // order.Status__c='Inbound';
        // update order;
        
        // order.Status__c='Completed';
        // update order;
        
        // // -------------------------------------
        // // wsl defective
        // // ------------------------------------
        // order = new RTV_Order__c();
        // order.Order_Type__c = 'RTV Defective';
        // order.Earliest_Delivery_Date__c = System.today();
        // order.Ship_To_Contact__c = 'xx';
        // order.Ship_To_Phone1__c = '13012341234';
        // order.Ship_To_Phone2__c = '13012341234';
        // order.Ship_To_Address__c = 'xx';
        // order.Ship_To_Outbound_Emails__c = 'xx@xx.xx';
        // order.Status__c = 'Pending';
        // order.Application_QTY__c = 123.45;
        // insert order;
        
        // order.Status__c='Ready';
        // update order;
        
        // order.Status__c='POST to LF';
        // update order;
        
        // order.Status__c='Delivered';
        // update order;
        
        // order.Status__c='Inspected';
        // update order;
        
        // order.Status__c='Insp Wait Approval';
        // update order;
        
        // order.Insp_Cs_Approve_Time__c = System.now();
        // update order;
        
        // order.Status__c='Inbound';
        // update order;
        
        // order.Status__c='Completed';
        // update order;
        
        // // ------------------------------------
        // // dtc takeback
        // // ------------------------------------
        // RMS_Account_Group__c acgCC = new RMS_Account_Group__c();
        // acgCC.Name = '00)CC';
        // insert acgCC;
        
        // program = new RTV_Program__c();
        // program.RecordTypeId = RMS_CommonUtil.getRecordTypes('RTV_Program__c').get('CFS DTC Takeback Kick Off').Id;
        // insert program;
        
        // summary = new RTV_Summary__c();
        // summary.RTV_Program__c = program.Id;
        // insert summary;
        
        // order = new RTV_Order__c();
        // order.Order_Type__c = 'CFS DTC Takeback';
        // order.Earliest_Delivery_Date__c = System.today();
        // order.Ship_To_Contact__c = 'xx';
        // order.Ship_To_Phone1__c = '13012341234';
        // order.Ship_To_Phone2__c = '13012341234';
        // order.Ship_To_Address__c = 'xx';
        // order.Ship_To_Outbound_Emails__c = 'xx@xx.xx';
        // order.Status__c = 'Pending';
        // order.Application_QTY__c = 123.45;
        // insert order;
        
        // order.Status__c='Ready';
        // update order;
        
        // order.Status__c='POST to LF';
        // update order;
        
        // order.Status__c='Delivered';
        // update order;
        
        // order.Status__c='Inspected';
        // update order;
        
        // order.Status__c='Insp Wait Approval';
        // update order;
        
        // order.Status__c='Insp Confirmed';
        // update order;
        
        // order.Status__c='Inbound';
        // update order;
        
        // order.Status__c='Completed';
        // update order;
            
        // // error
        // try{
        //     order.Status__c='error???';
        //     update order;
        // } catch(Exception err){
        // }
        
        // //-------------------------------------
        // // baozun
        // //-------------------------------------
        // RTV_BaoZun_Seeding__c seeding = new RTV_BaoZun_Seeding__c();
        // seeding.Year__c = 2021;
        // seeding.Month__c = 1;
        // insert seeding;
        
        // order = new RTV_Order__c();
        // order.RTV_BaoZun_Seeding__c = seeding.Id;
        // order.Name = 'xxxxx';
        // order.Status__c = 'Pending';
        // order.Seeding_Status__c = 'POST to LF';
        // insert order;
        
        // order.Seeding_Status__c = 'Inbound';
        // update order;
    }
}