force-app/main/default/objects/ConverseRMS__c/ConverseRMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Converse RMS Setting</description>
    <label>ConverseRMS</label>
</CustomObject>

force-app/main/default/objects/ConverseRMS__c/fields/ExRate__c.field-meta.xml
<CustomField>
    <fullName>ExRate__c</fullName>
    <defaultValue>7.1</defaultValue>
    <label>ExRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>1.13</defaultValue>
    <description>Tax rate</description>
    <label>TaxRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Earliest_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Delivery_Date__c</fullName>
    <description>最早提货日期</description>
    <label>Earliest Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inbound_Amount__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Amount__c</fullName>
    <formula>IF(Inspect_Amount_A__c &gt;=0, Inspect_Amount_A__c, 0) +
IF(Inspect_Amount_B__c &gt;=0, Inspect_Amount_B__c, 0) +
IF(Inspect_Amount_D__c &gt;=0, Inspect_Amount_D__c, 0)</formula>
    <label>Actual Amount (CNY/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <inlineHelpText>Please check if the address is right. 
If wrong, please correct it.</inlineHelpText>
    <label>Ship-To Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <label>Ship-To Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone1__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone1__c</fullName>
    <label>Ship-To Phone1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone2__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone2__c</fullName>
    <label>Ship-To Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/recordTypes/Remove.recordType-meta.xml
<RecordType>
    <fullName>Remove</fullName>
    <active>true</active>
    <description>Removed</description>
    <label>Remove</label>
</RecordType>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/ExRate__c.field-meta.xml
<CustomField>
    <fullName>ExRate__c</fullName>
    <defaultValue>$Setup.ConverseRMS__c.ExRate__c</defaultValue>
    <description>汇率</description>
    <label>ExRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>$Setup.ConverseRMS__c.TaxRate__c</defaultValue>
    <description>税率</description>
    <label>TaxRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Application QTY</description>
    <inlineHelpText>Total Application QTY</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inbound_Amount__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Amount (CNY/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Summary_Type__c.field-meta.xml
<CustomField>
    <fullName>Summary_Type__c</fullName>
    <description>WSL Takeback OR DTC Takeback</description>
    <label>Summary Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WSL Takeback</fullName>
                <default>true</default>
                <label>WSL Takeback</label>
            </value>
            <value>
                <fullName>DTC Takeback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/recordTypes/Remove.recordType-meta.xml
<RecordType>
    <fullName>Remove</fullName>
    <active>true</active>
    <description>Removed</description>
    <label>Remove</label>
</RecordType>

force-app/main/default/classes/Test_Trigger_RMS_Summary_StatusChange.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Summary_StatusChange {
    @IsTest
    public static void test() {
        List<ConverseRMS__c> settings = [SELECT TaxRate__c FROM ConverseRMS__c LIMIT 1];
        if (settings.isEmpty()) {
            insert new ConverseRMS__c(ExRate__c = 1.13);
        }
        else if (settings[0].TaxRate__c == null) {
            update new ConverseRMS__c(Id=settings[0].Id, ExRate__c = 1.13);
        }
        
        RTV_Program__c program = new RTV_Program__c();
        insert program;
        
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.RTV_Program__c = program.Id;
        summary.Status__c = 'Pending';
        summary.Inbound_Amount__c = 123.45;
        summary.Application_QTY__c = 123;
        insert summary;
        
        RTV_Order__c order = new RTV_Order__c();
        order.Return_Summary__c = summary.Id;
        order.Status__c = 'Pending';
        order.Earliest_Delivery_Date__c = System.today();
        order.Ship_To_Contact__c = 'xx';
        order.Ship_To_Phone1__c = '13012341234';
        order.Ship_To_Phone2__c = '13012341234';
        order.Ship_To_Address__c = 'xx';
        order.Application_QTY__c = 100;
        insert order;
        
        summary.Status__c = 'Remove';
        update summary;
        
        summary.Status__c = 'Ready';
        update summary;
        
        summary.Status__c = 'POST to LF';
        update summary;
        
        summary.Status__c = 'Completed';
        update summary;
        
        try {
            summary.Status__c = 'xxxxxxxxxxxxxxxxxxxxxxx';
            update summary;
        } catch(Exception err) {}
        
        summary.Summary_Type__c = 'DTC Takeback';
        summary.Status__c = 'Ready';
        update summary;
        summary.Status__c = 'POST to LF';
        update summary;
    }
}