force-app/main/default/objects/ConverseRMS__c/ConverseRMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Converse RMS Setting</description>
    <label>ConverseRMS</label>
</CustomObject>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_CS_Confirm_To_WSL_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_CS_Confirm_To_WSL_Confirm__c</fullName>
    <label>Offset Of CS Confirm To WSL Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Delivered_To_Insp__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Delivered_To_Insp__c</fullName>
    <label>Offset Of Delivered To Insp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Inbound_To_Completed__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Inbound_To_Completed__c</fullName>
    <label>Offset Of Inbound To Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Insp_To_CS_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Insp_To_CS_Confirm__c</fullName>
    <label>Offset Of Insp To CS Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Kick_Off_To_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Kick_Off_To_PTLF__c</fullName>
    <label>Offset Of Kick Off To PTLF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_PTLF_To_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_PTLF_To_Delivered__c</fullName>
    <label>Offset Of PTLF To Delivered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_WSL_Confirm_To_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_WSL_Confirm_To_Inbound__c</fullName>
    <label>Offset Of WSL Confirm To Inbound</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Actual_Date_Of_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Delivered__c</fullName>
    <description>LF提货运输完成实际日期</description>
    <inlineHelpText>LF提货运输完成实际日期</inlineHelpText>
    <label>Actual Date Of Delivered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Application QTY</description>
    <inlineHelpText>Total Application QTY</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Expected_Date_Of_Inpected__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_Inpected__c</fullName>
    <description>LF质检完成预计日期</description>
    <inlineHelpText>LF质检完成预计日期</inlineHelpText>
    <label>Expected Date Of Inpected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Insp_CS_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_CS_Approve_Time__c</fullName>
    <description>CS审批Inspection的时间点</description>
    <label>Insp CS Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Insp_Final_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_Final_Approve_Time__c</fullName>
    <description>Inspection完全审批通过的时间点</description>
    <label>Insp Final Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Insp_Final_Reject_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_Final_Reject_Time__c</fullName>
    <description>Inspection被彻底Reject的时间点</description>
    <label>Insp Final Reject Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Insp_Submit_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_Submit_Time__c</fullName>
    <description>LF提交Inspection审批的时间点</description>
    <label>Insp Submit Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/LF_WH_Inbound_Date__c.field-meta.xml
<CustomField>
    <fullName>LF_WH_Inbound_Date__c</fullName>
    <description>LF仓库入库日期</description>
    <label>LF WH Inbound Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Summary_Date_Compute.cls
@IsTest(isParallel=true)
public  class Test_Trigger_RMS_Summary_Date_Compute {
    @IsTest
    public static void test() {
        RTV_Program__c program = new RTV_Program__c();
        insert program;

        ConverseRMS__c converseRMS = new ConverseRMS__c();
        converseRMS.Offset_Of_Kick_Off_To_PTLF__c = 1;
        converseRMS.Offset_Of_PTLF_To_Delivered__c = 1;
        converseRMS.Offset_Of_Insp_To_CS_Confirm__c = 1;
        converseRMS.Offset_Of_CS_Confirm_To_WSL_Confirm__c = 1;
        converseRMS.Offset_Of_WSL_Confirm_To_Inbound__c = 1;
        converseRMS.Offset_Of_Delivered_To_Insp__c = 1;
        converseRMS.Offset_Of_Inbound_To_Completed__c = 1;
        insert converseRMS;
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.Status__c = 'Pending';
        summary.Expected_Date_Of_Inpected__c = Date.today();
        summary.Application_QTY__c = 100;
        summary.RTV_Program__c = program.id;
        insert summary;

        summary.Status__c = 'Ready';
        update summary;

        summary.Expected_Date_Of_Inpected__c = Date.today().addDays(1);
        summary.Actual_Date_Of_Delivered__c = Date.today().addDays(1);
        summary.Actual_Date_Of_Delivered__c = Date.today();
        summary.Insp_Submit_Time__c = Datetime.now();
        summary.Insp_CS_Approve_Time__c = Datetime.now();
        summary.Insp_Final_Reject_Time__c = Datetime.now();
        summary.Insp_Final_Approve_Time__c = Datetime.now();
        summary.LF_WH_Inbound_Date__c = Date.today();
        summary.CS_Inbound_Date__c = Date.today();
        update summary;

        summary.Insp_Submit_Time__c = Datetime.now().addDays(1);
        summary.Insp_CS_Approve_Time__c = Datetime.now().addDays(1);
        summary.Insp_Final_Reject_Time__c = Datetime.now().addDays(1);
        summary.Insp_Final_Approve_Time__c = Datetime.now().addDays(1);
        summary.LF_WH_Inbound_Date__c = Date.today().addDays(1);
        summary.CS_Inbound_Date__c = Date.today().addDays(1);
        summary.Status__c = 'POST to LF';
        update summary;

        summary.Status__c = 'Completed';
        update summary;

    }
}