force-app/main/default/objects/ConverseRMS__c/ConverseRMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Converse RMS Setting</description>
    <label>ConverseRMS</label>
</CustomObject>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_CS_Confirm_To_WSL_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_CS_Confirm_To_WSL_Confirm__c</fullName>
    <label>Offset Of CS Confirm To WSL Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Delivered_To_Insp__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Delivered_To_Insp__c</fullName>
    <label>Offset Of Delivered To Insp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Inbound_To_Completed__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Inbound_To_Completed__c</fullName>
    <label>Offset Of Inbound To Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Insp_To_CS_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Insp_To_CS_Confirm__c</fullName>
    <label>Offset Of Insp To CS Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Kick_Off_To_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Kick_Off_To_PTLF__c</fullName>
    <label>Offset Of Kick Off To PTLF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_PTLF_To_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_PTLF_To_Delivered__c</fullName>
    <label>Offset Of PTLF To Delivered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_WSL_Confirm_To_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_WSL_Confirm_To_Inbound__c</fullName>
    <label>Offset Of WSL Confirm To Inbound</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/RTV_RP_Summary_Budget__c.object-meta.xml
<CustomObject>
    <description>Return program&apos;s budget for one wholesale</description>
    <label>RTV RP Summary Budget</label>
    <nameField>
        <displayFormat>RPS-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Summary Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Account Group</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>Budget MSRP (CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>Budget QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Return_Program__c.field-meta.xml
<CustomField>
    <fullName>Return_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Belongs to Return Program</description>
    <label>Return Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Tack_Back_Net__c.field-meta.xml
<CustomField>
    <fullName>Tack_Back_Net__c</fullName>
    <label>Budget Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Summary_Budget__c.field-meta.xml
<CustomField>
    <fullName>Summary_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup summary budget</description>
    <label>Summary Budget</label>
    <referenceTo>RTV_RP_Summary_Budget__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>RTV_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Summary_Ready_PostLF.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Summary_Ready_PostLF {
    @IsTest
    public static void test() {
        // setting
        if ([
            SELECT Offset_Of_Kick_Off_To_PTLF__c,
                Offset_Of_PTLF_To_Delivered__c,
                Offset_Of_Delivered_To_Insp__c,
                Offset_Of_Insp_To_CS_Confirm__c,
                Offset_Of_CS_Confirm_To_WSL_Confirm__c,
                Offset_Of_WSL_Confirm_To_Inbound__c,
                Offset_Of_Inbound_To_Completed__c 
            FROM ConverseRMS__c
        ].isEmpty()) {
            insert new ConverseRMS__c(
                Offset_Of_Kick_Off_To_PTLF__c = 1,
                Offset_Of_PTLF_To_Delivered__c = 1,
                Offset_Of_Delivered_To_Insp__c = 1,
                Offset_Of_Insp_To_CS_Confirm__c = 1,
                Offset_Of_CS_Confirm_To_WSL_Confirm__c = 1,
                Offset_Of_WSL_Confirm_To_Inbound__c = 1,
                Offset_Of_Inbound_To_Completed__c = 1
            );
        }
        
        // masterdata.account group
        RMS_Account_Group__c acgroup = new RMS_Account_Group__c();
        insert acgroup;
        
        // masterdata.soldto
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Account_Group__c = acgroup.Id;
        insert soldto;
        
        // masterdata.shipto
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = '100001';
        shipto.Sold_To_Code__c = soldto.Id;
        insert shipto;
        
        // program
        RTV_Program__c program = new RTV_Program__c();
        insert program;
        
        // summarybudget
        RTV_RP_Summary_Budget__c summaryBg = new RTV_RP_Summary_Budget__c();
        summaryBg.Return_Program__c = program.Id;
        summaryBg.Account_Group__c = acgroup.Id;
        summaryBg.Tack_Back_Net__c = 100;
        summaryBg.MSRP__c = 100;
        summaryBg.QTY__c = 100;
        insert summaryBg;
        
        // summary
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.RTV_Program__c = program.Id;
        summary.Account_Group__c = acgroup.Id;
        summary.Summary_Budget__c = summaryBg.Id;
        summary.Status__c = 'Pending';
        insert summary;
        
        // 创建所有AccountGroup下所有shipto白名单
        summary.Status__c = 'Ready';
        update summary;
        
        // 更新现有白名单
        summary.Status__c = 'Pending';
        update summary;
        summary.Status__c = 'Ready';
        update summary;
    }
}