force-app/main/default/objects/ConverseRMS__c/ConverseRMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Converse RMS Setting</description>
    <label>ConverseRMS</label>
</CustomObject>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_CS_Confirm_To_WSL_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_CS_Confirm_To_WSL_Confirm__c</fullName>
    <label>Offset Of CS Confirm To WSL Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Delivered_To_Insp__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Delivered_To_Insp__c</fullName>
    <label>Offset Of Delivered To Insp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Inbound_To_Completed__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Inbound_To_Completed__c</fullName>
    <label>Offset Of Inbound To Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Insp_To_CS_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Insp_To_CS_Confirm__c</fullName>
    <label>Offset Of Insp To CS Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Kick_Off_To_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Kick_Off_To_PTLF__c</fullName>
    <label>Offset Of Kick Off To PTLF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_PTLF_To_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_PTLF_To_Delivered__c</fullName>
    <label>Offset Of PTLF To Delivered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_WSL_Confirm_To_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_WSL_Confirm_To_Inbound__c</fullName>
    <label>Offset Of WSL Confirm To Inbound</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Access_Summary.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Access_Summary {
    @IsTest
    static void test() {
        // setting
        if ([
            SELECT Offset_Of_Kick_Off_To_PTLF__c,
                Offset_Of_PTLF_To_Delivered__c,
                Offset_Of_Delivered_To_Insp__c,
                Offset_Of_Insp_To_CS_Confirm__c,
                Offset_Of_CS_Confirm_To_WSL_Confirm__c,
                Offset_Of_WSL_Confirm_To_Inbound__c,
                Offset_Of_Inbound_To_Completed__c 
            FROM ConverseRMS__c
        ].isEmpty()) {
            insert new ConverseRMS__c(
                Offset_Of_Kick_Off_To_PTLF__c = 1,
                Offset_Of_PTLF_To_Delivered__c = 1,
                Offset_Of_Delivered_To_Insp__c = 1,
                Offset_Of_Insp_To_CS_Confirm__c = 1,
                Offset_Of_CS_Confirm_To_WSL_Confirm__c = 1,
                Offset_Of_WSL_Confirm_To_Inbound__c = 1,
                Offset_Of_Inbound_To_Completed__c = 1
            );
        }
        
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.OwnerId = UserInfo.getUserId();
        summary.Status__c = 'Pending';
        insert summary;
        
        summary.Status__c = 'Ready';
        update summary;
    }
}