force-app/main/default/objects/ConverseRMS__c/ConverseRMS__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Converse RMS Setting</description>
    <label>ConverseRMS</label>
</CustomObject>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_CS_Confirm_To_WSL_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_CS_Confirm_To_WSL_Confirm__c</fullName>
    <label>Offset Of CS Confirm To WSL Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Delivered_To_Insp__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Delivered_To_Insp__c</fullName>
    <label>Offset Of Delivered To Insp</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Inbound_To_Completed__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Inbound_To_Completed__c</fullName>
    <label>Offset Of Inbound To Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Insp_To_CS_Confirm__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Insp_To_CS_Confirm__c</fullName>
    <label>Offset Of Insp To CS Confirm</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_Kick_Off_To_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_Kick_Off_To_PTLF__c</fullName>
    <label>Offset Of Kick Off To PTLF</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_PTLF_To_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_PTLF_To_Delivered__c</fullName>
    <label>Offset Of PTLF To Delivered</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConverseRMS__c/fields/Offset_Of_WSL_Confirm_To_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Offset_Of_WSL_Confirm_To_Inbound__c</fullName>
    <label>Offset Of WSL Confirm To Inbound</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/RMS_Product__c.object-meta.xml
<CustomObject>
    <description>Base data - Product</description>
    <label>RMS Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>bu_all_all_gl</description>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FW</fullName>
            </value>
            <value>
                <fullName>APP/ACC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/BUCN__c.field-meta.xml
<CustomField>
    <fullName>BUCN__c</fullName>
    <description>bu_all_cn_rl</description>
    <label>BUCN</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>APP</fullName>
            </value>
            <value>
                <fullName>FTW-Core</fullName>
            </value>
            <value>
                <fullName>FTW-Seasonal</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>SS TEE</fullName>
            </value>
            <value>
                <fullName>WOVEN BOTTOM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <description>material_code_all_cn_rl</description>
    <label>Material Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>Manufacturer Suggested Retail Price
msrp_all_cn_rl</description>
    <inlineHelpText>Manufacturer Suggested Retail Price</inlineHelpText>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code CN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/Contact_Pr__c.field-meta.xml
<CustomField>
    <fullName>Contact_Pr__c</fullName>
    <description>联系人</description>
    <label>Contact Pr</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/RMS_TradingTerm__c.object-meta.xml
<CustomObject>
    <description>TradingTerm history</description>
    <label>RMS TradingTerm</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS TradingTerm</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_TradingTerm__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <formula>SUBSTITUTE(Name, TEXT(Year__c), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sold-To Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_US_Size__c/RMS_US_Size__c.object-meta.xml
<CustomObject>
    <description>US Size参照表</description>
    <label>RMS US Size</label>
    <nameField>
        <displayFormat>Size-{000000}</displayFormat>
        <label>US Size Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMS US Size</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_US_Size__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/RTV_RP_Ship_To__c.object-meta.xml
<CustomObject>
    <description>允许回收的Sold-to&amp;Ship-to白名单</description>
    <label>RTV RP Ship To</label>
    <nameField>
        <displayFormat>WL-{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Ship To White List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <formula>Summary_Budget__r.Account_Group__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RMS_Ship_To__c.Sold_To_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sold_To__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipLabel>RTV RP Ship To List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipName>Return_Account_White_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/RTV_RP_SKU_Budget__c.object-meta.xml
<CustomObject>
    <description>Return summary of one product.</description>
    <label>RTV RP SKU Budget</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Sku Budget Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP SKU Budget</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Account Group 维度的 Product 预算</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP SKU Budget</relationshipLabel>
    <relationshipName>RTV_RP_SKU_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <formula>RP_Ship_To__r.Ship_To__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ship-To</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_SKU_Budget__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Sold To 维度的 Product 预算</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RTV RP SKU Budget</relationshipLabel>
    <relationshipName>RTV_RP_SKU_Budget</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/RTV_RP_Summary_Budget__c.object-meta.xml
<CustomObject>
    <description>Return program&apos;s budget for one wholesale</description>
    <label>RTV RP Summary Budget</label>
    <nameField>
        <displayFormat>RPS-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Summary Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Account Group</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>Budget MSRP (CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>SAP CSV空白列</description>
    <label>BU</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_RTV_Order_UploadPackingCtrl.cls
@IsTest(isParallel=true)
public class Test_RTV_Order_UploadPackingCtrl {
    @isTest
    public static void test() {
        // setting
        if ([
            SELECT Offset_Of_Kick_Off_To_PTLF__c,
                Offset_Of_PTLF_To_Delivered__c,
                Offset_Of_Delivered_To_Insp__c,
                Offset_Of_Insp_To_CS_Confirm__c,
                Offset_Of_CS_Confirm_To_WSL_Confirm__c,
                Offset_Of_WSL_Confirm_To_Inbound__c,
                Offset_Of_Inbound_To_Completed__c 
            FROM ConverseRMS__c
        ].isEmpty()) {
            insert new ConverseRMS__c(
                Offset_Of_Kick_Off_To_PTLF__c = 1,
                Offset_Of_PTLF_To_Delivered__c = 1,
                Offset_Of_Delivered_To_Insp__c = 1,
                Offset_Of_Insp_To_CS_Confirm__c = 1,
                Offset_Of_CS_Confirm_To_WSL_Confirm__c = 1,
                Offset_Of_WSL_Confirm_To_Inbound__c = 1,
                Offset_Of_Inbound_To_Completed__c = 1
            );
        }
        
        // masterdata.product
        RMS_Product__c product = new RMS_Product__c();
        product.Material_Code__c = '[material]';
        product.Season_Code_CN__c = '20Q1';
        product.BUCN__c = 'APP';
        product.MSRP__c = 123.45;
        insert product;
        
        // masterdata.ussize
        if ([SELECT Id FROM RMS_US_Size__c WHERE BU__c='AP' AND Size__c='29'].isEmpty()) {
            insert new RMS_US_Size__c(BU__c='AP', Size__c='29');
        }
        
        // masterdata.account group
        RMS_Account_Group__c acgroup = new RMS_Account_Group__c();
        insert acgroup;
        
        // masterdata.soldto
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Account_Group__c = acgroup.Id;
        soldto.Name = 'xxxxx';
        insert soldto;
        
        // masterdata.shipto
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = '100001';
        shipto.Sold_To_Code__c = soldto.Id;
        shipto.Contact_Pr__c = 'xxxxx';
        shipto.Contact_Tel__c = 'xxxxx';
        shipto.Dely_Addr__c = 'xxxxxxxxx';
        insert shipto;
        
        // masterdata.tradingterm
        RMS_TradingTerm__c tradeTerm = new RMS_TradingTerm__c();
        tradeTerm.Name = soldto.Name+'2020';
        tradeTerm.TT_APP_ACC__c = 0.9;
        tradeTerm.TT_FTW_EG__c = 0.9;
        tradeTerm.TT_FW_Seasonal__c = 0.9;
        tradeTerm.Year__c = 2020;
        insert tradeTerm;
        
        // program
        RTV_Program__c program = new RTV_Program__c();
        insert program;
        
        // summarybudget
        RTV_RP_Summary_Budget__c summaryBg = new RTV_RP_Summary_Budget__c();
        summaryBg.Return_Program__c = program.Id;
        summaryBg.Account_Group__c = acgroup.Id;
        summaryBg.Tack_Back_Net__c = 1000000;
        summaryBg.MSRP__c = 100000;
        summaryBg.QTY__c = 1000000;
        insert summaryBg;
        
        // skubudget
        RTV_RP_Sku_Budget__c skuWL = new RTV_RP_Sku_Budget__c();
        skuWL.Return_Program__c = program.Id;
        skuWL.Sku_Material_Code__c = '[material]';
        insert skuWL;
        
        // summary
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.RTV_Program__c = program.Id;
        summary.Account_Group__c = acgroup.Id;
        summary.Summary_Budget__c = summaryBg.Id;
        summary.Status__c = 'Pending';
        insert summary;
        
        // shipto-whitelist
        RTV_RP_Ship_To__c shiptoWL = new RTV_RP_Ship_To__c();
        shiptoWL.Sold_To__c = soldto.Id;
        shiptoWL.Ship_To__c = shipto.Id;
        shiptoWL.RTV_Program__c = program.Id;
        shiptoWL.Summary__c = summary.Id;
        shiptoWL.Summary_Budget__c = summaryBg.Id;  
        insert shiptoWL;
        
        // summary -> kickoff
        summary.Status__c = 'Ready';
        update summary;
        
        // 获取 shipto-whitelist
        shiptoWL = [SELECT Id, Order_Auth_Code__c FROM RTV_RP_Ship_To__c WHERE Id = :shiptoWL.Id];
        
        // --------------------
        // 开始test
        // --------------------
        ApexPages.currentPage().getParameters().put('id', summary.Id);
        RTV_Order_UploadPackingCtrl ctrl = new RTV_Order_UploadPackingCtrl();
        ctrl.cancel();
        
        System.debug(ctrl.shipToSelectOptions.toString());
        ctrl.shipToSelected = 'from_csv';
        
        ctrl.fileUploadName = 'xxxx';
        ctrl.getFileCharset();
        ctrl.setFileCharset('UTF-8');
        
        // --------------------------------
        // 错误
        // --------------------------------
        // 错误：空文件
        ctrl.upload();
        
        Test.startTest();
        try {
            ctrl.fileUploadBody = Blob.valueof('\r' +
                '授权码,箱号,货品号,BU,尺寸(美码),尺寸(亚码),季节码,数量,Sold To,Ship To,最早提货日\r' + 
                '--Error------------------'+'AP'+',[box],[material],AP,29,30,20Q1,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r' +
                shiptoWL.Order_Auth_Code__c+'AP'+',[box],[error---],AP,29,30,20Q1,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r' +
                shiptoWL.Order_Auth_Code__c+'AP'+',[box],[material],AP,29,30,??Q?,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r' +
                shiptoWL.Order_Auth_Code__c+'AP'+',[box],[material],AP,29,30,20Q1,3,' + soldto.Name + ',' + '--error--' + ',2030/1/1\r' +
                shiptoWL.Order_Auth_Code__c+'AP'+',[box],[material],AP,29,30,20Q1,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r' +
                shiptoWL.Order_Auth_Code__c+'AP'+',[box],[material],AP,29,30,20Q1,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r' +
                shiptoWL.Order_Auth_Code__c+'FW'+',[box],[material],FW,29,30,20Q1,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r' +
                shiptoWL.Order_Auth_Code__c+'AP'+',[bo2],[material],AP,29,30,20Q1,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r'
            );
            ctrl.upload();
            
            ctrl.fileUploadBody = Blob.valueof('\r' +
                '授权码,箱号,货品号,BU,尺寸(美码),尺寸(亚码),季节码,数量,Sold To,Ship To,最早提货日\r' + 
                shiptoWL.Order_Auth_Code__c+'AP'+',[box],[material],AP,29,30,20Q1,3,' + soldto.Name + ',' + shipto.Name + ',2030/1/1\r'
            );
            ctrl.upload();
            System.debug(ctrl.loadingPercent);
        } 
        finally {
            Test.stopTest();
            ctrl.checkUploadResult();
        }
    }
}