force-app/main/default/objects/RMS_Product__c/RMS_Product__c.object-meta.xml
<CustomObject>
    <description>Base data - Product</description>
    <label>RMS Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/fields/BUCN__c.field-meta.xml
<CustomField>
    <fullName>BUCN__c</fullName>
    <description>bu_all_cn_rl</description>
    <label>BUCN</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>APP</fullName>
            </value>
            <value>
                <fullName>FTW-Core</fullName>
            </value>
            <value>
                <fullName>FTW-Seasonal</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>SS TEE</fullName>
            </value>
            <value>
                <fullName>WOVEN BOTTOM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <description>material_code_all_cn_rl</description>
    <label>Material Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code CN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <description>product_sku_code_all_cn_rl</description>
    <label>SKU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Auth_Code__c</fullName>
    <externalId>true</externalId>
    <label>Order Auth Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/LF_Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>LF_Order_Auth_Code__c</fullName>
    <description>LF Order Auth Code</description>
    <formula>RTV_Order__r.Name + BU_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LF Order Auth Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/POS_SKU__c.field-meta.xml
<CustomField>
    <fullName>POS_SKU__c</fullName>
    <description>POS机中读取的SKU全值</description>
    <label>POS SKU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code (CN)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_RTV_Order_UploadInspectCtrl_DTC.cls
@IsTest(isParallel=true)
public class Test_RTV_Order_UploadInspectCtrl_DTC {
    @isTest
    public static void test() {
        RMS_Product__c product = new RMS_Product__c();
        product.Material_Code__c = '[material]';
        product.BUCN__c = 'APP';
        product.Season_Code_CN__c = '20Q1';
        product.SKU__c = '[material]00';
        insert product;
        
        RTV_Order__c order = new RTV_Order__c();
        order.Status__c = 'Delivered';
        order.Name = '000001';
        order.Order_Auth_Code__c = order.Name;
        insert order;
        
        RTV_Order_Item__c item = new RTV_Order_Item__c();
        item.RTV_Order__c = order.Id;
        item.Material_Code__c = '[material]';
        item.BU_2__c = 'AP';
        item.SKU_Size_US__c = 'XL';
        item.POS_SKU__c = product.SKU__c + item.SKU_Size_US__c;
        insert item;
        
        item = [SELECT LF_Order_Auth_Code__c FROM RTV_Order_Item__c WHERE id = :item.Id];
        
        // ----------------------------
        // 开始测试
        // ----------------------------
        ApexPages.currentPage().getParameters().put('orderId', order.Id);
        RTV_Order_UploadInspectCtrl_DTC ctrl = new RTV_Order_UploadInspectCtrl_DTC();
        ctrl.cancel();
        ctrl.getFileCharset();
        ctrl.setFileCharset('UTF-8');
        
        // 空文件
        ctrl.upload();
        
        // 错误
        ctrl.createItemIfNotFound = true;
        ctrl.fileUploadName = 'xxxx';
        // ctrl.fileUploadBody = Blob.valueof('\r'
        //     + '退货授权号,Bar Code,Material code,Style,Color,Size,季节码,申请数量,实收,差异,A,B,C,D,Reason code\r'
        //     + item.LF_Order_Auth_Code__c + ',[Bar Code],[error],style,color,XL,20Q1,3,3,0,1,1,1,1,A\r'
        // );
        // ctrl.upload();
        
        // 上传
        ctrl.createItemIfNotFound = true;
        ctrl.fileUploadBody = Blob.valueof('\r'
            + '退货授权号,Bar Code,Material code,Style,Color,Size,季节码,申请数量,实收,差异,A,B,C,D,Reason code\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,A\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,B1\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,B2\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,B3\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,B4\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,B5\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,B6\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,B7\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C1\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C2-1\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C2-2\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C2-3\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C2-4\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C2-5\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C2-6\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,C2-7\r'
            + item.LF_Order_Auth_Code__c + ',[Bar Code],[material],style,color,XL,20Q1,3,3,0,1,1,1,1,D\r'
        );
        ctrl.upload();
        
        // 更新
        ctrl.upload();
    }
}