force-app/main/default/objects/RMS_Product__c/RMS_Product__c.object-meta.xml
<CustomObject>
    <description>Base data - Product</description>
    <label>RMS Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/fields/BUCN__c.field-meta.xml
<CustomField>
    <fullName>BUCN__c</fullName>
    <description>bu_all_cn_rl</description>
    <label>BUCN</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>APP</fullName>
            </value>
            <value>
                <fullName>FTW-Core</fullName>
            </value>
            <value>
                <fullName>FTW-Seasonal</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>SS TEE</fullName>
            </value>
            <value>
                <fullName>WOVEN BOTTOM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>Manufacturer Suggested Retail Price
msrp_all_cn_rl</description>
    <inlineHelpText>Manufacturer Suggested Retail Price</inlineHelpText>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <description>Trading Term(APP/ ACC)</description>
    <inlineHelpText>Trading Term(APP/ ACC)</inlineHelpText>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FTW_EG__c.field-meta.xml
<CustomField>
    <fullName>TT_FTW_EG__c</fullName>
    <description>Trading Term(FW-AS CORE)</description>
    <inlineHelpText>Trading Term(FW-AS CORE)</inlineHelpText>
    <label>TT(FW-AS CORE)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FW_Seasonal__c.field-meta.xml
<CustomField>
    <fullName>TT_FW_Seasonal__c</fullName>
    <description>Trading Term(Trading Term)</description>
    <inlineHelpText>Trading Term(Trading Term)</inlineHelpText>
    <label>TT(FW-Seasonal)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/RMS_TradingTerm__c.object-meta.xml
<CustomObject>
    <description>TradingTerm history</description>
    <label>RMS TradingTerm</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS TradingTerm</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_TradingTerm__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/fields/TT_FTW_EG__c.field-meta.xml
<CustomField>
    <fullName>TT_FTW_EG__c</fullName>
    <label>TT(FW-AS CORE)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/fields/TT_FW_Seasonal__c.field-meta.xml
<CustomField>
    <fullName>TT_FW_Seasonal__c</fullName>
    <label>TT(FW-Seasonal)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>单价（Manufacturer Suggested Retail Price）</description>
    <inlineHelpText>Manufacturer Suggested Retail Price</inlineHelpText>
    <label>MSRP (CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Return method(discount% on return)</description>
    <inlineHelpText>Return method(discount% on return)</inlineHelpText>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/ExRate__c.field-meta.xml
<CustomField>
    <fullName>ExRate__c</fullName>
    <defaultValue>$Setup.ConverseRMS__c.ExRate__c</defaultValue>
    <description>汇率</description>
    <label>ExRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>$Setup.ConverseRMS__c.TaxRate__c</defaultValue>
    <description>税率</description>
    <label>TaxRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_RMS_CommonUtil.cls
@IsTest(isParallel=true)
public class Test_RMS_CommonUtil {
    @isTest
    public static void test() {
        RMS_CommonUtil.getRecordTypes('RTV_Order__c');
        
        RMS_CommonUtil.summary_getName('programName', 'accountGroupName');
        
        RMS_CommonUtil.order_getCode('aaaa', 'bbbbb', 'xxx');
        RMS_CommonUtil.order_getLFCode('orderAuthCode', 'bu2');
        
        RMS_CommonUtil.defect_getCode('xxx','xxx');
        
        RMS_CommonUtil.item_getName(new RTV_Order_Item__c());
        
        RMS_CommonUtil.item_getUniqueKey('orderAuthCode', new RTV_Order_Item__c());
        RMS_CommonUtil.item_getUniqueKeyDef('orderAuthCode', new RTV_Order_Item__c(), 1, 1);
        
        RMS_CommonUtil.item_Def_IsNoDelivery('无实物退残');
        RMS_CommonUtil.item_Def_IsNoDelivery('xx');
        RMS_CommonUtil.item_Def_IsSepical('特批');
        
        RMS_CommonUtil.item_getBu2('AP');
        RMS_CommonUtil.item_getBu2('AC');
        RMS_CommonUtil.item_getBu2('FW');
        try{
            RMS_CommonUtil.item_getBu2('XXX');
        }catch(Exception err){}
        
        // 计算TradingTerm >>
        RMS_Sold_To__c soldTo = new RMS_Sold_To__c();
        soldTo.TT_APP_ACC__c = 1.2;
        soldTo.TT_FW_Seasonal__c = 1.2;
        soldTo.TT_FTW_EG__c = 1.2;
        
        RTV_Program__c program = new RTV_Program__c();
        program.TaxRate__c = 1.7;
        program.ExRate__c = 0.8;
        program.Discount__c = 0.5;
        
        // 计算TradingTerm
        RMS_TradingTerm__c tradeTerm = new RMS_TradingTerm__c();
        RMS_CommonUtil.item_getTradeTerm_TB('APP', tradeTerm);
        RMS_CommonUtil.item_getTradeTerm_TB('FW', tradeTerm);
        RMS_CommonUtil.item_getTradeTerm_TB('FW', null);
        RMS_CommonUtil.item_getTradeTerm_DEF('APP', tradeTerm, false);
        RMS_CommonUtil.item_getTradeTerm_DEF('FW', tradeTerm, true);
        RMS_CommonUtil.item_getTradeTerm_DEF('FW', tradeTerm, false);
        RMS_CommonUtil.item_getTradeTerm_DEF('FW', null, false);
        
        // 计算Net
        RMS_Product__c pdt = new RMS_Product__c();
        pdt.BUCN__c = 'APP';
        pdt.MSRP__c = 10.2;
        RMS_CommonUtil.item_getNet(pdt, program, 0.7);
        RMS_CommonUtil.item_getNet(pdt, 0.7);
        
        // 字符串转日期
        try{
            RMS_CommonUtil.str2Date('2019/1/29');
        } catch(Exception err){
        }
        try{
            RMS_CommonUtil.str2Date('1/29/2019');
        } catch(Exception err){
        }
        try{
            RMS_CommonUtil.str2Date('2019/1/55');
        } catch(Exception err){
        }
        try{
            RMS_CommonUtil.str2Date('123456');
        } catch(Exception err){
        }
        // str2Decimal
        RMS_CommonUtil.str2Decimal('1', 0);
        RMS_CommonUtil.str2Decimal('xx', 0);
        
        // message
        RMS_CommonUtil.pageAddMessage(ApexPages.Severity.INFO, 'xxx');
        
        // size
        RMS_CommonUtil.size_Us2Asia('XL', 'AP');
        RMS_CommonUtil.size_Asia2Us('L', 'AP');
        RMS_CommonUtil.size_lfUs2Us('10', 'FW');
        
        // ***** shareToRoleSubordinates *****
        try {
            RTV_Order__c order = new RTV_Order__c();
            insert order;
            
            Group grp = [SELECT RelatedId, Type FROM Group WHERE Type = 'RoleAndSubordinates' LIMIT 1];
            
            Map<Id, Id> objAndRoleIds = new Map<Id, Id>();
            objAndRoleIds.put(order.Id, grp.RelatedId);
            
            RMS_CommonUtil.shareToRoleSubordinates(objAndRoleIds, RTV_Order__Share.SObjectType, 'Read');
        } catch(Exception err) {
        }
        // ***** shareToRoleSubordinates *****
        
        new RMS_CommonUtil.LoginUserInfo();
    }
}