force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Owner_AccountGroup.cls
@IsTest(SeeAllData=true)
public class Test_Trigger_RMS_Owner_AccountGroup {
    @IsTest
    public static void test() {
        RMS_Account_Group__c acg = new RMS_Account_Group__c();
        acg.Name = 'xxx';
        insert acg;
        
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Account_Group__c = acg.Id;
        soldto.Name = 'xxxxx';
        insert soldto;
        
        acg.OwnerId = [SELECT Id FROM User WHERE Id != :UserInfo.getUserId() LIMIT 1][0].Id;
        update acg;
    }
}