force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/DTC_Code__c.field-meta.xml
<CustomField>
    <fullName>DTC_Code__c</fullName>
    <description>CFS直营门店或者Digital五大仓</description>
    <label>DTC Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/fields/IsDtcValid__c.field-meta.xml
<CustomField>
    <fullName>IsDtcValid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>DTC是否有效（初始只有五个有效）</description>
    <label>IsDtcValid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV DEF Summary</relationshipLabel>
    <relationshipName>RTV_DEF_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <label>DTC Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>DIG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <description>PS：因为Number字段类型会显示千分符，所以选Text类型</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_RTV_DEF_Summary_DTC.cls
@IsTest(isParallel=true)
public class Test_RTV_DEF_Summary_DTC {
    @isTest
    public static void test() {
        RMS_Account_Group__c accgrp = new RMS_Account_Group__c();
        accgrp.Name = '00)CC';
        insert accgrp;
        
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Name = '12345';
        soldto.Account_Group__c = accgrp.Id;
        insert soldto;
        
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = '1234567';
        shipto.DTC_Code__c = '1001';
        shipto.Sold_To_Code__c = soldto.Id;
        shipto.OwnerId = UserInfo.getUserId();
        shipto.IsDtcValid__c = true;
        insert shipto;
        
        RTV_DEF_Summary__c summary = new RTV_DEF_Summary__c();
        summary.Account_Group__c = accgrp.Id;
        summary.Year__c = '2021';
        summary.Month__c = 3;
        insert summary;
        
        // ----------------------------
        // 开始测试
        // ----------------------------
        RTV_DEF_Summary_DTC ctrl = new RTV_DEF_Summary_DTC(new ApexPages.StandardController(summary));
        ctrl.getLoginUser();
        ctrl.loadPage();
        System.debug(ctrl.orders_Cnt);
        
        // ----------------------------
        // createOrderForm
        // ----------------------------
        ctrl.createOrderForm.open();
        ctrl.createOrderForm.close();
        System.debug(ctrl.CreateOrderForm.error);
        
        ctrl.summary.DTC_Type__c = 'CFS';
        ctrl.createOrderForm.inputStoreCode = shipto.DTC_Code__c;
        ctrl.createOrderForm.submit();
        
        ctrl.summary.DTC_Type__c = 'DIG';
        ctrl.createOrderForm.inputShipToCode = shipto.Name;
        ctrl.createOrderForm.submit();
        ctrl.createOrderForm.submit();
        
        ctrl.summary.DTC_Type__c = 'CFS';
        ctrl.createOrderForm.inputShipToCode = 'error';
        ctrl.createOrderForm.submit();
        
        // ----------------------------
        // ApprovalSubmitForm
        // ----------------------------
        ctrl.appSubmitForm.open();
        ctrl.appSubmitForm.close();
        ctrl.appSubmitForm.submit();
        ctrl.appSubmitForm.isSubmiterChecked = true;
        ctrl.appSubmitForm.submit();
        
        // ----------------------------
        // ApprovalForm
        // ----------------------------
        ctrl.approveForm.open();
        ctrl.approveForm.close();
        ctrl.approveForm.approve();
        ctrl.approveForm.reject();
    }
}