force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/DTC_Rebuy__c.field-meta.xml
<CustomField>
    <fullName>DTC_Rebuy__c</fullName>
    <defaultValue>false</defaultValue>
    <description>dtc场合，rebuy默认未选择</description>
    <label>Rebuy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_Trigger_RTV_Program_InitRebuy.cls
@IsTest(isParallel=true)
public class Test_Trigger_RTV_Program_InitRebuy {
    @isTest
    public static void test() {
        RMS_Account_Group__c acgCC = new RMS_Account_Group__c();
        acgCC.Name = '00)CC';
        insert acgCC;
        
        RTV_Program__c program = new RTV_Program__c();
        program.RecordTypeId = RMS_CommonUtil.getRecordTypes('RTV_Program__c').get('CFS DTC Takeback Kick Off').Id;
        program.DTC_Rebuy__c = true;
        insert program;
    }
}