force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_FTW_Core_List__c/RMS_FTW_Core_List__c.object-meta.xml
<CustomObject>
    <description>常青款</description>
    <label>RMS FTW Core List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS FTW Core List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/RMS_Product__c.object-meta.xml
<CustomObject>
    <description>Base data - Product</description>
    <label>RMS Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>bu_all_all_gl</description>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FW</fullName>
            </value>
            <value>
                <fullName>APP/ACC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/BUCN__c.field-meta.xml
<CustomField>
    <fullName>BUCN__c</fullName>
    <description>bu_all_cn_rl</description>
    <label>BUCN</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>APP</fullName>
            </value>
            <value>
                <fullName>FTW-Core</fullName>
            </value>
            <value>
                <fullName>FTW-Seasonal</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>SS TEE</fullName>
            </value>
            <value>
                <fullName>WOVEN BOTTOM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <description>material_code_all_cn_rl</description>
    <label>Material Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>Manufacturer Suggested Retail Price
msrp_all_cn_rl</description>
    <inlineHelpText>Manufacturer Suggested Retail Price</inlineHelpText>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code CN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <description>Trading Term(APP/ ACC)</description>
    <inlineHelpText>Trading Term(APP/ ACC)</inlineHelpText>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FTW_EG__c.field-meta.xml
<CustomField>
    <fullName>TT_FTW_EG__c</fullName>
    <description>Trading Term(FW-AS CORE)</description>
    <inlineHelpText>Trading Term(FW-AS CORE)</inlineHelpText>
    <label>TT(FW-AS CORE)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FW_Seasonal__c.field-meta.xml
<CustomField>
    <fullName>TT_FW_Seasonal__c</fullName>
    <description>Trading Term(Trading Term)</description>
    <inlineHelpText>Trading Term(Trading Term)</inlineHelpText>
    <label>TT(FW-Seasonal)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/RMS_TradingTerm__c.object-meta.xml
<CustomObject>
    <description>TradingTerm history</description>
    <label>RMS TradingTerm</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS TradingTerm</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_TradingTerm__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <formula>SUBSTITUTE(Name, TEXT(Year__c), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sold-To Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/fields/TT_FTW_EG__c.field-meta.xml
<CustomField>
    <fullName>TT_FTW_EG__c</fullName>
    <label>TT(FW-AS CORE)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/fields/TT_FW_Seasonal__c.field-meta.xml
<CustomField>
    <fullName>TT_FW_Seasonal__c</fullName>
    <label>TT(FW-Seasonal)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>年度</description>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RTV_Defective_UploadPackingListCtrl.cls
@IsTest(isParallel=true)
public with sharing class Test_RTV_Defective_UploadPackingListCtrl {
    @IsTest
    private static void test()
    {
        // 数据 soldto ~ shipto
        RMS_Account_Group__c acgroup = new RMS_Account_Group__c();
        insert acgroup;
        
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldTo.Name = 'xxxx';
        soldto.Account_Group__c = acgroup.Id;
        soldTo.TT_APP_ACC__c = 1.2;
        soldTo.TT_FW_Seasonal__c = 1.2;
        soldTo.TT_FTW_EG__c = 1.2;
        insert soldto;
        
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = '100001';
        shipto.Sold_To_Code__c = soldto.Id;
        insert shipto;
        
        // 数据 order
        RTV_Order__c order = new RTV_Order__c();
        order.Sold_To__c = soldto.Id;
        order.Ship_To__c = shipto.Id;
        insert order;
        
        // 数据 product
        RMS_Product__c product = new RMS_Product__c();
        product.Material_Code__c = '[material]';
        product.Season_Code_CN__c = '21Q1';
        product.BU__c = 'APP';
        product.BUCN__c = 'APP';
        product.MSRP__c = 123.45;
        insert product;
        
        RMS_FTW_Core_List__c ftwCore = new RMS_FTW_Core_List__c();
        ftwCore.Name = product.Name;
        insert ftwCore;
        
        // masterdata.tradingterm
        RMS_TradingTerm__c tradeTerm = new RMS_TradingTerm__c();
        tradeTerm.Name = soldto.Name+'2021';
        tradeTerm.TT_APP_ACC__c = 0.9;
        tradeTerm.TT_FTW_EG__c = 0.9;
        tradeTerm.TT_FW_Seasonal__c = 0.9;
        tradeTerm.Year__c = 2021;
        insert tradeTerm;
        
        // 测试controller
        Apexpages.currentPage().getParameters().put('id',order.id);
        RTV_Defective_UploadPackingListCtrl ctrl = new RTV_Defective_UploadPackingListCtrl();
        
        // 空
        ctrl.uploadFile();
        
        // 新增item
        ctrl.fileUploadName = 'xxxx';
        ctrl.getFileCharset();
        ctrl.setFileCharset('UTF-8');
        
        
        // 错误
        ctrl.fileUploadBody = Blob.valueof(
            '\r' +
            '箱号,货品号,尺寸(美码),尺寸(亚码),BU,季节码,数量,零售价,退货理由(必填),原残/客残,备注\r' + 
            '[box],[material],6,,AP,21Q1,2,599,[退货理由],原残,特批\r'
        );
        ctrl.uploadFile();
        
        // 错误
        ctrl.fileUploadBody = Blob.valueof(
            '\r' +
            '箱号,货品号,尺寸(美码),尺寸(亚码),BU,季节码,数量,零售价,退货理由(必填),原残/客残,备注\r' + 
            '[box],[material],6,,AP,xxxQxx,2,599,[退货理由],原残,\r' +
            '[box],[material],6,,AP,21Q1,2,599,,原残,\r' +
            '[box],[material],6,,FW,21Q1,1,599,[退货理由],原残,\r' +
            '[box],[material],6,,AP,21Q1,1,599,,原残,\r' +
            '[box],[material],6,,AP,21Q1,1,599,鞋盒,原残,\r' +
            '[box],错误,7,AP,21Q1,1,469,[退货理由],原残,\r'
        );
        ctrl.uploadFile();
        
        // 正确
        ctrl.fileUploadBody = Blob.valueof(
            '\r' +
            '箱号,货品号,尺寸(美码),尺寸(亚码),BU,季节码,数量,零售价,退货理由(必填),原残/客残,备注\r' + 
            '[box],[material],6,,AP,21Q1,2,599,[退货理由],原残,\r' +
            '[box],[material],6,,AP,21Q1,1,599,[退货理由],原残,\r'
        );
        ctrl.uploadFile();
        
        // 关闭
        ctrl.cancel();
        
        // -----------------------
        // 上传特批附件
        // -----------------------
        ctrl.specialDef.inputFileBody = Blob.valueOf('xx');
        ctrl.specialDef.inputFileName = 'xx.txt';
        try { ctrl.specialDef.uploadFile(); }catch(Exception err){}
        try { ctrl.specialDef.deleteFile(); }catch(Exception err){}
    }
}