force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Code_Add__c.field-meta.xml
<CustomField>
    <fullName>Code_Add__c</fullName>
    <description>code add</description>
    <label>Code Add</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Log__c/RTV_Log__c.object-meta.xml
<CustomObject>
    <description>自定义日志</description>
    <label>RTV Log</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Log__c/fields/Batch_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_ID__c</fullName>
    <label>Batch Job ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Log__c/fields/Errors__c.field-meta.xml
<CustomField>
    <fullName>Errors__c</fullName>
    <label>Errors</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Return method(discount% on return)</description>
    <inlineHelpText>Return method(discount% on return)</inlineHelpText>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/ExRate__c.field-meta.xml
<CustomField>
    <fullName>ExRate__c</fullName>
    <defaultValue>$Setup.ConverseRMS__c.ExRate__c</defaultValue>
    <description>汇率</description>
    <label>ExRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>$Setup.ConverseRMS__c.TaxRate__c</defaultValue>
    <description>税率</description>
    <label>TaxRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/RTV_RP_Ship_To__c.object-meta.xml
<CustomObject>
    <description>允许回收的Sold-to&amp;Ship-to白名单</description>
    <label>RTV RP Ship To</label>
    <nameField>
        <displayFormat>WL-{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Ship To White List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <formula>Summary_Budget__r.Account_Group__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Auth_Code__c</fullName>
    <label>Order Auth Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Removed__c.field-meta.xml
<CustomField>
    <fullName>Removed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>删除标记</description>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RMS_Ship_To__c.Sold_To_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sold_To__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipLabel>RTV RP Ship To List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup RTV Summary</description>
    <label>Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Summary_Budget__c.field-meta.xml
<CustomField>
    <fullName>Summary_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Summary Budget</description>
    <label>Summary Budget</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RTV_RP_Summary_Budget__c.Return_Program__c</field>
            <operation>equals</operation>
            <valueField>$Source.RTV_Program__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RTV_RP_Summary_Budget__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/RTV_RP_Summary_Budget__c.object-meta.xml
<CustomObject>
    <description>Return program&apos;s budget for one wholesale</description>
    <label>RTV RP Summary Budget</label>
    <nameField>
        <displayFormat>RPS-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Summary Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Account Group</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>Budget QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Tack_Back_Net__c.field-meta.xml
<CustomField>
    <fullName>Tack_Back_Net__c</fullName>
    <label>Budget Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Application_Amount__c.field-meta.xml
<CustomField>
    <fullName>Application_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Application Amount of orders</description>
    <inlineHelpText>Total Application Amount of orders</inlineHelpText>
    <label>Application Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Application QTY</description>
    <inlineHelpText>Total Application QTY</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Summary_Budget__c.field-meta.xml
<CustomField>
    <fullName>Summary_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup summary budget</description>
    <label>Summary Budget</label>
    <referenceTo>RTV_RP_Summary_Budget__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>RTV_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTV_Order_UploadPackingCtrl.cls
public with sharing class RTV_Order_UploadPackingCtrl {
    /** url参数: summaryId */
    public String summaryId = ApexPages.currentPage().getParameters().get('id');
    
    /** 上传的文件正文 */
    public transient Blob fileUploadBody {get; set;}
    public String fileUploadName {get; set;}
    
    /** 文件编码 */
    public List<ApexPages.SelectOption> fileCharsetOpts {get{return RMS_CSV_Iterator.CHARSET_OPTIONS;}}
    public String fileCharset = fileCharsetOpts.get(0).getValue();
    public String getFileCharset() {return fileCharset;}
    public void setFileCharset(String value) {this.fileCharset=value;}
    
    /** 当前rtv_summary */
    public RTV_Summary__c summary {get; set;}
    
    /** admin用户的profile */
    private static String[] adminProfiles = new String[]{
        'System Administrator', '系统管理员', 'RMS Admin', 'RMS CS', 'RMS WSL HQ'
    };
    /** 可以从csv中指定shipto的用户profile */
    private static String[] csvShipToProfiles = new String[]{
        'System Administrator', '系统管理员', 'RMS Admin', 'RMS CS', 'RMS WSL HQ', 'RMS WSL Reg Branch', 'RMS WSL Sold To'
    };
    
    /** 现存数据：ShipTo白名单 */
    private Map<String, RTV_RP_Ship_To__c> shipToWhiteList;
    
    /** 页面选择的shipTo */
    public String shipToSelected {get; set;}
    public List<SelectOption> shipToSelectOptions {get; set;}

    /** 执行中的uploadBatch的job对象 */
    public AsyncApexJob uploadJob {get; set;}
    public Attachment resErrCsvFile {get; set;}
    public Boolean isLoading {get; set;}
    public Integer loadingPercent {get{ return getJobPercent(this.uploadJob); }}
    
    /**
     * 构造方法
     */
    public RTV_Order_UploadPackingCtrl() {
        this.querySummary();
        this.queryTargetShipToList();
    }
    
    /** 检索summary(页面初期化和每次上传后检索) */
    private void querySummary() {
        // 查询summary和program
        this.summary = [
            SELECT Id, Name, Account_Group__c, Account_Group__r.Name,
                Application_QTY__c, Application_Amount__c,
                Summary_Budget__r.QTY__c, Summary_Budget__r.Tack_Back_Net__c,
                RTV_Program__c, RTV_Program__r.Name , 
                RTV_Program__r.Discount__c,
                RTV_Program__r.TaxRate__c, RTV_Program__r.ExRate__c
            FROM RTV_Summary__c WHERE Id = :summaryId LIMIT 1
        ];
    }
    
    /** 检索shipto白名单(页面初期化时检索) */
    private void queryTargetShipToList() {
        this.shipToWhiteList = new Map<String, RTV_RP_Ship_To__c>();
        this.shipToSelectOptions = new List<SelectOption>();
        
        // 查询user.profile
        Id userId = UserInfo.getUserId();
        Profile userProfile = [
            SELECT Name FROM Profile WHERE Id = :UserInfo.getProfileId() LIMIT 1
        ];
        
        // 检索shipto白名单中的shipto.id
        Set<Id> shipToWLIds = new Set<Id>();
        for (RTV_RP_Ship_To__c sprp: [
            SELECT Ship_To__c, Order_Auth_Code__c,
                Ship_To__r.Name, 
                Ship_To__r.Code_Add__c,
                Ship_To__r.Contact_Pr__c,
                Ship_To__r.Contact_Tel1__c,
                Ship_To__r.Contact_Tel2__c,
                Ship_To__r.Dely_Addr__c,
                Ship_To__r.OwnerId,
                Ship_To__r.Owner.Profile.Name,
                Ship_To__r.Sold_To_Code__r.Name, 
                Ship_To__r.Sold_To_Code__r.Id,
                Ship_To__r.Sold_To_Code__r.OwnerId,
                Ship_To__r.Sold_To_Code__r.Owner.Profile.Name,
                Ship_To__r.Sold_To_Code__r.TT_APP_ACC__c, 
                Ship_To__r.Sold_To_Code__r.TT_FTW_EG__c, 
                Ship_To__r.Sold_To_Code__r.TT_FW_Seasonal__c,
                Ship_To__r.Sold_To_Code__r.Account_Group__r.Name,
                Ship_To__r.Sold_To_Code__r.Account_Group__r.OwnerId,
                Ship_To__r.Sold_To_Code__r.Account_Group__r.Owner.Profile.Name
            FROM RTV_RP_Ship_To__c
            WHERE Removed__c = false AND Summary__c = :summaryId
        ]) {
            this.shipToWhiteList.put(sprp.Ship_To__r.Name, sprp);
        }
                
        // 部分user附加选项：从csv中指定shipto
        if (csvShipToProfiles.contains(userProfile.Name)){
            this.shipToSelectOptions.add(new SelectOption('from_csv', '匹配csv中填写的ship-to'));
        }
        // 遍历shipto白名单检索结果
        for (RTV_RP_Ship_To__c sprp: this.shipToWhiteList.values()) {
            this.shipToSelectOptions.add(new SelectOption(sprp.Ship_To__r.Name, sprp.Ship_To__r.Name));
        }
    }
    
    /** 返回上一页 */
    public PageReference cancel(){
        PageReference returnPage = new PageReference('/' + this.summaryId);
        returnPage.setRedirect(true);
        return returnPage;
    }
    
    /** 上传 */
    public void upload() {
        // 检查文件
        if (this.fileUploadBody == null) {
            RMS_CommonUtil.pageAddMessage(ApexPages.severity.ERROR, '请选择上传文件！');
            return;
        }
        
        // 初期化
        this.isLoading = true;
        this.uploadJob = new AsyncApexJob();
        this.resErrCsvFile = null;
        
        // 创建batch
        RTV_Order_UploadPacking_Batch batch = new RTV_Order_UploadPacking_Batch();
        batch.summary = this.summary;
        batch.selectShipTo = this.shipToSelected;
        batch.shipToWhiteList = this.shipToWhiteList;
        batch.csvFileBody = this.fileUploadBody;
        batch.csvFileCharset = this.fileCharset;
        this.uploadJob.Id = Database.executeBatch(batch, 2000);
    }
    
    /** 获取uploadBatch的执行结构 */
    public void checkUploadResult() {
        // 检索batch的Job对象
        this.uploadJob = [
            SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors, CompletedDate, ExtendedStatus
            FROM AsyncApexJob WHERE Id = :this.uploadJob.Id LIMIT 1
        ];
        // 执行结束时
        if (this.uploadJob.CompletedDate != null) {
            uploadFinish();
        }
    }
    
    /** 执行结束时的操作 */
    public void uploadFinish() {
        this.isLoading = false;
        
        // 检查异常
        if (!String.isBlank(this.uploadJob.ExtendedStatus)) {
            RMS_CommonUtil.pageAddMessage(ApexPages.Severity.ERROR, this.uploadJob.ExtendedStatus);
            return;
        } 
        // 检查自定义错误
        // 获取batch的自定义log
        List<RTV_Log__c> logs = [
            SELECT Errors__c, (SELECT Id FROM Attachments WHERE Name = 'Error.csv' LIMIT 1)
            FROM RTV_Log__c
            WHERE Batch_Job_ID__c = :this.uploadJob.Id LIMIT 1
        ];
        if (logs.size() > 0) {
            RTV_Log__c log = logs[0];
            
            // 错误信息
            if (!String.isBlank(log.Errors__c)) {
                RMS_CommonUtil.pageAddMessage(ApexPages.severity.ERROR, log.Errors__c);
                return;
            }
            // 错误的csv文件
            if (log.Attachments.size() > 0) {
                RMS_CommonUtil.pageAddMessage(ApexPages.severity.INFO, 'Packinglist上传失败！请参考返回的错误信息文件。');
                this.resErrCsvFile = log.Attachments[0];
                return;
            }
        }
        // 上传成功
        RMS_CommonUtil.pageAddMessage(ApexPages.severity.CONFIRM, '上传成功');
    }
    
    /** 静态方法：计算job执行进度 */
    private static Integer getJobPercent(AsyncApexJob job) {
        if (job != null && job.TotalJobItems > 0) {
            Decimal jobProcessed = job.JobItemsProcessed == 0? 1.0: Decimal.valueOf(job.JobItemsProcessed);
            return Integer.valueOf(jobProcessed / job.TotalJobItems * 100.0);
        }
        return 0;
    }
}