force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV DEF Summary</relationshipLabel>
    <relationshipName>RTV_DEF_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <description>PS：因为Number字段类型会显示千分符，所以选Text类型</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Access_DEF_Summary.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Access_DEF_Summary {
    @isTest
    public static void test() {
        RMS_Account_Group__c accGrp = new RMS_Account_Group__c();
        accGrp.Name = 'xxx';
        accGrp.OwnerId = UserInfo.getUserId();
        insert accGrp;
        
        RTV_DEF_Summary__c summary = new RTV_DEF_Summary__c();
        summary.Year__c = String.valueOf(Date.today().year());
        summary.Month__c = Date.today().month();
        summary.Account_Group__c = accGrp.Id;
        insert summary;
    }
}