force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV DEF Summary</relationshipLabel>
    <relationshipName>RTV_DEF_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/TakeBack_From_Date__c.field-meta.xml
<CustomField>
    <fullName>TakeBack_From_Date__c</fullName>
    <description>召回过程中获取D品的日期范围</description>
    <inlineHelpText>Date range for get level(D) in the takeback process</inlineHelpText>
    <label>TakeBack From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/TakeBack_Till_Date__c.field-meta.xml
<CustomField>
    <fullName>TakeBack_Till_Date__c</fullName>
    <description>召回过程中获取D品的日期范围</description>
    <inlineHelpText>Date range for get level(D) in the takeback process</inlineHelpText>
    <label>TakeBack Till Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <description>PS：因为Number字段类型会显示千分符，所以选Text类型</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_Trigger_RTV_ContentDocument.cls
@IsTest(isParallel=true)
public with sharing class Test_Trigger_RTV_ContentDocument {
    @IsTest
    public static void test() {
        // account group
        RMS_Account_Group__c acg = new RMS_Account_Group__c();
        acg.Name = 'xxx';
        insert acg;

        // def summary
        RTV_DEF_Summary__c defSummary = new RTV_DEF_Summary__c();
        defSummary.Account_Group__c = acg.Id;
        defSummary.Year__c = String.valueOf(System.today().year());
        defSummary.Month__c = System.today().month();
        defSummary.TakeBack_From_Date__c = System.today().addDays(-10);
        defSummary.Takeback_Till_Date__c = System.today().addDays(10);
        insert defSummary;

        ContentVersion v = new ContentVersion();
        v.versionData = Blob.valueof('Summary Attachment...');
        v.title = 'fileName';
        v.pathOnClient = 'fileName';
        insert v;
        ContentVersion cv = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:v.Id LIMIT 1];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.LinkedEntityId = defSummary.Id;
        cdl.ContentDocumentId= cv.ContentDocumentId;
        cdl.ShareType= 'I';
        insert cdl;

        ContentDocument cd = [SELECT Id, Title FROM ContentDocument WHERE Id= :cv.ContentDocumentId LIMIT 1];
        try {delete cd;} catch(Exception e){}
    }
}