force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/RMS_Product__c.object-meta.xml
<CustomObject>
    <description>Base data - Product</description>
    <label>RMS Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/fields/BUCN__c.field-meta.xml
<CustomField>
    <fullName>BUCN__c</fullName>
    <description>bu_all_cn_rl</description>
    <label>BUCN</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACC</fullName>
            </value>
            <value>
                <fullName>APP</fullName>
            </value>
            <value>
                <fullName>FTW-Core</fullName>
            </value>
            <value>
                <fullName>FTW-Seasonal</fullName>
            </value>
            <value>
                <fullName>NULL</fullName>
            </value>
            <value>
                <fullName>SS TEE</fullName>
            </value>
            <value>
                <fullName>WOVEN BOTTOM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <description>material_code_all_cn_rl</description>
    <label>Material Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>Manufacturer Suggested Retail Price
msrp_all_cn_rl</description>
    <inlineHelpText>Manufacturer Suggested Retail Price</inlineHelpText>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code CN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <description>Trading Term(APP/ ACC)</description>
    <inlineHelpText>Trading Term(APP/ ACC)</inlineHelpText>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FTW_EG__c.field-meta.xml
<CustomField>
    <fullName>TT_FTW_EG__c</fullName>
    <description>Trading Term(FW-AS CORE)</description>
    <inlineHelpText>Trading Term(FW-AS CORE)</inlineHelpText>
    <label>TT(FW-AS CORE)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FW_Seasonal__c.field-meta.xml
<CustomField>
    <fullName>TT_FW_Seasonal__c</fullName>
    <description>Trading Term(Trading Term)</description>
    <inlineHelpText>Trading Term(Trading Term)</inlineHelpText>
    <label>TT(FW-Seasonal)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/RTV_RP_Summary_Budget__c.object-meta.xml
<CustomObject>
    <description>Return program&apos;s budget for one wholesale</description>
    <label>RTV RP Summary Budget</label>
    <nameField>
        <displayFormat>RPS-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Summary Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Account Group</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>Budget MSRP (CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>Budget QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Return_Program__c.field-meta.xml
<CustomField>
    <fullName>Return_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Belongs to Return Program</description>
    <label>Return Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Tack_Back_Net__c.field-meta.xml
<CustomField>
    <fullName>Tack_Back_Net__c</fullName>
    <label>Budget Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_RTV_UploadRPWhiteListCtrlForSummary.cls
@IsTest(isParallel=true)
public class Test_RTV_UploadRPWhiteListCtrlForSummary {
    @IsTest
    static void test() {
        // RMS_Product__c product = new RMS_Product__c();
        // product.Material_Code__c = '10018342-A03';
        // product.Season_Code_CN__c = '20Q1';
        // product.BUCN__c = 'APP';
        // product.MSRP__c = 123.45;
        // insert product;
        
        RMS_Account_Group__c acgroup = new RMS_Account_Group__c();
        insert acgroup;
        
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Account_Group__c = acgroup.Id;
        soldto.TT_FTW_EG__c = 0.7;
        soldto.TT_FW_Seasonal__c = 0.8;
        soldto.TT_APP_ACC__c = 0.9;
        insert soldto;
        
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = '100001';
        shipto.Sold_To_Code__c = soldto.Id;
        insert shipto;
        
        RMS_Ship_To__c shipto2 = new RMS_Ship_To__c();
        shipto2.Name = '100002';
        shipto2.Sold_To_Code__c = soldto.Id;
        insert shipto2;
        
        RTV_Program__c program = new RTV_Program__c();
        insert program;
        
        RTV_RP_Summary_Budget__c summaryBg = new RTV_RP_Summary_Budget__c();
        summaryBg.Return_Program__c = program.Id;
        summaryBg.Account_Group__c = acgroup.Id;
        summaryBg.Tack_Back_Net__c = 100;
        summaryBg.MSRP__c = 100;
        summaryBg.QTY__c = 100;
        insert summaryBg;
        
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.RTV_Program__c = program.Id;
        summary.Account_Group__c = acgroup.Id;
        insert summary;
        
        ApexPages.currentPage().getParameters().put('summaryId', summary.Id);
        RTV_UploadRPWhiteListCtrlForSummary ctrl = new RTV_UploadRPWhiteListCtrlForSummary();
        ctrl.cancel();
        
        // 空文件
        ctrl.uploadFile();
        
        // 上传
        ctrl.fileUploadBody = Blob.valueof(
            'Ship To\r' + 
            shipto.Name + '\r' + 
            shipto2.Name + '\r'
        );
        ctrl.fileUploadName = 'xxxx';
        ctrl.getFileCharset();
        ctrl.setFileCharset('UTF-8');
        ctrl.uploadFile();
        
        // 上传更新
        ctrl.fileUploadBody = Blob.valueof(
            'Ship To\r' + 
            shipto2.Name + '\r'
        );
        ctrl.uploadFile();
        
        // 上传错误
        ctrl.fileUploadBody = Blob.valueof(
            'Ship To\r' + 
            'error\r'
        );
        ctrl.uploadFile();
    }
}