force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <description>Trading Term(APP/ ACC)</description>
    <inlineHelpText>Trading Term(APP/ ACC)</inlineHelpText>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FTW_EG__c.field-meta.xml
<CustomField>
    <fullName>TT_FTW_EG__c</fullName>
    <description>Trading Term(FW-AS CORE)</description>
    <inlineHelpText>Trading Term(FW-AS CORE)</inlineHelpText>
    <label>TT(FW-AS CORE)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FW_Seasonal__c.field-meta.xml
<CustomField>
    <fullName>TT_FW_Seasonal__c</fullName>
    <description>Trading Term(Trading Term)</description>
    <inlineHelpText>Trading Term(Trading Term)</inlineHelpText>
    <label>TT(FW-Seasonal)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Ship_To__c/RTV_RP_Ship_To__c.object-meta.xml
<CustomObject>
    <description>允许回收的Sold-to&amp;Ship-to白名单</description>
    <label>RTV RP Ship To</label>
    <nameField>
        <displayFormat>WL-{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Ship To White List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <formula>Summary_Budget__r.Account_Group__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Removed__c.field-meta.xml
<CustomField>
    <fullName>Removed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>删除标记</description>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RMS_Ship_To__c.Sold_To_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sold_To__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipLabel>RTV RP Ship To List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipName>Return_Account_White_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup RTV Summary</description>
    <label>Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Summary_Budget__c.field-meta.xml
<CustomField>
    <fullName>Summary_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Summary Budget</description>
    <label>Summary Budget</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RTV_RP_Summary_Budget__c.Return_Program__c</field>
            <operation>equals</operation>
            <valueField>$Source.RTV_Program__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RTV_RP_Summary_Budget__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Summary_Budget__c.field-meta.xml
<CustomField>
    <fullName>Summary_Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup summary budget</description>
    <label>Summary Budget</label>
    <referenceTo>RTV_RP_Summary_Budget__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>RTV_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/recordTypes/Remove.recordType-meta.xml
<RecordType>
    <fullName>Remove</fullName>
    <active>true</active>
    <description>Removed</description>
    <label>Remove</label>
</RecordType>

force-app/main/default/classes/RTV_UploadRPWhiteListCtrlForSummary.cls
public with sharing class RTV_UploadRPWhiteListCtrlForSummary {
    
    /** 画面参数：sumamryId */
    String summaryId = ApexPages.currentPage().getParameters().get('summaryId');

    private RTV_Summary__c summary;
    
    /** 上传的csv */
    public transient Blob fileUploadBody{get;set;}
    public String fileUploadName{get;set;}
    
    /** 文件编码 */
    public List<ApexPages.SelectOption> fileCharsetOpts {get{return RMS_CSV_Iterator.CHARSET_OPTIONS;}}
    public String fileCharset = fileCharsetOpts.get(0).getValue();
    public String getFileCharset() {return fileCharset;}
    public void setFileCharset(String value) {this.fileCharset=value;}
    
    /** csv必须列 */
    public static final String[] CsvFields = new String[]{'Ship To'};
    
    /** 结果：有效化的shipto */
    public List<RTV_RP_Ship_To__c> shiptoWL {get; set;}
    
    public List<RTV_RP_Ship_To__c> resNewShipToWL {get; set;}
    public List<RTV_RP_Ship_To__c> resUpdShipToWL {get; set;}
    
    /** 返回上一页 */
    public PageReference cancel(){
        PageReference returnPage = new PageReference('/' + summaryId);
        returnPage.setRedirect(true);
        return returnPage;
    }
    
    /** 执行上传 */
    public void uploadFile() {
        this.resNewShipToWL = new List<RTV_RP_Ship_To__c>();
        this.resUpdShipToWL = new List<RTV_RP_Ship_To__c>();
        try {
            // 判断input
            if (fileUploadBody == null) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'file is required'));
                return;
            }
            
            // 检索summary
            this.summary = [
                SELECT Id, Summary_Budget__c, Account_Group__c, RTV_Program__c, RTV_Program__r.OwnerId
                FROM RTV_Summary__c WHERE Id = :summaryId LIMIT 1
            ];
            
            // 统计csv中各shipToCode
            Set<String> csvShipToCodes = this.getCsvShipToCodes();
            
            // 检索csv中各shipToCode对应的，该AccountGroup下的shipto对象
            Map<String, RMS_Ship_To__c> csvShipToMap = this.queryShipTos(csvShipToCodes);
            
            // 如果csv中有不在当前Account_Group的shipToCode时
            Set<String> otherCodes = new Set<String>(csvShipToCodes);
            otherCodes.removeAll(csvShipToMap.KeySet());
            if (!otherCodes.isEmpty()) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Sorry, please do not upload the Ship-to of other Account Group: ' + otherCodes.toString()));
                return;
            }
            
            // 检索该summary的白名单
            Map<String, RTV_RP_Ship_To__c> shipToWhiteMap = this.queryShipToWhiteList();
            
            // 获取所有待处理的shipToCode
            Set<String> allCodes = new Set<String>();
            allCodes.addAll(csvShipToMap.KeySet());
            allCodes.addAll(shipToWhiteMap.KeySet());
            
            for (String shipToCode: allCodes) {
                RMS_Ship_To__c csvShipTo = csvShipToMap.get(shipToCode.toUpperCase());
                RTV_RP_Ship_To__c existShipToWL = shipToWhiteMap.get(shipToCode.toUpperCase());
                
                // 当shiptocode在csv中，不在白名单中，且可以新建(完全没有白名单)时
                if (csvShipTo != null && existShipToWL == null && shipToWhiteMap.isEmpty()) {
                    // 新增shipto白名单
                    RTV_RP_Ship_To__c sprp = new RTV_RP_Ship_To__c();
                    sprp.Removed__c = false;
                    
                    // 基础信息
                    sprp.RTV_Program__c = summary.RTV_Program__c;
                    sprp.Summary_Budget__c = summary.Summary_Budget__c;
                    sprp.Summary__c = summary.Id;
                    sprp.Sold_To__c = csvShipTo.Sold_To_Code__c;
                    sprp.Ship_To__c = csvShipTo.Id;
                    
                    //Owner(和order的owner逻辑一致)
                    sprp.OwnerId = csvShipTo.OwnerId;
                    
                    this.resNewShipToWL.add(sprp);
                }
                // 当shipto在csv中，在白名单中时
                else if (csvShipTo != null && existShipToWL != null) {
                    // 修改shipto白名单(unremove)
                    existShipToWL.Removed__c = false;
                    existShipToWL.OwnerId = csvShipTo.OwnerId;
                    this.resUpdShipToWL.add(existShipToWL);
                }
                // 当shipto不在csv中，在白名单中时
                else if (csvShipTo == null && existShipToWL != null) {
                    // 修改shipto白名单(remove)
                    existShipToWL.Removed__c = true;
                    existShipToWL.OwnerId = summary.RTV_Program__r.OwnerId;
                    this.resUpdShipToWL.add(existShipToWL);
                }
            }
            
            // 执行新建和更新
            if (!this.resNewShipToWL.isEmpty()) {
                insert this.resNewShipToWL;
            }
            if (!this.resUpdShipToWL.isEmpty()) {
                update this.resUpdShipToWL;
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Upload Success'));
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
        }
        
    }
    
    /** 获取csv中的shipToCode集合 */ 
    private Set<String> getCsvShipToCodes() {
        Set<String> csvShipToCodes = new Set<String>();
        
        RMS_CSV_Iterator csvIter = new RMS_CSV_Iterator(this.fileUploadBody, this.fileCharset);
        csvIter.skipTitleLine(CsvFields);
        
        while (csvIter.next()) {
            String shipToCode = csvIter.getLineAsList()[0];
            csvShipToCodes.add(shipToCode.toUpperCase());   
        }
        return csvShipToCodes;
    }
        
    /** 检索shipToCode对应的shipto对象(当前Account_Group内) */
    private Map<String, RMS_Ship_To__c> queryShipTos(Set<String> shipToCodes) {
        Map<String, RMS_Ship_To__c> csvShipToMap = new Map<String, RMS_Ship_To__c>();
        
        for (RMS_Ship_To__c shipTo: [
            SELECT Name,
                OwnerId,
                Owner.Profile.Name, 
                Sold_To_Code__c, 
                Sold_To_Code__r.TT_FTW_EG__c,
                Sold_To_Code__r.TT_FW_Seasonal__c,
                Sold_To_Code__r.TT_APP_ACC__c,
                Sold_To_Code__r.OwnerId, 
                Sold_To_Code__r.Owner.Profile.Name, 
                Sold_To_Code__r.Account_Group__r.Name,
                Sold_To_Code__r.Account_Group__r.OwnerId,
                Sold_To_Code__r.Account_Group__r.Owner.Profile.Name
            FROM RMS_Ship_To__c 
            WHERE Sold_To_Code__r.Account_Group__c = :this.summary.Account_Group__c
            AND Name IN :shipToCodes
        ]) {
            csvShipToMap.put(shipTo.Name.toUpperCase(), shipTo);
        }
        return csvShipToMap;
    }
    
    /** 检索shipto白名单 */
    private Map<String, RTV_RP_Ship_To__c> queryShipToWhiteList() {
        Map<String, RTV_RP_Ship_To__c> shipToWhiteMap = new Map<String, RTV_RP_Ship_To__c>();
        
        for (RTV_RP_Ship_To__c sprp: [
            SELECT Id, Sold_To__c, Ship_To__r.Name, Removed__c
            FROM RTV_RP_Ship_To__c 
            WHERE Summary__c = :this.summaryId
        ]) {
            shipToWhiteMap.put(sprp.Ship_To__r.Name.toUpperCase(), sprp);
        }
        return shipToWhiteMap;
    }
}