force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/RTV_RP_Summary_Budget__c.object-meta.xml
<CustomObject>
    <description>Return program&apos;s budget for one wholesale</description>
    <label>RTV RP Summary Budget</label>
    <nameField>
        <displayFormat>RPS-{000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Summary Budgets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup Account Group</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <label>Budget MSRP (CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/QTY__c.field-meta.xml
<CustomField>
    <fullName>QTY__c</fullName>
    <label>Budget QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Return_Program__c.field-meta.xml
<CustomField>
    <fullName>Return_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Belongs to Return Program</description>
    <label>Return Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP Summary Budgets</relationshipLabel>
    <relationshipName>RTV_RP_Summary_Budgets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Summary_Budget__c/fields/Tack_Back_Net__c.field-meta.xml
<CustomField>
    <fullName>Tack_Back_Net__c</fullName>
    <label>Budget Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_RTV_OffPolicy_Export.cls
@IsTest(isParallel=true)
public with sharing class Test_RTV_OffPolicy_Export {
    @isTest
    public static void test() {
        RTV_Program__c program = new RTV_Program__c();
        insert program;
        
        RMS_Account_Group__c acg = new RMS_Account_Group__c();
        insert acg;
        
        ApexPages.currentPage().getParameters().put('id', program.Id);
        RTV_OffPolicy_Export ctrl = new RTV_OffPolicy_Export();
        ctrl.budget1 = null;
        ctrl.budget2 = null;
        ctrl.budget3 = null;
        ctrl.budget4 = null;
        ctrl.budget5 = null;
        ctrl.budget6 = null;
        ctrl.budget7 = null;
        ctrl.budget8 = null;
        ctrl.budget9 = null;
        ctrl.budget10 = null;
        ctrl.budget11 = null;
        ctrl.budget12 = null;
        ctrl.budget13 = null;
        ctrl.budget14 = null;
        ctrl.budget15 = null;
        ctrl.test();
        ctrl.getItems();
        
        for (Integer i=1; i<=13; i++) {
            RTV_RP_Summary_Budget__c sumBgt = new RTV_RP_Summary_Budget__c();
            sumBgt.Return_Program__c = program.Id;
            sumBgt.Account_Group__c = acg.Id;
            sumBgt.QTY__c = 10;
            sumBgt.MSRP__c = 100;
            sumBgt.Tack_Back_Net__c = 100;
            insert sumBgt;
            
            new RTV_OffPolicy_Export();
        }
    }
}