force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code A)</description>
    <inlineHelpText>Inspection qty (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code B)</description>
    <inlineHelpText>Inspection qty (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code C)</description>
    <inlineHelpText>Inspection qty (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code D)</description>
    <inlineHelpText>Inspection qty (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code (CN)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Selling_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Unit_Price__c</fullName>
    <defaultValue>(0)</defaultValue>
    <label>Selling Unit Price (CNY/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Color__c.field-meta.xml
<CustomField>
    <fullName>SKU_Color__c</fullName>
    <label>SKU Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Style__c.field-meta.xml
<CustomField>
    <fullName>SKU_Style__c</fullName>
    <label>SKU Style</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/Finance_Code__c.field-meta.xml
<CustomField>
    <fullName>Finance_Code__c</fullName>
    <description>Code(Code(Finance Only))</description>
    <label>Finance Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <description>Total Inspection QTY (Reason Code A)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <description>Total Inspection QTY (Reason Code B)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <description>Total Inspection QTY (Reason Code C)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <description>Total Inspection QTY (Reason Code D)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RTV_Sch_SKU_KPI.cls
@IsTest
public with sharing class Test_RTV_Sch_SKU_KPI {
    @isTest
    public static void test() {

        Test.StartTest();
    
        // account group
        RMS_Account_Group__c acg = new RMS_Account_Group__c();
        acg.Name = 'ag';
        insert acg;

        // summary
        RTV_Program__c program = new RTV_Program__c();
        program.Finance_Code__c = 'Finance Code';
        insert program;

        // summary
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.Account_Group__c = acg.Id;
        summary.RTV_Program__c = program.Id;
        summary.Name = 'summary';
        insert summary;

        // order
        RTV_Order__c order = new RTV_Order__c();
        order.Return_Summary__c = summary.Id;
        order.Name = RMS_CommonUtil.order_getCode('xxx', 'xxxx', 'xx');
        order.Status__c = 'Insp Confirmed';
        order.Inspect_QTY_D__c = 1;
        insert order;

        // item
        RTV_Order_Item__c item = new RTV_Order_Item__c();
        item.RTV_Order__c = order.Id;
        item.Material_Code__c = 'PDT000001';
        item.BU_2__c = 'AP';
        item.SKU_Style__c = 'style';
        item.SKU_Color__c = '001';
        item.Season_Code_CN__c = '20Q1';
        item.SKU_Size_US__c = 'XL';
        item.Selling_Unit_Price__c = 123.45;
        item.Inspect_QTY_A__c = 1;
        item.Inspect_QTY_B__c = 1;
        item.Inspect_QTY_C__c = 1;
        item.Inspect_QTY_D__c = 2;
        insert item;

        RTV_Sch_SKU_KPI p = new RTV_Sch_SKU_KPI();
        String sch = '0 30 15 26 4 ?';
        system.schedule('Test schexample', sch, p);
        Test.stopTest();

        RTV_Bth_SKU_KPI.lieToTest();
    }
}