force-app/main/default/objects/RMS_Account_Group__c/RMS_Account_Group__c.object-meta.xml
<CustomObject>
    <description>Account Group, such as YY or Belle</description>
    <label>RMS Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Account Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/RMS_Product__c.object-meta.xml
<CustomObject>
    <description>Base data - Product</description>
    <label>RMS Product</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Product__c/fields/CFS_Rebuy__c.field-meta.xml
<CustomField>
    <fullName>CFS_Rebuy__c</fullName>
    <description>rebuy_cfs_all_cn_rl</description>
    <label>CFS Rebuy</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rebuy</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RMS_Product__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <description>material_code_all_cn_rl</description>
    <label>Material Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/Finance_Code__c.field-meta.xml
<CustomField>
    <fullName>Finance_Code__c</fullName>
    <description>Code(Code(Finance Only))</description>
    <label>Finance Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_RTV_RP_UploadSKUBudget.cls
@IsTest(isParallel=true)
public with sharing class Test_RTV_RP_UploadSKUBudget {
    @isTest
    public static void test() {
        RMS_Product__c product = new RMS_Product__c();
        product.Material_Code__c = '00168C035';
        insert product;
        
        RMS_Product__c product2 = new RMS_Product__c();
        product2.Material_Code__c = '00168C035_rebuy';
        product2.CFS_Rebuy__c = 'Rebuy';
        insert product2;
        
        RMS_Account_Group__c acgroup = new RMS_Account_Group__c();
        acgroup.Name = 'xx)xx';
        insert acgroup;
        
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Name = 'xxxxxxx';
        soldto.Account_Group__c = acgroup.Id;
        insert soldto;
        
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = 'xxxxxxxxxxx';
        shipto.Sold_To_Code__c = soldto.Id;
        insert shipto;
        
        //创建program
        RTV_Program__c program = new RTV_Program__c();
        program.Finance_Code__c = 'xxx';
        insert program;
        
        //Controller
        ApexPages.currentPage().getParameters().put('id', program.Id);
        ApexPages.currentPage().getParameters().put('isGold', 'true');
        RTV_RP_UploadSKUBudgetController ctrl = new RTV_RP_UploadSKUBudgetController();
        ctrl.cancel();
        ctrl.checkResult();
        
        Test.StartTest();
        try {
            // 上传:空文件
            try { ctrl.uploadFile(); } catch (Exception err) {}
            
            // 上传:soldto级别
            ctrl.fileUploadBody = Blob.valueof(
                'SKU,Account Group,Sold To,Ship To,QTY,MSRP,$NET,order season\r'+
                '00168C035,,,,0,0,0,21Q2\r'+ 
                '00168C035_rebuy,,,,0,0,0,21Q2\r'+ 
                'error,,,,0,0,0,21Q2\r'
            );
            ctrl.fileUploadName = 'xxxx';
            ctrl.setFileCharset('UTF-8');
            ctrl.getFileCharset();
            try { ctrl.uploadFile(); } catch (Exception err) {}
            ctrl.checkResult();
            ctrl.getIsLoading();
            System.debug(ctrl.batchPercent);
            
            // accountGroup级别
            ctrl.fileUploadBody = Blob.valueof(
                'SKU,Account Group,Sold To,Ship To,QTY,MSRP,$NET,order season\r'+
                '00168C035,' + acgroup.Name + ',,,0,0,0,21Q2\r'
            );
            ctrl.uploadFile();
            
            // soldto级别
            ctrl.fileUploadBody = Blob.valueof(
                'SKU,Account Group,Sold To,Ship To,QTY,MSRP,$NET,order season\r'+
                '00168C035,,' + soldto.Name + ',,0,0,0,21Q2\r'
            );
            ctrl.uploadFile();
            
            // shipto级别
            ctrl.fileUploadBody = Blob.valueof(
                'SKU,Account Group,Sold To,Ship To,QTY,MSRP,$NET,order season\r'+
                '00168C035,,,' + shipto.Name + ',0,0,0,21Q2\r'
            );
            ctrl.uploadFile();
        } finally {
            Test.StopTest();
            ctrl.checkResult();
        }
    }
}