force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The quantity of customer application</description>
    <inlineHelpText>The quantity of customer application</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Defective_Reason__c.field-meta.xml
<CustomField>
    <fullName>Defective_Reason__c</fullName>
    <label>Defective Reason</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Defective_Source__c.field-meta.xml
<CustomField>
    <fullName>Defective_Source__c</fullName>
    <label>Defective Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>原残</fullName>
            </value>
            <value>
                <fullName>客残</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Original</fullName>
                <isActive>false</isActive>
                <label>Original</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Factory_Code__c.field-meta.xml
<CustomField>
    <fullName>Factory_Code__c</fullName>
    <label>Factory Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/LF_Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>LF_Order_Auth_Code__c</fullName>
    <description>LF Order Auth Code</description>
    <formula>RTV_Order__r.Name + BU_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LF Order Auth Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code (CN)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Color__c.field-meta.xml
<CustomField>
    <fullName>SKU_Color__c</fullName>
    <label>SKU Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_Asia__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_Asia__c</fullName>
    <description>亚码</description>
    <label>SKU Size (Asia)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Style__c.field-meta.xml
<CustomField>
    <fullName>SKU_Style__c</fullName>
    <label>SKU Style</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/RTV_Order_Item_DEF_Detail__c.object-meta.xml
<CustomObject>
    <label>RTV Order Item DEF Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Item DEF Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Acceptable_Return_QTY__c.field-meta.xml
<CustomField>
    <fullName>Acceptable_Return_QTY__c</fullName>
    <label>Acceptable Return QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Actual_QTY__c.field-meta.xml
<CustomField>
    <fullName>Actual_QTY__c</fullName>
    <label>Actual QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <label>BU-2</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Customer_Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Customer_Abbreviation__c</fullName>
    <label>Customer Abbreviation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/DEF_12M_18M__c.field-meta.xml
<CustomField>
    <fullName>DEF_12M_18M__c</fullName>
    <label>&gt;12M&lt;18M</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Defective_Reason__c.field-meta.xml
<CustomField>
    <fullName>Defective_Reason__c</fullName>
    <label>Defective Reason</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Defective_Reason_LF__c.field-meta.xml
<CustomField>
    <fullName>Defective_Reason_LF__c</fullName>
    <label>Defective Reason(LF)</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Defective_Source__c.field-meta.xml
<CustomField>
    <fullName>Defective_Source__c</fullName>
    <label>Defective Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>原残</fullName>
            </value>
            <value>
                <fullName>客残</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Original</fullName>
                <isActive>false</isActive>
                <label>Original</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Defective_Source_LF__c.field-meta.xml
<CustomField>
    <fullName>Defective_Source_LF__c</fullName>
    <label>Defective Source(LF)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>原残</fullName>
            </value>
            <value>
                <fullName>客残</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
                <isActive>false</isActive>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Original</fullName>
                <isActive>false</isActive>
                <label>Original</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Detail_Number__c.field-meta.xml
<CustomField>
    <fullName>Detail_Number__c</fullName>
    <label>Detail Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Factory_Code__c.field-meta.xml
<CustomField>
    <fullName>Factory_Code__c</fullName>
    <label>Factory Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Reject_QTY__c.field-meta.xml
<CustomField>
    <fullName>Reject_QTY__c</fullName>
    <label>Reject QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Item DEF Detail</relationshipLabel>
    <relationshipName>RTV_Order_Item_DEF_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/RTV_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order_Item__c</fullName>
    <label>RTV Order Item</label>
    <referenceTo>RTV_Order_Item__c</referenceTo>
    <relationshipLabel>Defective Details</relationshipLabel>
    <relationshipName>RTV_Order_Item_DEF_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code CN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipLabel>RTV Order Item DEF Detail</relationshipLabel>
    <relationshipName>RTV_Order_Item_DEF_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RTV Order Item DEF Detail</relationshipLabel>
    <relationshipName>RTV_Order_Item_DEF_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Specialcase_DEF_CC__c.field-meta.xml
<CustomField>
    <fullName>Specialcase_DEF_CC__c</fullName>
    <label>Specialcase DEF CC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RTV_Defective_Report_Inspect.cls
public with sharing class RTV_Defective_Report_Inspect {
    String orderId = ApexPages.currentPage().getParameters().get('orderId');

    //显示结果
    public List<RTV_Order_Item_DEF_Detail__c> results {get; set;}

    public static String empty {get{return '';}}

    public RTV_Defective_Report_Inspect() {
        results = [
            SELECT BU_2__c, 
                Customer_Abbreviation__c, 
                RTV_Order_Item__r.RTV_Order__r.Sold_To__r.Name,
                RTV_Order_Item__r.RTV_Order__r.Ship_To__r.Name, 
                Customer_Name__c,
                RTV_Order_Item__r.RTV_Order__r.Name,
                RTV_Order_Item__r.LF_Order_Auth_Code__c,
                Detail_Number__c,
                RTV_Order_Item__r.Material_Code__c,
                RTV_Order_Item__r.SKU_Style__c,
                RTV_Order_Item__r.SKU_Color__c,
                RTV_Order_Item__r.SKU_Size_US__c,
                RTV_Order_Item__r.SKU_Size_Asia__c,
                RTV_Order_Item__r.Season_Code_CN__c,
                Application_QTY__c,
                Defective_Reason__c,
                Defective_Source__c,
                Defective_Reason_LF__c,
                Defective_Source_LF__c,
                Factory_Code__c,
                Actual_QTY__c,
                Acceptable_Return_QTY__c,
                Specialcase_DEF_CC__c,
                DEF_12M_18M__c,
                Reject_QTY__c,
                Reject_Reason__c,
                RTV_Order_Item__r.Defective_Box_Code__c,
                Code__c,
                RTV_Order_Item__r.Application_Remark__c,
                Actual_Diff_QTY__c,
                RTV_Order_Item__r.Selling_Unit_Price__c,
                RTV_Order_Item__r.Selling_Unit_Price_CNY_inV__c
            FROM  RTV_Order_Item_DEF_Detail__c
            WHERE RTV_Order_Item__r.RTV_Order__c = :orderId
            AND RTV_Order_Item__r.IsMaterial__c = false
            ORDER BY Detail_Number__c
        ];
    }
}