force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The quantity of customer application</description>
    <inlineHelpText>The quantity of customer application</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code (CN)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_Asia__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_Asia__c</fullName>
    <description>亚码</description>
    <label>SKU Size (Asia)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Packing__c/RTV_Order_Packing__c.object-meta.xml
<CustomObject>
    <description>Packing information of RTV Order Item</description>
    <label>RTV Order Packing</label>
    <nameField>
        <displayFormat>PKG{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV Order Packings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Packing__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Packing__c/fields/Box_Code__c.field-meta.xml
<CustomField>
    <fullName>Box_Code__c</fullName>
    <label>Box Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Packing__c/fields/RTV_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order_Item__c</fullName>
    <label>RTV Order Item</label>
    <referenceTo>RTV_Order_Item__c</referenceTo>
    <relationshipLabel>Packing Details</relationshipLabel>
    <relationshipName>RTV_Order_Packings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RTV_Order_ReportPackingListCtrl.cls
public with sharing class RTV_Order_ReportPackingListCtrl {
    
    public Id summaryId = ApexPages.currentPage().getParameters().get('summaryId');
    
    public List<RTV_Order_Packing__c> results {get; set;}
    
    public RTV_Order_ReportPackingListCtrl() {
        this.results = [
            SELECT Box_Code__c,
                Application_QTY__c,
                RTV_Order_Item__r.Material_Code__c,
                RTV_Order_Item__r.BU_2__c,
                RTV_Order_Item__r.SKU_Size_US__c, 
                RTV_Order_Item__r.SKU_Size_Asia__c, 
                RTV_Order_Item__r.Season_Code_CN__c,
                RTV_Order_Item__r.RTV_Order__r.Name,
                RTV_Order_Item__r.RTV_Order__r.Sold_To__r.Name,
                RTV_Order_Item__r.RTV_Order__r.Ship_To__r.Name,
                RTV_Order_Item__r.RTV_Order__r.Earliest_Delivery_Date__c
            FROM RTV_Order_Packing__c 
            WHERE RTV_Order_Item__r.RTV_Order__r.Return_Summary__c = :summaryId
        ];
    }
}