force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>WSL Takeback OR DTC Takeback</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WSL Takeback</fullName>
                <default>true</default>
                <label>WSL Takeback</label>
            </value>
            <value>
                <fullName>RTV Defective</fullName>
            </value>
            <value>
                <fullName>CFS DTC Takeback</fullName>
            </value>
            <value>
                <fullName>Digital DTC Takeback</fullName>
            </value>
            <value>
                <fullName>CFS DTC Defective</fullName>
            </value>
            <value>
                <fullName>Digital DTC Defective</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The quantity of customer application</description>
    <inlineHelpText>The quantity of customer application</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/POS_SKU__c.field-meta.xml
<CustomField>
    <fullName>POS_SKU__c</fullName>
    <description>POS机中读取的SKU全值</description>
    <label>POS SKU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/recordTypes/DTC.recordType-meta.xml
<RecordType>
    <fullName>DTC</fullName>
    <active>true</active>
    <label>DTC</label>
</RecordType>

force-app/main/default/classes/Test_Trigger_DTC_CombineDuplicate.cls
@IsTest
public with sharing class Test_Trigger_DTC_CombineDuplicate {
    @isTest
    public static void test() {
       RTV_Order__c order = new RTV_Order__c();
       order.Name = 'xxx';
       order.Order_Type__c = 'CFS DTC Takeback';
       insert order;
       List<RTV_Order_Item__c> itemList = new List<RTV_Order_Item__c>();
       RTV_Order_Item__c itemA =new RTV_Order_Item__c();
       itemA.RTV_Order__c = order.Id;
       itemA.POS_SKU__c ='10021090661S';
       itemA.Application_QTY__c = 1;

       itemList.add(itemA);

       RTV_Order_Item__c itemB =new RTV_Order_Item__c();
       itemB.RTV_Order__c = order.Id;
       itemB.POS_SKU__c ='10021090661S';
       itemB.Application_QTY__c = 1;

       itemList.add(itemB);

       insert itemList;

    }
}