force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Outbound_Emails__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Outbound_Emails__c</fullName>
    <inlineHelpText>请输入Ship-To外部Email地址（逗号分割的1~5个地址）</inlineHelpText>
    <label>Ship-To Outbound Emails</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RTV_DEF_Approve_Email_Batch.cls
@IsTest(isParallel=true)
public  class Test_RTV_DEF_Approve_Email_Batch {
    @isTest
    public static void test() {
        RTV_Order__c order = new RTV_Order__c();
        order.Ship_To_Outbound_Emails__c = 'xx@xxxx.xxxx';
        order.Name = 'xxx';
        order.Status__c = 'Insp Wait Approval';
        insert order;
        
        RTV_DEF_Approve_Email_Batch batch = new RTV_DEF_Approve_Email_Batch(new Set<Id>{order.Id});
        Test.StartTest();
        Database.executeBatch(batch, 1);
        Test.StopTest();
    }
}