force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/POS_SKU__c.field-meta.xml
<CustomField>
    <fullName>POS_SKU__c</fullName>
    <description>POS机中读取的SKU全值</description>
    <label>POS SKU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/RTV_Order_Item_DEF_Detail__c.object-meta.xml
<CustomObject>
    <label>RTV Order Item DEF Detail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Item DEF Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/Detail_Number__c.field-meta.xml
<CustomField>
    <fullName>Detail_Number__c</fullName>
    <label>Detail Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Item DEF Detail</relationshipLabel>
    <relationshipName>RTV_Order_Item_DEF_Detail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item_DEF_Detail__c/fields/RTV_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order_Item__c</fullName>
    <label>RTV Order Item</label>
    <referenceTo>RTV_Order_Item__c</referenceTo>
    <relationshipLabel>Defective Details</relationshipLabel>
    <relationshipName>RTV_Order_Item_DEF_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_RTV_DTC_DEF_Upload_Reason.cls
@IsTest(isParallel=true)
public class Test_RTV_DTC_DEF_Upload_Reason {
    @isTest
    public static void test() {
        RTV_Order__c order = new RTV_Order__c();
        order.Name = '[order1]';
        insert order;
        
        RTV_Order_Item__c item = new RTV_Order_Item__c();
        item.RTV_Order__c = order.Id;
        item.Name = 'xxx';
        item.POS_SKU__c = '[sku]';
        insert item;
        
        RTV_Order_Item_Def_Detail__c detail = new RTV_Order_Item_Def_Detail__c();
        detail.RTV_Order_Item__c = item.Id;
        detail.Detail_Number__c = 1;
        insert detail;
        
        // -----------------------
        // 测试
        // -----------------------
        ApexPages.currentPage().getParameters().put('orderId', order.Id);
        RTV_DTC_DEF_Upload_Reason ctrl = new RTV_DTC_DEF_Upload_Reason();
        ctrl.fileUploadName = 'xx';
        ctrl.setFileCharset('UTF-8');
        ctrl.getFileCharset();
        ctrl.cancel();
        ctrl.upload();
        
        ctrl.fileUploadBody = Blob.valueOf(
            '授权码,序号,POS SKU,货品号,尺寸(美码),退货理由(必填),原残/客残,备注\r' +
            '[#Err##],1,[sku],xx,xx,理由,原残,\r'+ 
            '[order1],1,[sku],xx,xx,,原残,\r' + 
            '[order1],1,[sku],xx,xx,鞋盒,原残,\r' +
            '[order1],1,[sku],xx,xx,鞋盒,原残,特批\r'
        );
        ctrl.upload();
        
        ctrl.fileUploadBody = Blob.valueOf(
            '授权码,序号,POS SKU,货品号,尺寸(美码),退货理由(必填),原残/客残,备注\r' +
            '[order1],1,[sku],xx,xx,理由,原残,\r'
        );
        ctrl.upload();
        
        // -----------------------
        // 上传特批附件
        // -----------------------
        ctrl.specialDef.inputFileBody = Blob.valueOf('xx');
        ctrl.specialDef.inputFileName = 'xx.txt';
        try { ctrl.specialDef.uploadFile(); }catch(Exception err){}
        try { ctrl.specialDef.deleteFile(); }catch(Exception err){}
    }
}