force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Auth_Code__c</fullName>
    <externalId>true</externalId>
    <label>Order Auth Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/LF_Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>LF_Order_Auth_Code__c</fullName>
    <description>LF Order Auth Code</description>
    <formula>RTV_Order__r.Name + BU_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LF Order Auth Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code (CN)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Selling_Type__c.field-meta.xml
<CustomField>
    <fullName>Selling_Type__c</fullName>
    <label>Selling Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Selling_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Unit_Price__c</fullName>
    <defaultValue>(0)</defaultValue>
    <label>Selling Unit Price (CNY/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Unique Key  = order.name + item.Material_Code__c + item.BU_2__c + item.SKU_Size_US__c + item.Season_Code_CN__c</description>
    <externalId>true</externalId>
    <inlineHelpText>Unique Key  = order.name + item.Material_Code__c + item.BU_2__c + item.SKU_Size_US__c + item.Season_Code_CN__c</inlineHelpText>
    <label>Unique Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/RTV_Order_UploadSellingPriceCtrl.cls
public with sharing class RTV_Order_UploadSellingPriceCtrl {

    /** 参数summary */
    public final Id theSummaryId = ApexPages.currentPage().getParameters().get('summaryId');
    
    /** 上传的csv文件正文 */
    public transient Blob fileUploadBody {get; set;}
    public String fileUploadName {get; set;}
    
    /** 文件编码 */
    public List<ApexPages.SelectOption> fileCharsetOpts {get{return RMS_CSV_Iterator.CHARSET_OPTIONS;}}
    public String fileCharset = fileCharsetOpts.get(0).getValue();
    public String getFileCharset() {return fileCharset;}
    public void setFileCharset(String value) {this.fileCharset=value;}

    /** 目标item */
    private Map<String, RTV_Order_Item__c> existItems;
    /** 待更新记录 */
    private Map<String, RTV_Order_Item__c> updateItems;

    /** 上传是否有错误 */
    private Boolean isError = false;

    /** csv的必须列 */
    private static String[] Csv_Fields = new String[]{
        'LF Order Auth Code', 'BU', 'Material Code', 'Size (US)', 'Season Code (CN)', 'Selling Type', 'Selling Unit Price (CNY/excl.VAT)'};

    public RTV_Order_UploadSellingPriceCtrl() {
        // Nothing
    }

    /** 返回上一页 */
    public PageReference cancel() {
        String url = '/lightning/o/RTV_Summary__c/list';
        if (this.theSummaryId != null) {
            url = String.format('/lightning/r/RTV_Summary__c/{0}/view', new List<string>{this.theSummaryId});
        }
        return new PageReference(url);
    }
    
    /** 上传 */
    public void upload() {
        this.existItems = new Map<String, RTV_Order_Item__c>();
        this.updateItems = new Map<String, RTV_Order_Item__c>();
        this.isError = false;

        // 检查input
        if (this.fileUploadBody == null) {
            RMS_CommonUtil.pageAddMessage(ApexPages.severity.ERROR, 'file is required');
            return;
        }
        
        // 执行上传
        Savepoint savePot = Database.setSavepoint();
        try {
            this.doUpload();
        } 
        // 捕捉dml错误 (包括自定义的validate rule)
        catch(Exception err) {
            if (err.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION')) {
                // 自定义的validate rule会自动添加message
            } else {
                RMS_CommonUtil.pageAddMessage(ApexPages.severity.ERROR, err.getMessage());
            }
            Database.rollback(savePot);
        }
        
    }

    /** 执行上传 */
    private void doUpload() {
        System.debug('doUpload');

        // 创建csv迭代器
        RMS_CSV_Iterator csvIter = new RMS_CSV_Iterator(this.fileUploadBody, this.fileCharset);
        csvIter.skipTitleLineIgnoreCase(Csv_Fields);
        
        // 检索order前，先遍历一次csv缩小检索范围
        List<RMS_CSV_Iterator.OneLineInfo> csvTable = new List<RMS_CSV_Iterator.OneLineInfo>();
        Set<String> lfOrderCodes = new Set<String>();
        while (csvIter.next()) {
            RMS_CSV_Iterator.OneLineInfo tr = csvIter.getOneLineInfo();
            
            // 记录该行内容
            csvTable.add(tr);
            lfOrderCodes.add(tr.get('LF Order Auth Code'));
        }
        System.debug('lfOrderCodes' + lfOrderCodes.size());
        
        // 检索item
        this.queryItems(lfOrderCodes);

        // 遍历csv
        for (RMS_CSV_Iterator.OneLineInfo tr: csvTable) {
            System.debug('tr.LF Order Auth Code' + tr.get('LF Order Auth Code'));

            // 通过'LF Order Auth Code'获取'OrderCode'和'BU2'
            String lfOrderCode = tr.get('LF Order Auth Code');
            String orderCode = lfOrderCode.substring(0, lfOrderCode.length()-2);
            
            // 更新item
            changeItem(orderCode, tr);
        }
        
        // 更新Items
        if (!this.updateItems.isEmpty()) {
            upsert this.updateItems.values();
            if(!this.isError){
                RMS_CommonUtil.pageAddMessage(ApexPages.severity.CONFIRM, 'Update selling price success');
            }
        } else {
            RMS_CommonUtil.pageAddMessage(ApexPages.severity.INFO, 'No item found');
        }
    }

    /**
     * 统计item
     */
    private void queryItems(Set<String> csvLfOrderCodes) {
        
        // 检索item，统计各 LF_Order_Auth_Code__c 对应的itemlist
        for (RTV_Order_Item__c item: [
            SELECT Id, Name, LF_Order_Auth_Code__c, UniqueKey__c,
                Material_Code__c, BU_2__c, SKU_Size_US__c, Season_Code_CN__c, 
                RTV_Order__r.Order_Auth_Code__c
            FROM RTV_Order_Item__c
            WHERE LF_Order_Auth_Code__c IN :csvLfOrderCodes
        ]) {
            // 获取现存的item
            this.existItems.put(item.UniqueKey__c, item);
        }
    }

    /** 修改 RTV_Order_Item__c */
    private void changeItem(String orderCode, RMS_CSV_Iterator.OneLineInfo tr) {
        // 获取csv中的目标item
        RTV_Order_Item__c csvInfo = new RTV_Order_Item__c();
        csvInfo.Material_Code__c = tr.get('Material Code');
        csvInfo.BU_2__c = tr.get('BU');
        csvInfo.Sku_Size_US__c = tr.get('Size (US)');
        csvInfo.Season_Code_CN__c = tr.get('Season Code (CN)');
        csvInfo.UniqueKey__c = RMS_CommonUtil.item_getUniqueKey(orderCode, csvInfo);
        
        // 获取数据库中的item
        RTV_Order_Item__c item = this.existItems.get(csvInfo.UniqueKey__c);
        // 更新item
        if (item != null) {
            System.debug('存在' + item);
            // 添加到待更新（只添加需要更新的字段）
            this.updateItems.put(item.UniqueKey__c, new RTV_Order_Item__c(
                Id = item.Id,
                UniqueKey__c = item.UniqueKey__c,
                Selling_Type__c = tr.get('Selling Type'),
                Selling_Unit_Price__c = String.isBlank(tr.get('Selling Unit Price (CNY/excl.VAT)'))? 0: Decimal.valueOf(tr.get('Selling Unit Price (CNY/excl.VAT)'))
            ));
        }else {
            System.debug('找不到' + tr.values());
            this.isError = true;
            RMS_CommonUtil.pageAddMessage(ApexPages.severity.ERROR, 'No item found:' + tr.values());
        }
    }
}