force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Delivery_QTY__c.field-meta.xml
<CustomField>
    <fullName>Delivery_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Delivery QTY</description>
    <inlineHelpText>Delivery QTY</inlineHelpText>
    <label>Delivery QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Earliest_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Delivery_Date__c</fullName>
    <description>最早提货日期</description>
    <label>Earliest Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code A)</description>
    <inlineHelpText>Inspection qty (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code B)</description>
    <inlineHelpText>Inspection qty (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code C)</description>
    <inlineHelpText>Inspection qty (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code D)</description>
    <inlineHelpText>Inspection qty (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <inlineHelpText>Please check if the address is right. 
If wrong, please correct it.</inlineHelpText>
    <label>Ship-To Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <label>Ship-To Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone1__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone1__c</fullName>
    <label>Ship-To Phone1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total Application QTY</description>
    <inlineHelpText>Total Application QTY</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Delivery_QTY__c.field-meta.xml
<CustomField>
    <fullName>Delivery_QTY__c</fullName>
    <description>Total Delivery QTY</description>
    <inlineHelpText>Total Delivery QTY</inlineHelpText>
    <label>Delivery QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <description>Total Inspection QTY (Reason Code A)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <description>Total Inspection QTY (Reason Code B)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <description>Total Inspection QTY (Reason Code C)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <description>Total Inspection QTY (Reason Code D)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Order_CurSta_QTY.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Order_CurSta_QTY {
    @IsTest
    public static void test() {
        RTV_Summary__c summary = new RTV_Summary__c();
        insert summary;

        RTV_Order__c order = new RTV_Order__c();
        order.Return_Summary__c = summary.Id;
        order.Name = 'xxx';
        order.Status__c = 'Ready';
        order.Earliest_Delivery_Date__c = System.today();
        order.Ship_To_Contact__c = 'xx';
        order.Ship_To_Phone1__c = '13012345678';
        order.Ship_To_Address__c = 'xx';
        order.Application_QTY__c = 111;
        order.Delivery_QTY__c = 111;
        order.Inspect_QTY_A__c = 111;
        order.Inspect_QTY_B__c = 111;
        order.Inspect_QTY_C__c = 111;
        order.Inspect_QTY_D__c = 111;
        insert order;

        order.Status__c = 'POST to LF';
        order.Application_QTY__c = 222;
        update order;

        order.Status__c = 'Delivered';
        order.Delivery_QTY__c = 222;
        update order;

        order.Status__c = 'Inspected';
        order.Inspect_QTY_A__c = 222;
        order.Inspect_QTY_B__c = 222;
        order.Inspect_QTY_C__c = 222;
        order.Inspect_QTY_D__c = 222;
        update order;

        order.Status__c = 'Completed';
        update order;

    }
}