force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Inbound_QTY__c.field-meta.xml
<CustomField>
    <fullName>Inbound_QTY__c</fullName>
    <label>Inbound QTY</label>
    <summarizedField>RTV_Order_Item__c.Inbound_QTY__c</summarizedField>
    <summaryForeignKey>RTV_Order_Item__c.RTV_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code A)</description>
    <inlineHelpText>Inspection qty (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code B)</description>
    <inlineHelpText>Inspection qty (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code C)</description>
    <inlineHelpText>Inspection qty (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inbound_QTY__c.field-meta.xml
<CustomField>
    <fullName>Inbound_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inbound QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RTV_DTC_Summary_InboundABC_Batch.cls
public with sharing class RTV_DTC_Summary_InboundABC_Batch implements Database.Batchable<SObject>, Database.Stateful{
    public Set<Id> workOrdersIds {get; set;}
    public RTV_DTC_Summary_InboundABC_Batch(Set<Id> workOrdersIds) {
        this.workOrdersIds = workOrdersIds;
    }
     /** 开始 */
     public Database.QueryLocator start(Database.BatchableContext info){
        return Database.getQueryLocator([
            SELECT Id, Inspect_QTY_A__c, Inspect_QTY_B__c, Inspect_QTY_C__c
            FROM RTV_Order_Item__c
            WHERE RTV_Order__c IN :this.workOrdersIds
        ]);
    }

    /** 执行 */
    public void execute(Database.BatchableContext info, List<RTV_Order_Item__c> items){
        List<RTV_Order_Item__c> upItems = new List<RTV_Order_Item__c>();
        // 遍历item
        for (RTV_Order_Item__c item: Items) {
            // 设置inboundQty
            RTV_Order_Item__c upItem = new RTV_Order_Item__c();
            upItem.Id = item.Id;
            upItem.Inbound_QTY__c =  item.Inspect_QTY_A__c + item.Inspect_QTY_B__c + item.Inspect_QTY_C__c;
            upItems.add(upItem);
        }
        update upItems;
    }
    
    /** 结束 */
    public void finish(Database.BatchableContext info){
        // 抛出job执行时统计的异常
        AsyncApexJob job = [SELECT ExtendedStatus FROM AsyncApexJob WHERE Id = :info.getJobId() LIMIT 1];
        if (!String.isEmpty(job.ExtendedStatus)) {
            throw new RMS_CommonUtil.RMSException(job.ExtendedStatus);
        }
    }




}