force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Amount_inV__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount_inV__c</fullName>
    <label>Actual Amount (CNY/incl.VAT)</label>
    <summarizedField>RTV_Order_Item__c.Actual_Amount_inV__c</summarizedField>
    <summaryForeignKey>RTV_Order_Item__c.RTV_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_CS_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_CS_Confirmed__c</fullName>
    <label>Actual Date Of CS Confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Delivered__c</fullName>
    <label>Actual Date Of Delivered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_Delivered_Complete__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Delivered_Complete__c</fullName>
    <label>Actual Date Of Arrive DC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_Inspected__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Inspected__c</fullName>
    <label>Actual Date Of Inspected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_PTLF__c</fullName>
    <label>Actual Date Of PTLF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_WSL_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_WSL_Confirmed__c</fullName>
    <label>Actual Date Of WSL Confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Application_Amount__c.field-meta.xml
<CustomField>
    <fullName>Application_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total application amount of return order items.</description>
    <inlineHelpText>Total application amount of return order items.</inlineHelpText>
    <label>Application Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>IF(Return_Summary__r.DTC_Type__c==&apos;CFS&apos;     || ISPICKVAL(RTV_DEF_Summary__r.DTC_Type__c, &apos;CFS&apos;), &apos;CFS&apos;,
IF(Return_Summary__r.DTC_Type__c==&apos;Digital&apos; || ISPICKVAL(RTV_DEF_Summary__r.DTC_Type__c, &apos;DIG&apos;), &apos;Digital&apos;,
&apos;&apos;))</formula>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/IsDTC__c.field-meta.xml
<CustomField>
    <fullName>IsDTC__c</fullName>
    <formula>ISPICKVAL(Order_Type__c, &apos;CFS DTC Takeback&apos;) || 
ISPICKVAL(Order_Type__c, &apos;Digital DTC Takeback&apos;) || 
ISPICKVAL(Order_Type__c, &apos;CFS DTC Defective&apos;) || 
ISPICKVAL(Order_Type__c, &apos;Digital DTC Defective&apos;)</formula>
    <label>IsDTC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Amount(CNY/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Actual_Amount_inV__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount_inV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Amount(CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Application_Amount__c.field-meta.xml
<CustomField>
    <fullName>Application_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Application Amount (USD/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/BudgetAmount__c.field-meta.xml
<CustomField>
    <fullName>BudgetAmount__c</fullName>
    <label>BudgetAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/BudgetQTY__c.field-meta.xml
<CustomField>
    <fullName>BudgetQTY__c</fullName>
    <label>BudgetQTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/IsDTC__c.field-meta.xml
<CustomField>
    <fullName>IsDTC__c</fullName>
    <formula>RTV_Order__r.IsDTC__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsDTC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Order_Season__c.field-meta.xml
<CustomField>
    <fullName>Order_Season__c</fullName>
    <label>Order Season</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Color__c.field-meta.xml
<CustomField>
    <fullName>SKU_Color__c</fullName>
    <label>SKU Color</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Style__c.field-meta.xml
<CustomField>
    <fullName>SKU_Style__c</fullName>
    <label>SKU Style</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/RTV_SKU_KPI__c.object-meta.xml
<CustomObject>
    <description>SKU KPI</description>
    <label>RTV SKU KPI</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV SKU KPI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <label>ACCOUNT GROUP</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <label>Actual Amount(CNY/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Amount_inV__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount_inV__c</fullName>
    <label>Actual Amount(CNY/incl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Date_Of_CS_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_CS_Confirmed__c</fullName>
    <label>Actual Date Of CS Confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Date_Of_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Delivered__c</fullName>
    <label>Actual Date Of Delivered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Date_Of_Delivered_Complete__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Delivered_Complete__c</fullName>
    <label>Actual Date Of Arrive DC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Date_Of_Inspected__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Inspected__c</fullName>
    <label>Actual Date Of Inspected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Date_Of_Kick_Off__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_Kick_Off__c</fullName>
    <label>Actual Date Of Kick Off</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Date_Of_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_PTLF__c</fullName>
    <label>Actual Date Of PTLF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Actual_Date_Of_WSL_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_WSL_Confirmed__c</fullName>
    <label>Actual Date Of WSL Confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/BudgetQTY__c.field-meta.xml
<CustomField>
    <fullName>BudgetQTY__c</fullName>
    <label>BudgetQTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Date_Of_TB_Start__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_TB_Start__c</fullName>
    <label>Date Of TB Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Expected_Date_Of_CS_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_CS_Confirmed__c</fullName>
    <label>Expected Date Of CS Confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Expected_Date_Of_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_Inbound__c</fullName>
    <label>Expected Date Of Inbound</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Expected_Date_Of_Inpected__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_Inpected__c</fullName>
    <label>Expected Date Of Inpected</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Expected_Date_Of_PTLF__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_PTLF__c</fullName>
    <label>Expected Date Of PTLF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Expected_Date_Of_WSL_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_WSL_Confirmed__c</fullName>
    <label>Expected Date Of WSL Confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Order_Season__c.field-meta.xml
<CustomField>
    <fullName>Order_Season__c</fullName>
    <label>Order Season</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Style__c.field-meta.xml
<CustomField>
    <fullName>Style__c</fullName>
    <label>Style</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV SKU KPI</relationshipLabel>
    <relationshipName>RTV_SKU_KPI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTV_Bth_SKU_KPI.cls
public class RTV_Bth_SKU_KPI implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    Map<String, RTV_SKU_KPI__c> skuMap = new Map<String, RTV_SKU_KPI__c>();
    Set<Id> thisSummaryIds = new Set<Id>();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        System.debug('start RTV_Bth_SKU_KPI...');
        String query = 'SELECT RTV_Order__r.Return_Summary__r.RTV_Program__r.Finance_Code__c, RTV_Order__r.Return_Summary__r.Account_Group__r.Name,' +
            'RTV_Order__r.Return_Summary__c, RTV_Order__r.Return_Summary__r.Name, RTV_Order__r.Return_Summary__r.Status__c, RTV_Order__r.Return_Summary__r.Expected_Date_Of_Inbound__c,' +
            'RTV_Order__r.Return_Summary__r.Expected_Date_Of_LF_Inbound__c,RTV_Order__r.Return_Summary__r.LF_WH_Inbound_Date__c,RTV_Order__r.Return_Summary__r.CS_Inbound_Date__c, RTV_Order__r.Return_Summary__r.Date_Of_TB_Start__c, RTV_Order__r.Return_Summary__r.Actual_Date_Of_Kick_Off__c,' +
            'RTV_Order__r.Return_Summary__r.Expected_Date_Of_PTLF__c, RTV_Order__r.Return_Summary__r.Actual_Date_Of_PTLF__c, RTV_Order__r.Return_Summary__r.Expected_Date_Of_Delivered__c,' +
            'RTV_Order__r.Return_Summary__r.Actual_Date_Of_Delivered__c, RTV_Order__r.Return_Summary__r.Actual_Date_Of_Delivered_Complete__c, RTV_Order__r.Return_Summary__r.Expected_Date_Of_Inpected__c,' +
            'RTV_Order__r.Return_Summary__r.Actual_Date_Of_Inspected__c, RTV_Order__r.Return_Summary__r.Expected_Date_Of_CS_Confirmed__c, RTV_Order__r.Return_Summary__r.Actual_Date_Of_CS_Confirmed__c,' +
            'RTV_Order__r.Return_Summary__r.Expected_Date_Of_WSL_Confirmed__c, RTV_Order__r.Return_Summary__r.Actual_Date_Of_WSL_Confirmed__c, ' +
            'RTV_Order__r.Return_Summary__r.DTC_Type__c, ' +
            'RTV_Order__r.Return_Summary__r.OwnerId, ' +
            'RTV_Order__r.Status__c, ' +
            'RTV_Order__r.Name, ' +
            'Id, ' +
            'BudgetQTY__c, ' +
            'BudgetAmount__c, ' +
            'Order_Season__c, ' +
            'Application_Amount__c, '+
            'Actual_Amount__c, ' +
            'Actual_Amount_inV__c, ' +
            'IsDTC__c,'+
            'Material_Code__c, BU_2__c, SKU_Style__c, SKU_Color__c, SKU_Size_US__c,' +
            'Inbound_QTY__c, Application_QTY__c, Inspect_QTY_A__c, Inspect_QTY_B__c, Inspect_QTY_C__c, Inspect_QTY_D__c ' +
            'FROM RTV_Order_Item__c WHERE RTV_Order__r.Return_Summary__c != NULL';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        System.debug('execute RTV_Bth_SKU_KPI...' + scope.size());

        //Key: summaryId
        Map<Id, List<RTV_Order_Item__c>> orderItemMap = new Map<Id, List<RTV_Order_Item__c>>();
        for (SObject s: scope) {
            RTV_Order_Item__c o = (RTV_Order_Item__c)s;
            if (orderItemMap.containsKey(o.RTV_Order__r.Return_Summary__c)) {
                orderItemMap.get(o.RTV_Order__r.Return_Summary__c).add(o);
            }else {
                orderItemMap.put(o.RTV_Order__r.Return_Summary__c, new List<RTV_Order_Item__c>{o});
            }
        }

        String key = null;
        Map<String, RTV_SKU_KPI__c> tempSkuMap = new Map<String, RTV_SKU_KPI__c>();
        for (List<RTV_Order_Item__c> items : orderItemMap.values()) {
            for (RTV_Order_Item__c obj : items) {
                key = obj.RTV_Order__r.Return_Summary__c + obj.Material_Code__c + obj.BU_2__c + obj.SKU_Style__c + obj.SKU_Color__c + obj.SKU_Size_US__c+ obj.Id;
                RTV_SKU_KPI__c skuItem = new RTV_SKU_KPI__c();
                // 初始化
                skuItem.Inbound_QTY__c = 0;
                skuItem.Inspect_QTY_A__c = 0;
                skuItem.Inspect_QTY_B__c = 0;
                skuItem.Inspect_QTY_C__c = 0;
                skuItem.Inspect_QTY_D__c = 0;
                skuItem.Current_Status_QTY__c = 0;
    
                if(skuMap.containsKey(key)){
                    skuItem = skuMap.get(key);
                }else if(tempSkuMap.containsKey(key)){
                    skuItem = tempSkuMap.get(key);
                }
                
                skuItem.OwnerId = obj.RTV_Order__r.Return_Summary__r.OwnerId;
                skuItem.Summary__c = obj.RTV_Order__r.Return_Summary__c;
                skuItem.SummaryId__c = obj.RTV_Order__r.Return_Summary__c;
                skuItem.OrderName__c = obj.RTV_Order__r.Name;
                skuItem.OrderItemId__c = obj.Id;
                skuItem.BudgetQTY__c = obj.BudgetQTY__c;
                skuItem.BudgetAmount__c = obj.BudgetAmount__c;
                skuItem.Order_Season__c = obj.Order_Season__c;
                skuItem.Applied_Amount__c = obj.Application_Amount__c;
                skuItem.Actual_Amount__c = obj.Actual_Amount__c;
                skuItem.Actual_Amount_inV__c = obj.Actual_Amount_inV__c;

                skuItem.Finance_Code__c = obj.RTV_Order__r.Return_Summary__r.RTV_Program__r.Finance_Code__c;
                skuItem.Account_Group__c = obj.RTV_Order__r.Return_Summary__r.Account_Group__r.Name;
                skuItem.Name = obj.RTV_Order__r.Return_Summary__r.Name;
                skuItem.Current_Status__c = obj.RTV_Order__r.Return_Summary__r.Status__c == 'POST to LF' ? 'In Progress' : obj.RTV_Order__r.Return_Summary__r.Status__c;
                
                skuItem.BU__c = obj.BU_2__c;
                skuItem.Material_Code__c = obj.Material_Code__c;
                skuItem.Style__c = obj.SKU_Style__c;
                skuItem.Color__c = obj.SKU_Color__c != null ? obj.SKU_Color__c.leftPad(3,'0') : obj.SKU_Color__c;
                skuItem.Size__c = obj.SKU_Size_US__c;
    
                skuItem.Inbound_QTY__c += obj.Inbound_QTY__c == null ? 0 : obj.Inbound_QTY__c;
                skuItem.Inspect_QTY_A__c += obj.Inspect_QTY_A__c == null ? 0 : obj.Inspect_QTY_A__c;
                skuItem.Inspect_QTY_B__c += obj.Inspect_QTY_B__c == null ? 0 : obj.Inspect_QTY_B__c;
                skuItem.Inspect_QTY_C__c += obj.Inspect_QTY_C__c == null ? 0 : obj.Inspect_QTY_C__c;
                skuItem.Inspect_QTY_D__c += obj.Inspect_QTY_D__c == null ? 0 : obj.Inspect_QTY_D__c;
    
                /**
                 * Current Status QTY
                 * Order状态为Ready或POST To LF     =>      申请数量
                 * Order状态为Delivery              =>      提货数量???
                 * Order状态为Inspected             =>      质检数量
                 * Order状态为Completed             =>      入库数量
                 */
                if(obj.RTV_Order__r.Status__c == 'Ready' || obj.RTV_Order__r.Status__c == 'POST to LF'){
                    skuItem.Current_Status_QTY__c += obj.Application_QTY__c == null ? 0 : obj.Application_QTY__c;
                }else if(obj.RTV_Order__r.Status__c == 'Delivered'){
                    //TODO:一个SKU的提货数量
                    skuItem.Current_Status_QTY__c += obj.Application_QTY__c == null ? 0 : obj.Application_QTY__c;
                }else if(obj.RTV_Order__r.Status__c == 'Completed'||obj.RTV_Order__r.Status__c == 'Inbound'){
                    skuItem.Current_Status_QTY__c += obj.Inbound_QTY__c;
                }else {
                    skuItem.Current_Status_QTY__c += (obj.Inspect_QTY_A__c + obj.Inspect_QTY_B__c + obj.Inspect_QTY_C__c + obj.Inspect_QTY_D__c);
                }
    
                skuItem.Expected_Date_Of_Inbound__c = obj.RTV_Order__r.Return_Summary__r.Expected_Date_Of_LF_Inbound__c;
                skuItem.Actual_Date_Of_Inbound__c= obj.RTV_Order__r.Return_Summary__r.LF_WH_Inbound_Date__c;
                skuItem.Expected_Date_of_Billing_Realease__c = obj.RTV_Order__r.Return_Summary__r.Expected_Date_Of_Inbound__c;
                skuItem.Actual_Date_of_Billing_Realease__c = obj.RTV_Order__r.Return_Summary__r.CS_Inbound_Date__c;
                skuItem.Date_Of_TB_Start__c = obj.RTV_Order__r.Return_Summary__r.Date_Of_TB_Start__c;
                skuItem.Actual_Date_Of_Kick_Off__c = obj.RTV_Order__r.Return_Summary__r.Actual_Date_Of_Kick_Off__c;
                skuItem.Expected_Date_Of_PTLF__c = obj.RTV_Order__r.Return_Summary__r.Expected_Date_Of_PTLF__c;
                skuItem.Actual_Date_Of_PTLF__c = obj.RTV_Order__r.Return_Summary__r.Actual_Date_Of_PTLF__c;
                skuItem.Expected_Date_Of_Delivered_Complete__c = obj.RTV_Order__r.Return_Summary__r.Expected_Date_Of_Delivered__c;
                skuItem.Actual_Date_Of_Delivered__c = obj.RTV_Order__r.Return_Summary__r.Actual_Date_Of_Delivered__c;
                skuItem.Actual_Date_Of_Delivered_Complete__c = obj.RTV_Order__r.Return_Summary__r.Actual_Date_Of_Delivered_Complete__c;
                skuItem.Expected_Date_Of_Inpected__c = obj.RTV_Order__r.Return_Summary__r.Expected_Date_Of_Inpected__c;
                skuItem.Actual_Date_Of_Inspected__c = obj.RTV_Order__r.Return_Summary__r.Actual_Date_Of_Inspected__c;
                skuItem.Expected_Date_Of_CS_Confirmed__c = obj.RTV_Order__r.Return_Summary__r.Expected_Date_Of_CS_Confirmed__c;
                skuItem.Actual_Date_Of_CS_Confirmed__c = obj.RTV_Order__r.Return_Summary__r.Actual_Date_Of_CS_Confirmed__c;
                skuItem.Expected_Date_Of_WSL_Confirmed__c = obj.RTV_Order__r.Return_Summary__r.Expected_Date_Of_WSL_Confirmed__c;
                skuItem.Actual_Date_Of_WSL_Confirmed__c = obj.RTV_Order__r.Return_Summary__r.Actual_Date_Of_WSL_Confirmed__c;
                skuItem.OrderStatus__c = obj.RTV_Order__r.Status__c;
    
                tempSkuMap.put(key, skuItem);
                thisSummaryIds.add(skuItem.SummaryId__c);
            }
        }

        if(!tempSkuMap.isEmpty()) {
            List<RTV_SKU_KPI__c> tempSkus = tempSkuMap.values();
            system.debug('tempSkusCount:'+tempSkus.Size());
            upsert tempSkus;

            for (RTV_SKU_KPI__c obj : tempSkus) {
                key = obj.SummaryId__c + obj.Material_Code__c + obj.BU__c + obj.Style__c + obj.Color__c + obj.Size__c+obj.OrderItemId__c;
                skuMap.put(key, obj);
            }
        }

    }
    
    public void finish(Database.BatchableContext bc) {
        System.debug('finish RTV_Bth_SKU_KPI...');
        
    }
    // 用于跳过代码覆盖率测试
    public static void lieToTest() {
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}