force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>WSL Takeback OR DTC Takeback</description>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WSL Takeback</fullName>
                <default>true</default>
                <label>WSL Takeback</label>
            </value>
            <value>
                <fullName>RTV Defective</fullName>
            </value>
            <value>
                <fullName>CFS DTC Takeback</fullName>
            </value>
            <value>
                <fullName>Digital DTC Takeback</fullName>
            </value>
            <value>
                <fullName>CFS DTC Defective</fullName>
            </value>
            <value>
                <fullName>Digital DTC Defective</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_Asia__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_Asia__c</fullName>
    <description>亚码</description>
    <label>SKU Size (Asia)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/recordTypes/DTC.recordType-meta.xml
<RecordType>
    <fullName>DTC</fullName>
    <active>true</active>
    <label>DTC</label>
</RecordType>

force-app/main/default/classes/Test_Trigger_RMS_OrderItem_Size_DTC.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_OrderItem_Size_DTC {
    @IsTest
    public static void test() {
        
        RTV_Order__c order =new RTV_Order__c();
        order.Order_Type__c='CFS DTC Takeback';
        insert order;
        RTV_Order_Item__c item = new RTV_Order_Item__c();
        item.RTV_Order__c = order.Id;
        item.BU_2__c ='AP';
        item.SKU_Size_Asia__c='XXL';
        
        insert item;
    }
}