force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Insp_CS_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_CS_Approve_Time__c</fullName>
    <description>CS审批的时间</description>
    <label>Insp CS Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Process Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <description>PS：因为Number字段类型会显示千分符，所以选Text类型</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Earliest_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Delivery_Date__c</fullName>
    <description>最早提货日期</description>
    <label>Earliest Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Insp_CS_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_CS_Approve_Time__c</fullName>
    <label>Insp CS Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_DEF_Summary__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV DEF Summary</label>
    <referenceTo>RTV_DEF_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <inlineHelpText>Please check if the address is right. 
If wrong, please correct it.</inlineHelpText>
    <label>Ship-To Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <label>Ship-To Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Outbound_Emails__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Outbound_Emails__c</fullName>
    <inlineHelpText>请输入Ship-To外部Email地址（逗号分割的1~5个地址）</inlineHelpText>
    <label>Ship-To Outbound Emails</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone1__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone1__c</fullName>
    <label>Ship-To Phone1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone2__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone2__c</fullName>
    <label>Ship-To Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Order_StatusChange_DEF.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Order_StatusChange_DEF {
    @isTest
    public static void test() {
        // defsummary
        RTV_DEF_Summary__c summary = new RTV_DEF_Summary__c();
        summary.Year__c = '2019';
        summary.Month__c = 12;
        insert summary;
        
        // 创建order
        RTV_Order__c order = new RTV_Order__c();
        order.RTV_DEF_Summary__c = summary.Id;
        order.Earliest_Delivery_Date__c = System.today();
        order.Ship_To_Contact__c = 'xx';
        order.Ship_To_Phone1__c = '13012341234';
        order.Ship_To_Phone2__c = '13012341234';
        order.Ship_To_Address__c = 'xx';
        order.Ship_To_Outbound_Emails__c = 'xx@xx.xx';
        order.Application_QTY__c = 123.45;
        order.Status__c = 'Ready';
        insert order;
        
        // update order
        order.Status__c = 'POST to LF';
        update order;
        
        // update order
        order.Insp_CS_Approve_Time__c = System.now();
        update order;
    }
}