force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Process Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_DEF_Summary__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV DEF Summary</label>
    <referenceTo>RTV_DEF_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTV_Order_ClearData.cls
public class RTV_Order_ClearData {
    /** LoginUserInfo */
    public RMS_CommonUtil.LoginUserInfo loginUser = new RMS_CommonUtil.LoginUserInfo();
    public RMS_CommonUtil.LoginUserInfo getLoginUser() {return loginUser;}

    public final Id summaryId = ApexPages.currentPage().getParameters().get('summaryId');
    public final Id defSummaryId = ApexPages.currentPage().getParameters().get('defSummaryId');

    // orders
    public List<RTV_Order__c> objs {get; set;}

    /** 载入页面 */
    public void loadPage() {
        // 从RTVSummary页面进入时
        if (this.summaryId != null) {
            this.objs = [
                SELECT Id, Name, Status__c
                FROM RTV_Order__c WHERE Return_Summary__c = :summaryId AND Status__c = 'Ready'
            ];
        } 
        // 从RTVDEFSummary页面进入时
        else if (this.defSummaryId != null) {
            this.objs = [
                SELECT Id, Name, Status__c
                FROM RTV_Order__c WHERE RTV_DEF_Summary__c = :defSummaryId AND Status__c = 'Ready'
            ];
        }
    }

    /** 删除该Summary下的所有的没有被POST to LF的Order */
    public void clearData(){
        try {
            if(this.objs.size() < 1){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'No data to clear'));
                return;
            }
            delete objs;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO, 'Cleared successfully'));
            
            loadPage();
        } catch (Exception err) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, err.getMessage()));
        }
    }

    /** 返回上一页 */
    public PageReference cancel(){
        PageReference returnPage = new PageReference('/' + this.summaryId);
        returnPage.setRedirect(true);
        return returnPage;  
    }
}