force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Insp_CS_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_CS_Approve_Time__c</fullName>
    <description>CS审批的时间</description>
    <label>Insp CS Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Process Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/From_TakeBack_Order__c.field-meta.xml
<CustomField>
    <fullName>From_TakeBack_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From TakeBack Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>To DEF Orders</relationshipLabel>
    <relationshipName>To_DEF_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Insp_CS_Approve_Time__c.field-meta.xml
<CustomField>
    <fullName>Insp_CS_Approve_Time__c</fullName>
    <label>Insp CS Approve Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_DEF_Summary__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV DEF Summary</label>
    <referenceTo>RTV_DEF_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTV_Defective_SellingPrice.cls
public inherited sharing class RTV_Defective_SellingPrice {
    
    // 参数: DEF Summary
    public final Id defSummaryId = ApexPages.currentPage().getParameters().get('defSummaryId');
    
    // 参数：Order范围仅为TB转DEF
    public final Boolean isFromTakeback = 'true'.equalsIgnoreCase(ApexPages.currentPage().getParameters().get('isFromTakeback'));
    
    // 页面显示: order列表
    public List<RTV_Order__c> orderList {get; set;}
    public Integer orderListCnt {get; set;}
    
    // 页面Input：税率
    public Decimal TaxRate{get;set;}
    
    // 批处理
    public AsyncApexJob batchJob {get; set;}
    // 载入中
    public Boolean isLoading {get; set;}
    // 载入中(进度%)
    public Integer loadingPercent {get { return getJobPercent(this.batchJob); }}

    /** 构造方法 */
    public RTV_Defective_SellingPrice() {
        if (isFromTakeback) {
            this.orderList = [
                SELECT Name FROM RTV_Order__c 
                WHERE RTV_DEF_Summary__c = :this.defSummaryId 
                AND Status__c = 'Insp Wait Approval'
                AND From_Takeback_Order__c != null
            ];
        } else {
            this.orderList = [
                SELECT Name FROM RTV_Order__c 
                WHERE RTV_DEF_Summary__c = :this.defSummaryId 
                AND Status__c = 'Insp Wait Approval'
                AND From_Takeback_Order__c = null
                AND Insp_CS_Approve_Time__c = null  //必须在CS审批前Mapping
            ];
        }
        this.orderListCnt = this.orderList.size();
        if (orderListCnt == 0) {
            RMS_CommonUtil.pageAddMessage(ApexPages.Severity.INFO, '没有CS审批中的订单.');
        }
    }
    
    /** 关闭页面 */
    public PageReference cancel(){
        PageReference returnPage = new PageReference('/' + this.defSummaryId);
        returnPage.setRedirect(true);
        return returnPage;  
    }
    
    /** 开始执行 */
    public void startBatch() {
        this.isLoading = true;
        
        // 执行batch
        RTV_Defective_SellingPrice_Batch batch = new RTV_Defective_SellingPrice_Batch(
            this.defsummaryId, this.TaxRate, this.isFromTakeback
        );
        this.batchJob = new AsyncApexJob();
        this.batchJob.Id = Database.executeBatch(batch, 1); //SellingPricebatch一次执行一个order，这里参数只能设1
    }
    
    /** 检查执行结果 */
    public void checkResult() {
        // 检索batch
        this.batchJob = [
            SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors, CompletedDate, ExtendedStatus
            FROM AsyncApexJob WHERE Id = :this.batchJob.Id LIMIT 1
        ];
        // 结束时
        if (this.batchJob.CompletedDate != null) {
            // 成功时
            if (String.isBlank(batchJob.ExtendedStatus)) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.CONFIRM, 'Get selling price success'));
            }
            // 错误信息
            if (!String.isBlank(batchJob.ExtendedStatus)) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, batchJob.ExtendedStatus));
            }
            this.isLoading = false;
        }
    }
    
    /** 静态方法：计算job执行进度 */
    private static Integer getJobPercent(AsyncApexJob job) {
        if (job != null && job.TotalJobItems > 0) {
            return Integer.valueOf(job.JobItemsProcessed / job.TotalJobItems * 100.0);
        }
        return 0;
    }
}