force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Process Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <defaultValue>TEXT(YEAR(TODAY()))</defaultValue>
    <description>PS：因为Number字段类型会显示千分符，所以选Text类型</description>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/RTV_Defective__c.object-meta.xml
<CustomObject>
    <label>RTV DEF Program</label>
    <nameField>
        <label>Defective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Defective__c/fields/Defective_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Defective_Auth_Code__c</fullName>
    <label>Finance Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/From_Takeback_Order__c.field-meta.xml
<CustomField>
    <fullName>From_Takeback_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This Defective is created from a Takeback order</description>
    <inlineHelpText>This Defective is created from a Takeback order</inlineHelpText>
    <label>From Takeback Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipName>RTV_Defective</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Refresh__c.field-meta.xml
<CustomField>
    <fullName>Refresh__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refresh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Off Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCAPP</fullName>
            </value>
            <value>
                <fullName>FTW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_WSL_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_WSL_Confirmed__c</fullName>
    <label>Actual Date Of WSL Confirmed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Actual_Date_Of_WSL_Inbound__c.field-meta.xml
<CustomField>
    <fullName>Actual_Date_Of_WSL_Inbound__c</fullName>
    <label>Actual Date Of TB To DEF</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/From_TakeBack_Order__c.field-meta.xml
<CustomField>
    <fullName>From_TakeBack_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From TakeBack Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>To DEF Orders</relationshipLabel>
    <relationshipName>To_DEF_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_DEF_Summary__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV DEF Summary</label>
    <referenceTo>RTV_DEF_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Defective__c.field-meta.xml
<CustomField>
    <fullName>RTV_Defective__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV Defective(AC/AP)</label>
    <referenceTo>RTV_Defective__c</referenceTo>
    <relationshipLabel>RTV Orders(AC/AP)</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Defective.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Defective {
    @IsTest
    static void test()
    {
        RTV_Defective__c def = new RTV_Defective__c();
        def.name = 'def';
        def.Type__c = 'FTW';
        def.Defective_Auth_Code__c = '111111';
        def.Start_Date__c = Date.today();
        def.End_Date__c = Date.today().addDays(20);
        insert def;

        RTV_DEF_Summary__c defsummary = new RTV_DEF_Summary__c();
        defsummary.Year__c = '2021';
        defsummary.Month__c = 4;
        insert defsummary;

        RTV_Order__c order = new RTV_Order__c();
        order.RTV_DEF_Summary__c = defsummary.id;
        order.Actual_Date_Of_WSL_Confirmed__c = Date.today().addDays(10);
        insert order;

        RTV_Order__c tborder = new RTV_Order__c();
        tborder.RTV_DEF_Summary__c = defsummary.id;
        tborder.From_TakeBack_Order__c = order.id;
        tborder.Actual_Date_Of_WSL_Inbound__c = Date.today().addDays(10);
        insert tborder;

        def.Status__c = 'Off Policy';
        def.Refresh__c = true;
        update def;

        RTV_Defective__c deftest = new RTV_Defective__c();
        deftest.Type__c = 'FTW';
        deftest.name = 'deftest';
        deftest.Defective_Auth_Code__c = '222222';
        deftest.Start_Date__c = Date.today();
        deftest.End_Date__c = Date.today().addDays(20);
        insert deftest;

        RTV_Defective__c acapdef = new RTV_Defective__c();
        acapdef.name = 'acapdef';
        acapdef.Type__c = 'ACCAPP';
        acapdef.Defective_Auth_Code__c = '333333';
        acapdef.Start_Date__c = Date.today().addDays(1);
        acapdef.End_Date__c = Date.today().addDays(21);
        insert acapdef;

        acapdef.Refresh__c = true;
        update acapdef;
    }
}