force-app/main/default/objects/RTV_SKU_KPI__c/RTV_SKU_KPI__c.object-meta.xml
<CustomObject>
    <description>SKU KPI</description>
    <label>RTV SKU KPI</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV SKU KPI</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_SKU_KPI__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RTV_Sch_SKU_KPI.cls
global class RTV_Sch_SKU_KPI implements Schedulable {

    global void execute(SchedulableContext sc){
        // RESET SKU KPI
        // RTV_Bth_SKU_KPI_Del bth = new RTV_Bth_SKU_KPI_Del('SELECT Id FROM RTV_SKU_KPI__c WHERE Current_Status__c != \'Completed\'');
        RTV_Bth_SKU_KPI_Del bth = new RTV_Bth_SKU_KPI_Del('SELECT Id FROM RTV_SKU_KPI__c');
        Database.executebatch(bth, 5000);
    }
}