force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Province</description>
    <label>Province</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Process Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/RTV_LF_Order__c.object-meta.xml
<CustomObject>
    <label>RTV LF Order</label>
    <nameField>
        <label>LF Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV LF Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_LF_Order__c/fields/Application_Box_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_Box_QTY__c</fullName>
    <description>申请箱数</description>
    <label>Application Box QTY</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <label>BU-2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/LF_Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>LF_Order_Auth_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LF Order Auth Code</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV LF Orders</relationshipLabel>
    <relationshipName>RTV_LF_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Earliest_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Delivery_Date__c</fullName>
    <description>最早提货日期</description>
    <label>Earliest Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Have_Read_Delivery_Report__c.field-meta.xml
<CustomField>
    <fullName>Have_Read_Delivery_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Have Read Delivery Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Auth_Code__c</fullName>
    <externalId>true</externalId>
    <label>Order Auth Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_DEF_Summary__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV DEF Summary</label>
    <referenceTo>RTV_DEF_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <inlineHelpText>Please check if the address is right. 
If wrong, please correct it.</inlineHelpText>
    <label>Ship-To Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <label>Ship-To Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone1__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone1__c</fullName>
    <label>Ship-To Phone1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone2__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone2__c</fullName>
    <label>Ship-To Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTV_DeliveryPDF_Export.cls
public with sharing  class RTV_DeliveryPDF_Export {
    /** url参数: summaryId */
    public String summaryId = ApexPages.currentPage().getParameters().get('summaryId');
    public List<RTV_LF_Order__c> results {get; set;}
    public Map<Id, List<RTV_LF_Order__c>> orderMap {get; set;}
    public Set<Id> orderIds {get; set;}
    public List<PDF_Extend> allOrders{get;set;}
    public List<PDF_Extend> orders{get;set;}
    public String printType {get; set;}
    public Boolean isOpening {get; set;}
    RMS_CommonUtil.LoginUserInfo loginUser = new RMS_CommonUtil.LoginUserInfo();
    
    public RTV_DeliveryPDF_Export() {
        this.isOpening = true;
        if (this.summaryId != null) {
            this.results = [
                SELECT BU_2__c, Application_Box_QTY__c, 
                    Application_QTY__c, 
                    LF_Order_Auth_Code__c,
                    RTV_Order__r.Order_Auth_Code__c, 
                    RTV_Order__r.Earliest_Delivery_Date__c, 
                    RTV_Order__r.Ship_To__r.Sold_To_Code__r.Sold_To_Name_CN__c, 
                    RTV_Order__r.Ship_To__r.Province__c, 
                    RTV_Order__r.Ship_To__r.City__c, 
                    RTV_Order__r.Ship_To_Contact__c, 
                    RTV_Order__r.Ship_To_Phone1__c, 
                    RTV_Order__r.Ship_To_Phone2__c, 
                    RTV_Order__r.Ship_To_Address__c, 
                    RTV_Order__r.Ship_To__r.Sold_To_Code__r.Name, 
                    RTV_Order__r.Ship_To__r.Name,
                    RTV_Order__r.Have_Read_Delivery_Report__c,
                    RTV_Order__r.RTV_DEF_Summary__c
                FROM RTV_LF_Order__c
                WHERE (RTV_Order__r.Return_Summary__c = :this.summaryId 
                     OR RTV_Order__r.RTV_DEF_Summary__c = :this.summaryId)
                AND RTV_Order__r.Status__c IN ('POST to LF')
            ];

            // Id 是orderID
            this.orderMap = new Map<Id, List<RTV_LF_Order__c>>();
            for (RTV_LF_Order__c lforder : this.results) {
                if(this.orderMap.containsKey(lforder.RTV_Order__c)){
                    this.orderMap.get(lforder.RTV_Order__c).add(lforder);
                }else {
                    this.orderMap.put(lforder.RTV_Order__c, new List<RTV_LF_Order__c>{lforder});
                }
            }
 
            this.orderIds = this.orderMap.keySet();
            this.allOrders = new List<PDF_Extend>();
            for(Id id:this.orderMap.keySet()){
                PDF_Extend order = new PDF_Extend();
                order.shiptoCode=orderMap.get(id).get(0).RTV_Order__r.Ship_To__r.Name;
                order.Order_Auth_Code=orderMap.get(id).get(0).RTV_Order__r.Order_Auth_Code__c;
                order.Sold_To_Name=orderMap.get(id).get(0).RTV_Order__r.Ship_To__r.Sold_To_Code__r.Sold_To_Name_CN__c;
                order.Province=orderMap.get(id).get(0).RTV_Order__r.Ship_To__r.Province__c;
                order.City=orderMap.get(id).get(0).RTV_Order__r.Ship_To__r.City__c;
                order.Ship_To_Address=orderMap.get(id).get(0).RTV_Order__r.Ship_To_Address__c;
                order.Earliest_Delivery_Date=orderMap.get(id).get(0).RTV_Order__r.Earliest_Delivery_Date__c;
                order.Ship_To_Contact=orderMap.get(id).get(0).RTV_Order__r.Ship_To_Contact__c;
                order.Ship_To_Phone1=orderMap.get(id).get(0).RTV_Order__r.Ship_To_Phone1__c;
                order.Ship_To_Phone2=orderMap.get(id).get(0).RTV_Order__r.Ship_To_Phone2__c;
                if(orderMap.get(id).get(0).RTV_Order__r.RTV_DEF_Summary__c!=null){
                    order.orderType='DEF';
                }else{
                    order.orderType='TB';
                }
                order.lforders=orderMap.get(id);
                order.boxTotal=0;
                order.goodsTotal=0;
                order.HaveReadDelivery=orderMap.get(id).get(0).RTV_Order__r.Have_Read_Delivery_Report__c;
                for(RTV_LF_Order__c lforder : orderMap.get(id)){
                    if(lforder.Application_Box_QTY__c!=null){
                        order.boxTotal+=lforder.Application_Box_QTY__c;
                    }
                    if(lforder.Application_QTY__c!=null){
                        order.goodsTotal+=lforder.Application_QTY__c;
                    }
                }
                this.allOrders.add(order);
            }
        }
    }
    // 更新Order的'提货信息已阅'Flag
    public void updateHaveReadDelivery() {
        // 只有lf下载时更新已阅
        if (loginUser.isLF == false && !Test.isRunningTest()) {
            return;
        }
        // 待更新order
        Map<Id, RTV_Order__c> updOrders = new Map<Id, RTV_Order__c>();
        
        // 遍历lfOrder
        for (RTV_LF_Order__c lfO: this.results) {
            // 修改关联order的flag
            if (lfO.RTV_Order__r.Have_Read_Delivery_Report__c == false) {
                RTV_Order__c updO = new RTV_Order__c();
                updO.Id = lfO.RTV_Order__r.Id;
                updO.Have_Read_Delivery_Report__c = true;
                updOrders.put(updO.Id, updO);
            }
        }
        // 更新order
        if (updOrders.size() > 0) {
            update updOrders.values();
        }
    }

    public PageReference test() {
        this.isOpening = false;
        this.orders = new List<PDF_Extend>();
        // 已阅
        if(printType == 'Have Read'){
            for (PDF_Extend order : this.allOrders) {
                if(order.HaveReadDelivery==true){
                    this.orders.add(order);
                }
            }
        }
        else if(printType == 'Not Read'){
            for (PDF_Extend order : this.allOrders) {
                if(order.HaveReadDelivery==false){
                    this.orders.add(order);
                }
            }
        }
        else {
            this.orders =this.allOrders;
        }

        return null;
    }

    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('ALL','全部')); 
        options.add(new SelectOption('Have Read','已通知'));
        options.add(new SelectOption('Not Read','未通知'));
        return options; 
    }
    
    class PDF_Extend {
        public String shiptoCode{get;set;}
        public String Order_Auth_Code{get;set;}
        public String Sold_To_Name{get;set;}
        public String Province{get;set;}
        public String City{get;set;}
        public String Ship_To_Address{get;set;}
        public Date Earliest_Delivery_Date{get;set;}
        public String Ship_To_Contact{get;set;}
        public String Ship_To_Phone1{get;set;}
        public String Ship_To_Phone2{get;set;}
        public List<RTV_LF_Order__c> lforders{get;set;}
        public Decimal boxTotal{get;set;}
        public Decimal goodsTotal{get;set;}
        public Boolean HaveReadDelivery{get;set;}
        public String orderType{get;set;}
     }
    
}