force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Ship_To__c/RTV_RP_Ship_To__c.object-meta.xml
<CustomObject>
    <description>允许回收的Sold-to&amp;Ship-to白名单</description>
    <label>RTV RP Ship To</label>
    <nameField>
        <displayFormat>WL-{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV RP Ship To White List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Auth_Code__c</fullName>
    <label>Order Auth Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Removed__c.field-meta.xml
<CustomField>
    <fullName>Removed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>删除标记</description>
    <label>Removed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_Tos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>RMS_Ship_To__c.Sold_To_Code__c</field>
            <operation>equals</operation>
            <valueField>$Source.Sold_To__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipLabel>RTV RP Ship To List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipName>Return_Account_White_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_RP_Ship_To__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup RTV Summary</description>
    <label>Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV RP Ship To White List</relationshipLabel>
    <relationshipName>RTV_RP_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTV_RP_Report_ShipToWhiteList.cls
public with sharing class RTV_RP_Report_ShipToWhiteList {
    
    public final Id summaryId = ApexPages.currentPage().getParameters().get('summaryId');
    
    public final Id programId = ApexPages.currentPage().getParameters().get('programId');

    public final String isReady = ApexPages.currentPage().getParameters().get('isReady');

    public List<RTV_RP_Ship_To__c> results {get; set;}

    public Boolean isRender {get; set;}
    
    public RTV_RP_Report_ShipToWhiteList() {
        if(isReady == 'true')
        {
            this.isRender = true;
        }
        else {
            this.isRender = false;
        }
        if (summaryId != null) {
            results = [
                SELECT Ship_To__r.Name,Sold_To__r.Name,Order_Auth_Code__c FROM RTV_RP_Ship_To__c WHERE Summary__c = :summaryId AND Removed__c = False
            ];
        } else if (programId != null) {
            results = [
                SELECT Ship_To__r.Name FROM RTV_RP_Ship_To__c WHERE RTV_Program__c = :programId AND Removed__c = False
            ];
        }
    }
    
}