force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <description>Trading Term(APP/ ACC)</description>
    <inlineHelpText>Trading Term(APP/ ACC)</inlineHelpText>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/fields/TT_FTW_EG__c.field-meta.xml
<CustomField>
    <fullName>TT_FTW_EG__c</fullName>
    <description>Trading Term(FW-AS CORE)</description>
    <inlineHelpText>Trading Term(FW-AS CORE)</inlineHelpText>
    <label>TT(FW-AS CORE)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/RMS_TradingTerm__c.object-meta.xml
<CustomObject>
    <description>TradingTerm history</description>
    <label>RMS TradingTerm</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS TradingTerm</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_TradingTerm__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <formula>SUBSTITUTE(Name, TEXT(Year__c), &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sold-To Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_TradingTerm__c/fields/TT_APP_ACC__c.field-meta.xml
<CustomField>
    <fullName>TT_APP_ACC__c</fullName>
    <label>TT(APP/ ACC)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code A)</description>
    <inlineHelpText>Inspection qty (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code B)</description>
    <inlineHelpText>Inspection qty (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code C)</description>
    <inlineHelpText>Inspection qty (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code D)</description>
    <inlineHelpText>Inspection qty (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code (CN)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_SellingPrices__b/RTV_SellingPrices__b.object-meta.xml
<CustomObject>
    <description>季度成交价格表</description>
    <label>RTV SellingPrices</label>
    <pluralLabel>RTV SellingPrices</pluralLabel>
</CustomObject>

force-app/main/default/objects/RTV_SellingPrices__b/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_SellingPrices__b/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <label>Sold To Code</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <description>Total Inspection QTY (Reason Code A)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <description>Total Inspection QTY (Reason Code B)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <description>Total Inspection QTY (Reason Code C)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <description>Total Inspection QTY (Reason Code D)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RTV_Summary_SellingPrice.cls
@IsTest(isParallel=true)
public class Test_RTV_Summary_SellingPrice {
    @isTest
    public static void test() {
        // 创建soldto
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Name = '12345';
        insert soldto;
        
        // 创建shipto
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = '1234567';
        shipto.Sold_To_Code__c = soldto.Id;
        insert shipto;
        
        // 创建summary
        RTV_Summary__c summary = new RTV_Summary__c();
        insert summary;
        
        // 创建order
        RTV_Order__c order = new RTV_Order__c();
        order.Name = RMS_CommonUtil.order_getCode('xxx', 'xxxxx', 'xxx');
        order.Return_Summary__c = summary.Id;
        order.Sold_To__c = soldto.Id;
        order.Ship_To__c = shipto.Id;
        order.Status__c = 'Insp Wait Approval';
        insert order;
        
        // 创建item
        RTV_Order_Item__c item = new RTV_Order_Item__c();
        item.RTV_Order__c = order.Id;
        item.Material_Code__c = 'TestProduct';
        item.BU_2__c = 'FW';
        item.Season_Code_CN__c = '20Q1';
        item.SKU_Size_US__c = 'XL';
        item.Inspect_QTY_A__c = 1;
        item.Inspect_QTY_B__c = 1;
        item.Inspect_QTY_C__c = 1;
        item.Inspect_QTY_D__c = 1;
        insert item;
        
        // 创建tradingTerm
        RMS_TradingTerm__c tradeTerm = new RMS_TradingTerm__c();
        tradeTerm.Name = soldto.Name;
        tradeTerm.TT_APP_ACC__c = 0.9;
        tradeTerm.TT_FTW_EG__c = 0.9;
        tradeTerm.TT_FW_Seasonal__c = 0.9;
        tradeTerm.Year__c = 2019;
        insert tradeTerm;
        
        // 创建常青款
        RMS_FTW_Core_List__c ftwCore = new RMS_FTW_Core_List__c();
        ftwCore.Name = item.Material_Code__c;
        insert ftwCore;
        
        // 创建seasonCode
        RMS_SP_Season_Code__c season = new RMS_SP_Season_Code__c();
        season.Name = '20Q1';
        season.TaxRate__c = 1.13;
        insert season;
        
        //----------------------------
        // 开始测试
        //----------------------------
        ApexPages.currentPage().getParameters().put('summaryId', summary.Id);
        RTV_Summary_SellingPrice ctrl = new RTV_Summary_SellingPrice();
        ctrl.cancel();
        
        Test.StartTest();
        try {
            ctrl.startBatch();
            System.debug(ctrl.loadingPercent);
        } finally {
            Test.StopTest();
            ctrl.checkResult();
        }
        
        //----------------------------
        // 由于测试类中不能创建BigObject
        // 所以单独测试各个方法
        //----------------------------
        RTV_Summary_SellingPrice_Batch batch = new RTV_Summary_SellingPrice_Batch(summary.Id, 0);
        batch.execute(null, new List<RTV_Order__c>{order});
        
        // case：折扣价格相同
        RTV_Summary_SellingPrice_Batch.OrderInfo info = new RTV_Summary_SellingPrice_Batch.OrderInfo(order);
        info.order = order;
        info.order.Sold_To__r = soldto;
        info.tradingTermList = new List<RMS_TradingTerm__c>{tradeTerm};
        info.sellingPriceSTMap.put('TestProduct19Q3' + soldto.Name, new List<RTV_SellingPrices__b>{
            new RTV_SellingPrices__b(
                Material_Code__c='TestProduct',
                Season_Code__c='19Q3',
                Sold_To_Code__c=soldto.Name,
                MSRP__c=123.45,
                Selling_Price__c=55.45
            )
        });
        info.orderItemMap.put(item, new List<String>{'19Q3','19Q4','20Q1','20Q2'});
        batch.isSellingPrice(info, item);
        batch.checkSellingPrice(info, '19Q3', item);
        
        // case：折扣价格不同
        info.sellingPriceSTMap.get('TestProduct19Q3' + soldto.Name).add(
            new RTV_SellingPrices__b(
                Material_Code__c='TestProduct',
                Season_Code__c='19Q3',
                Sold_To_Code__c=soldto.Name,
                MSRP__c=123.45,
                Selling_Price__c=60.45
            )
        );
        batch.checkSellingPrice(info, '19Q3', item);
        
        // case：价格为0
        info.sellingPriceSTMap.get('TestProduct19Q3' + soldto.Name)[0].MSRP__c = 0;
        try {
            batch.checkSellingPrice(info, '19Q3', item);
        } catch(Exception err) {}
    }
}