force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Sold_To__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联批发商Wholesale</description>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RMS Sold To</relationshipLabel>
    <relationshipName>RMS_Sold_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipLabel>RTV DEF Summary</relationshipLabel>
    <relationshipName>RTV_DEF_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/LF_WH_Inbound_Comment__c.field-meta.xml
<CustomField>
    <fullName>LF_WH_Inbound_Comment__c</fullName>
    <label>LF WH Inbound Comment</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Process Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code A)</description>
    <inlineHelpText>Inspection qty (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code B)</description>
    <inlineHelpText>Inspection qty (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code C)</description>
    <inlineHelpText>Inspection qty (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Inspection qty (Reason Code D)</description>
    <inlineHelpText>Inspection qty (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Sold_To__c.field-meta.xml
<CustomField>
    <fullName>Sold_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold-To</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <description>The first 2 characters of product&apos;s BU</description>
    <inlineHelpText>The first 2 characters of product&apos;s BU</inlineHelpText>
    <label>BU</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Season_Code_CN__c.field-meta.xml
<CustomField>
    <fullName>Season_Code_CN__c</fullName>
    <label>Season Code (CN)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Selling_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Unit_Price__c</fullName>
    <defaultValue>(0)</defaultValue>
    <label>Selling Unit Price (CNY/excl.VAT)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/SKU_Size_US__c.field-meta.xml
<CustomField>
    <fullName>SKU_Size_US__c</fullName>
    <description>Product US Size</description>
    <label>SKU Size (US)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>RMS_Account_Group__c</referenceTo>
    <relationshipName>Return_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_A__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_A__c</fullName>
    <description>Total Inspection QTY (Reason Code A)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code A)</inlineHelpText>
    <label>Inspect QTY A</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_B__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_B__c</fullName>
    <description>Total Inspection QTY (Reason Code B)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code B)</inlineHelpText>
    <label>Inspect QTY B</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_C__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_C__c</fullName>
    <description>Total Inspection QTY (Reason Code C)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code C)</inlineHelpText>
    <label>Inspect QTY C</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Inspect_QTY_D__c.field-meta.xml
<CustomField>
    <fullName>Inspect_QTY_D__c</fullName>
    <description>Total Inspection QTY (Reason Code D)</description>
    <inlineHelpText>Total Inspection QTY (Reason Code D)</inlineHelpText>
    <label>Inspect QTY D</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/LF_WH_Inbound_Comment__c.field-meta.xml
<CustomField>
    <fullName>LF_WH_Inbound_Comment__c</fullName>
    <description>LF仓库入库备注</description>
    <label>LF WH Inbound Comment</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RTV_DTC_Summary_Inbound.cls
@IsTest(isParallel=true)
public with sharing class Test_RTV_DTC_Summary_Inbound {
    @isTest
    public static void test() {
        // account group
        RMS_Account_Group__c acg = new RMS_Account_Group__c();
        acg.Name = '00)CC';
        insert acg;
        
        // soldto
        RMS_Sold_To__c soldto = new RMS_Sold_To__c();
        soldto.Name = 'xxxx';   
        soldto.Account_Group__c = acg.Id;
        insert soldto;
        
        // shipto
        RMS_Ship_To__c shipto = new RMS_Ship_To__c();
        shipto.Name = 'xxxxxxx';   
        shipto.Sold_To_Code__c = soldto.Id;
        insert shipto;
        
        // summary
        RTV_Summary__c summary = new RTV_Summary__c();
        summary.Account_Group__c = acg.Id;
        summary.Name = 'xxxx';
        insert summary;
        
        // order
        RTV_Order__c order = new RTV_Order__c();
        order.Return_Summary__c = summary.Id;
        order.Name = 'xxxxx';
        order.Sold_To__c = soldto.Id;
        order.Ship_To__c = shipto.Id;
        order.Status__c = 'Insp Confirmed';
        order.Inspect_QTY_C__c = 1;
        order.Inspect_QTY_D__c = 1;
        insert order;
        
        // item
        RTV_Order_Item__c item = new RTV_Order_Item__c();
        item.RTV_Order__c = order.Id;
        item.Material_Code__c = 'PDT000001';
        item.BU_2__c = 'AP';
        item.Season_Code_CN__c = '20Q1';
        item.SKU_Size_US__c = 'XL';
        item.Selling_Unit_Price__c = 123.45;
        item.Inspect_QTY_A__c = 1;
        item.Inspect_QTY_B__c = 1;
        item.Inspect_QTY_C__c = 1;
        item.Inspect_QTY_D__c = 2;
        insert item;
        
        // -----------------------------
        // 开始test
        // -----------------------------
        ApexPages.currentPage().getParameters().put('summaryId', summary.Id);
        RTV_DTC_Summary_Inbound ctrl = new RTV_DTC_Summary_Inbound();
        ctrl.getLoginUser();
        
        // loadPage
        ctrl.loadPage();
        ctrl.cancel();
        System.debug(ctrl.deliveryDate);
        System.debug(ctrl.contentDocumentId);
        
        // ----------------------------
        // lf inbound ABD
        // ----------------------------
        //无附件
        ctrl.inbound();
        
        // 无comment
        ctrl.summary.LF_WH_Inbound_Comment__c = 'xxxx';
        ctrl.inbound();
        
        // 上传空附件
        ctrl.upload();
        
        // 上传附件LF_WH
        ctrl.summary.LF_WH_Inbound_Date__c = null;
        ctrl.fileBody = Blob.valueOf('xxxxx');
        ctrl.fileName = 'xxxxxx';
        ctrl.upload();
        
        // 上传附件CS
        ctrl.summary.LF_WH_Inbound_Date__c = System.today();
        ctrl.summary.CS_Inbound_Date__c = null;
        ctrl.fileBody = Blob.valueOf('xxxxx');
        ctrl.fileName = 'xxxxxx';
        ctrl.upload();
        
        // 上传附件LFDELY
        ctrl.summary.LF_WH_Inbound_Date__c = System.today();
        ctrl.summary.CS_Inbound_Date__c = System.today();
        ctrl.fileBody = Blob.valueOf('xxxxx');
        ctrl.fileName = 'xxxxxx';
        ctrl.upload();
        
        // lf inbound ABD (recall)
        ctrl.summary.LF_WH_Inbound_Comment__c = 'xxxx';
        ctrl.summary.Attach_User__c = 'LFWH';
        ctrl.summary.Recall__c = true;
        ctrl.inbound();
        
        // lf inbound ABD: 没有defsummary
        order.To_DEF_Order__c = null;
        update order;
        ctrl.summary.Recall__c = false;
        ctrl.inbound();
        
        // lf inbound ABD: defSummary
        RTV_DEF_Summary__c defSummary = new RTV_DEF_Summary__c();
        defSummary.Account_Group__c = acg.Id;
        defSummary.Year__c = String.valueOf(System.today().year());
        defSummary.Month__c = System.today().month();
        defSummary.TakeBack_From_Date__c = System.today().addDays(-10);
        defSummary.Takeback_Till_Date__c = System.today().addDays(10);
        insert defSummary;
        
        // lf inbound ABD
        Test.startTest();
        try {
            order.To_DEF_Order__c = null;
            update order;
            
            ctrl.summary.Recall__c = false;
            ctrl.inbound();
            System.debug(ctrl.loadingPercent);
            System.debug(ctrl.isBatchLoading);
        } finally {
            Test.stopTest();
            ctrl.isBatchEnd();
        }
        
        // 删除附件
        try {
            ctrl.contentDocumentId = [SELECT Id FROM ContentDocument LIMIT 1][0].Id;
            ctrl.deleteAttach();
        } catch(Exception err) {}
    }
}