force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <label>DTC Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>DIG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Process Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>IF(Return_Summary__r.DTC_Type__c==&apos;CFS&apos;     || ISPICKVAL(RTV_DEF_Summary__r.DTC_Type__c, &apos;CFS&apos;), &apos;CFS&apos;,
IF(Return_Summary__r.DTC_Type__c==&apos;Digital&apos; || ISPICKVAL(RTV_DEF_Summary__r.DTC_Type__c, &apos;DIG&apos;), &apos;Digital&apos;,
&apos;&apos;))</formula>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_DEF_Summary__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV DEF Summary</label>
    <referenceTo>RTV_DEF_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Store_Code__c.field-meta.xml
<CustomField>
    <fullName>Store_Code__c</fullName>
    <formula>Ship_To__r.DTC_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Store Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/RTV_Program__c.object-meta.xml
<CustomObject>
    <description>Sales Return to Vendor Program</description>
    <label>RTV Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Program__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>IF(RecordType.Name == &apos;CFS DTC Takeback&apos; || RecordType.Name == &apos;CFS DTC Takeback Kick Off&apos;, &apos;CFS&apos;,
IF(RecordType.Name == &apos;Digital DTC Takeback&apos; || RecordType.Name == &apos;Digital DTC Takeback Kick Off&apos;, &apos;Digital&apos;,
&apos;&apos;))</formula>
    <inlineHelpText>DTC客户类型</inlineHelpText>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Program__c/fields/IsCFS__c.field-meta.xml
<CustomField>
    <fullName>IsCFS__c</fullName>
    <description>判断Program是否是CFS</description>
    <formula>IF(
  RecordType.Name = &apos;CFS DTC Takeback&apos; ||
  RecordType.Name = &apos;CFS DTC Takeback Kick Off&apos;,
  True,
  False
)</formula>
    <label>IsCFS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>RTV_Program__r.DTC_Type__c</formula>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/RTV_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup Return Program, when the order is create by BP.</description>
    <label>RTV Program</label>
    <referenceTo>RTV_Program__c</referenceTo>
    <relationshipLabel>RTV Summaries</relationshipLabel>
    <relationshipName>Return_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTV_Order_ReportAuthCode.cls
public with sharing class RTV_Order_ReportAuthCode {

    /** 参数summary */
    public final Id summaryId = ApexPages.currentPage().getParameters().get('summaryId');
    
    /** 参数summary */
    public final Id defSummaryId = ApexPages.currentPage().getParameters().get('defSummaryId');
    
    /** 参数 UTF8-BOM（确保excel打开csv不乱吗） */
    public static final String UTF8_BOM ='\uFEFF';

    public String getCsvString() {
        List<RTV_Order__c> orders;
        Boolean isCFS;
        
        // TB Summary
        if (summaryId != null) {
            RTV_Summary__c summary = [
                SELECT RTV_Program__r.IsCFS__c FROM RTV_Summary__c WHERE Id = :this.summaryId
            ];
            orders = [
                SELECT Name, Store_Code__c, Ship_To__r.Name FROM RTV_Order__c
                WHERE Return_Summary__c = :this.summaryId
                AND Status__c = 'Ready'
            ];
            isCFS = summary.RTV_Program__r.IsCFS__c;
        }
        // DEF Summary
        else if (defSummaryId != null) {
            RTV_DEF_Summary__c defSummary = [
                SELECT DTC_Type__c FROM RTV_DEF_Summary__c WHERE Id = :this.defSummaryId
            ];
            orders = [
                SELECT Name, Store_Code__c, Ship_To__r.Name FROM RTV_Order__c
                WHERE RTV_DEF_Summary__c = :this.defSummaryId
                AND Status__c = 'Ready'
            ];
            isCFS = defSummary.DTC_Type__c == 'CFS';
        }
        
        // 标题
        String[] rows = new String[0];
        String[] herder = new String[0];
        herder.add('授权码');
        herder.add('授权码(AP)');
        herder.add('授权码(AC)');
        herder.add('授权码(FW)');
        if(isCFS){
            herder.add('store id');
        }
        else {
            herder.add('ship to');
        }
        rows.add(String.join(herder, ','));
        
        // 明细
        for (RTV_Order__c obj : orders) {
            String[] line = new String[0];
            line.add(obj.Name);
            line.add(obj.Name + 'AP');
            line.add(obj.Name + 'AC');
            line.add(obj.Name + 'FW');
            if(isCFS){
                line.add(obj.Store_Code__c);
            }
            else {
                line.add(obj.Ship_To__r.Name);
            }
            rows.add(String.join(line, ','));
        }

        return UTF8_BOM + String.join(rows,'\n');
    }
}