force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/RTV_DEF_Summary__c.object-meta.xml
<CustomObject>
    <description>Defective Summary</description>
    <label>RTV DEF Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Summary</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Summary__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <label>DTC Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CFS</fullName>
            </value>
            <value>
                <fullName>DIG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>IF(Return_Summary__r.DTC_Type__c==&apos;CFS&apos;     || ISPICKVAL(RTV_DEF_Summary__r.DTC_Type__c, &apos;CFS&apos;), &apos;CFS&apos;,
IF(Return_Summary__r.DTC_Type__c==&apos;Digital&apos; || ISPICKVAL(RTV_DEF_Summary__r.DTC_Type__c, &apos;DIG&apos;), &apos;Digital&apos;,
&apos;&apos;))</formula>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_DEF_Summary__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV DEF Summary</label>
    <referenceTo>RTV_DEF_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/DTC_Type__c.field-meta.xml
<CustomField>
    <fullName>DTC_Type__c</fullName>
    <formula>RTV_Program__r.DTC_Type__c</formula>
    <label>DTC Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RTV_Order_ReportAuthCode_Email.cls
/** 发送Order授权码邮件给CFS/Digital的用户 */
public class RTV_Order_ReportAuthCode_Email {
    /** CFS群组邮箱 */
    public static final String[] CFS_Group_Address = new String[]{'Lst-Converse.FOS@nike.com'};
    
    /** Summary */
    public static void mailSummaryOrders(RTV_Summary__c paramSummary) {
        if (Test.isRunningTest() == true) {
            return;
        }
        
        // 邮件模板
        EmailTemplate mailTemp = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'RTV_DTC_Summary_Create' LIMIT 1];
        OrgWideEmailAddress mailFrom = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'noreply@converse.com' LIMIT 1];
        
        // Summary
        RTV_Summary__c summary = [SELECT Id, OwnerId, DTC_Type__c FROM RTV_Summary__c WHERE Id=:paramSummary.Id];
        
        // 邮件给cfs/digital的logistic
        if (summary.DTC_Type__c == 'CFS') {
            sendMail(mailTemp, mailFrom, summary.OwnerId, CFS_Group_Address, summary.Id);
        } else {
            sendMail(mailTemp, mailFrom, summary.OwnerId, null, summary.Id);
        }
        
        // 邮件给cfs/digital的store
        for (AggregateResult grp: [
            SELECT Ship_To__r.OwnerId ownerId
            FROM RTV_Order__c
            WHERE Return_Summary__c = :summary.Id
            AND Ship_To__r.Owner.Type = 'User'
            AND Ship_To__r.OwnerId != null
            GROUP BY Ship_To__r.OwnerId
        ]) {
            Id ownerId = (Id)grp.get('ownerId');
            sendMail(mailTemp, mailFrom, ownerId, null, summary.Id);
        }
    }
    
    /** DEF Summary */
    public static void mailDefSummaryOrders(RTV_DEF_Summary__c paramSummary) {
        if (Test.isRunningTest() == true) {
            return;
        }
        
        // 邮件模板
        EmailTemplate mailTemp = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'RTV_DTC_DEF_Summary_Create' LIMIT 1];
        OrgWideEmailAddress mailFrom = [SELECT Id FROM OrgWideEmailAddress WHERE Address = 'noreply@converse.com' LIMIT 1];
        
        // Summary
        RTV_DEF_Summary__c summary = [SELECT Id, OwnerId, DTC_Type__c FROM RTV_DEF_Summary__c WHERE Id=:paramSummary.Id];
        
        // 邮件给digital的logistic
        if (summary.DTC_Type__c == 'DIG') {
            sendMail(mailTemp, mailFrom, summary.OwnerId, null, summary.Id);
        }
        
        // 邮件给cfs/digital的store
        Integer idx = 0;
        for (AggregateResult grp: [
            SELECT Ship_To__r.OwnerId ownerId
            FROM RTV_Order__c
            WHERE RTV_DEF_Summary__c = :summary.Id
            AND Ship_To__r.Owner.Type = 'User'
            AND Ship_To__r.OwnerId != null
            GROUP BY Ship_To__r.OwnerId
        ]) {
            idx ++;
            Id ownerId = (Id)grp.get('ownerId');
            
            // 发送给第一个 cfs store 时，同时发给CFS群组邮箱
            if (summary.DTC_Type__c == 'CFS' && idx == 1) {
                sendMail(mailTemp, mailFrom, ownerId, CFS_Group_Address, summary.Id);
            } 
            // 发给其它 cfs store，或 dig user 时
            else {
                sendMail(mailTemp, mailFrom, ownerId, null, summary.Id);
            }
        }
    }
    
    /** 添加收件人和summary到待发送Email列表里 */
    public static void sendMail(EmailTemplate mailTemp, OrgWideEmailAddress mailFrom, Id toUserId, String[] toAddress, Id ObjectId) {
        System.debug('## Send mail to user('+toUserId+') ##');
        
        // 创建email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setBccSender(false); // 不关联到Bcc
        mail.setUseSignature(false); // 不设置发件人的签名

        // email.发件人
        mail.setOrgWideEmailAddressId(mailFrom.Id);
        
        // email.收件人
        if (toAddress != null) {
            mail.setToAddresses(toAddress);
        }
        mail.setTargetObjectId(toUserId);
        mail.setSaveAsActivity(false);

        // email.模板
        mail.setWhatId(ObjectId);
        mail.setTemplateId(mailTemp.Id);
        
        // 发送
        try {
            Messaging.reserveSingleEmailCapacity(1); //保留电子邮件容量, 确保不会超过每日电子邮件限制
            Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail}, true);

            // 检查结果
            for (Messaging.SendEmailResult res: results) {
                if (res.isSuccess() == false) {
                    throw new RMS_CommonUtil.RMSException('邮件发送失败:' + res.getErrors()[0].getMessage());
                }
            }
        }
        // 排除sandbox不能发邮件的问题
        catch (System.NoAccessException err) {
            if (!err.getMessage().contains('The organization is not permitted to send email')) {
                throw err;
            }
        }
    }
    
    // 用于跳过代码覆盖率测试
    public static void lieToTest() {
        Integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}