force-app/main/default/objects/RMS_Ship_To__c/RMS_Ship_To__c.object-meta.xml
<CustomObject>
    <description>批发商下，销售对象的仓库</description>
    <label>RMS Ship To</label>
    <nameField>
        <label>Ship To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Ship To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RMS_Ship_To__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City</description>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <description>Province</description>
    <label>Province</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RMS_Ship_To__c/fields/Sold_To_Code__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Code__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>关联Sold-to</description>
    <label>Sold To Code</label>
    <referenceTo>RMS_Sold_To__c</referenceTo>
    <relationshipLabel>RMS Ship To List</relationshipLabel>
    <relationshipName>RMS_Ship_To_List</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RMS_Sold_To__c/RMS_Sold_To__c.object-meta.xml
<CustomObject>
    <description>批发商下的经销商，即RMS的客户</description>
    <label>RMS Sold To</label>
    <nameField>
        <label>Sold To Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RMS Sold To List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_LF_Order__c/RTV_LF_Order__c.object-meta.xml
<CustomObject>
    <label>RTV LF Order</label>
    <nameField>
        <label>LF Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV LF Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_LF_Order__c/fields/Application_Box_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_Box_QTY__c</fullName>
    <description>申请箱数</description>
    <label>Application Box QTY</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/BU_2__c.field-meta.xml
<CustomField>
    <fullName>BU_2__c</fullName>
    <label>BU-2</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/LF_Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>LF_Order_Auth_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LF Order Auth Code</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV LF Orders</relationshipLabel>
    <relationshipName>RTV_LF_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Earliest_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Delivery_Date__c</fullName>
    <description>最早提货日期</description>
    <label>Earliest Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Auth_Code__c</fullName>
    <externalId>true</externalId>
    <label>Order Auth Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>关联Ship-to</description>
    <label>Ship-To</label>
    <referenceTo>RMS_Ship_To__c</referenceTo>
    <relationshipName>Return_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Address__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Address__c</fullName>
    <inlineHelpText>Please check if the address is right. 
If wrong, please correct it.</inlineHelpText>
    <label>Ship-To Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Contact__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Contact__c</fullName>
    <label>Ship-To Contact</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone1__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone1__c</fullName>
    <label>Ship-To Phone1</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Ship_To_Phone2__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Phone2__c</fullName>
    <label>Ship-To Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTV_Order_ReportDeliveryAuth.cls
public class RTV_Order_ReportDeliveryAuth {
    
    /** url参数: summaryId */
    public String summaryId = ApexPages.currentPage().getParameters().get('summaryId');
    
    /** url参数: orderId */
    public String orderId = ApexPages.currentPage().getParameters().get('orderId');
    
    public static String empty {get{return '';}}
    
    /** 导出结果 */
    public List<RTV_LF_Order__c> results {get; set;}
    
    /** 系统日期 */
    public String SysDateStr { get{
        return System.Date.today().format();
    }}
    
    /** 构造方法 */
    public RTV_Order_ReportDeliveryAuth() {
        // 下载整个sumamry的内容
        if (this.summaryId != null) {
            this.results = [
                SELECT BU_2__c, Application_Box_QTY__c, 
                    Application_QTY__c, 
                    LF_Order_Auth_Code__c,
                    RTV_Order__r.Order_Auth_Code__c, 
                    RTV_Order__r.Earliest_Delivery_Date__c, 
                    RTV_Order__r.Ship_To__r.Sold_To_Code__r.Sold_To_Name_CN__c, 
                    RTV_Order__r.Ship_To__r.Province__c, 
                    RTV_Order__r.Ship_To__r.City__c, 
                    RTV_Order__r.Ship_To_Contact__c, 
                    RTV_Order__r.Ship_To_Phone1__c, 
                    RTV_Order__r.Ship_To_Phone2__c, 
                    RTV_Order__r.Ship_To_Address__c, 
                    RTV_Order__r.Ship_To__r.Sold_To_Code__r.Name, 
                    RTV_Order__r.Ship_To__r.Name
                FROM RTV_LF_Order__c
                WHERE RTV_Order__r.Return_Summary__c = :this.summaryId
                AND RTV_Order__r.Status__c = 'POST to LF'
            ];
        }
        // 下载单个order的内容
        else if (this.orderId != null) {
            this.results = [
                SELECT BU_2__c, Application_Box_QTY__c,
                    Application_QTY__c, 
                    LF_Order_Auth_Code__c,
                    RTV_Order__r.Order_Auth_Code__c, 
                    RTV_Order__r.Earliest_Delivery_Date__c, 
                    RTV_Order__r.Ship_To__r.Sold_To_Code__r.Sold_To_Name_CN__c, 
                    RTV_Order__r.Ship_To__r.Province__c, 
                    RTV_Order__r.Ship_To__r.City__c, 
                    RTV_Order__r.Ship_To_Address__c, 
                    RTV_Order__r.Ship_To_Contact__c, 
                    RTV_Order__r.Ship_To_Phone1__c, 
                    RTV_Order__r.Ship_To_Phone2__c, 
                    RTV_Order__r.Ship_To__r.Sold_To_Code__r.Name, 
                    RTV_Order__r.Ship_To__r.Name
                FROM RTV_LF_Order__c
                WHERE RTV_Order__c = :this.orderId
                AND RTV_Order__r.Status__c = 'POST to LF'
            ];
        }
    }
}