force-app/main/default/objects/RTV_BaoZun_Seeding__c/RTV_BaoZun_Seeding__c.object-meta.xml
<CustomObject>
    <label>RTV Baozun Seeding</label>
    <nameField>
        <label>RTV BaoZun Seeding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Baozun Seeding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Baozun_Seeding__c.field-meta.xml
<CustomField>
    <fullName>RTV_Baozun_Seeding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Baozun Seeding</label>
    <referenceTo>RTV_BaoZun_Seeding__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/recordTypes/RTV_Baozun_Order_Inbound.recordType-meta.xml
<RecordType>
    <fullName>RTV_Baozun_Order_Inbound</fullName>
    <active>true</active>
    <label>RTV Baozun Order Inbound</label>
</RecordType>

force-app/main/default/classes/Test_RTV_Baozun_Order_Inbound.cls
@IsTest(isParallel=true)
public class Test_RTV_Baozun_Order_Inbound {
    @isTest
    public static void test() {
        RTV_Baozun_Seeding__c baozun = new RTV_Baozun_Seeding__c();
        baozun.Year__c = 2021;
        baozun.Month__c = 1;
        insert baozun;
        
        RTV_Order__c order = new RTV_Order__c();
        order.Name = 'xxx';
        order.RTV_Baozun_Seeding__c = baozun.Id;
        insert order;
        
        ApexPages.currentPage().getParameters().put('id', order.Id);
        RTV_Baozun_Order_Inbound ctrl = new RTV_Baozun_Order_Inbound();
        ctrl.cancel();
        
        ctrl.upload();
        ctrl.fileBody = Blob.valueOf('xxxxxxxxxxxxx');
        ctrl.fileName = 'xxxx';
        try {ctrl.upload();} catch(Exception err) {}
        
        ctrl.inbound();
    }
}