force-app/main/default/objects/RTV_BaoZun_Seeding__c/RTV_BaoZun_Seeding__c.object-meta.xml
<CustomObject>
    <label>RTV Baozun Seeding</label>
    <nameField>
        <label>RTV BaoZun Seeding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Baozun Seeding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_BaoZun_Seeding__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Trigger_RMS_Baozun_Seeding.cls
@IsTest(isParallel=true)
public class Test_Trigger_RMS_Baozun_Seeding {
    @isTest
    public static void test() {
        RTV_Baozun_Seeding__c seeding1 = new RTV_Baozun_Seeding__c();
        seeding1.Year__c = 2021;
        seeding1.Month__c = 5;
        insert seeding1;

        RTV_Baozun_Seeding__c seeding2 = new RTV_Baozun_Seeding__c();
        seeding2.Year__c = 2021;
        seeding2.Month__c = 6;
        insert seeding2;

        seeding1.Status__c = 'In Process';
        update seeding1;

    }
}