force-app/main/default/objects/RTV_BaoZun_Seeding__c/RTV_BaoZun_Seeding__c.object-meta.xml
<CustomObject>
    <label>RTV Baozun Seeding</label>
    <nameField>
        <label>RTV BaoZun Seeding Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Baozun Seeding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_BaoZun_Seeding__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Application_QTY__c.field-meta.xml
<CustomField>
    <fullName>Application_QTY__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total qty of customer applications</description>
    <inlineHelpText>Total qty of customer applications</inlineHelpText>
    <label>Application QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Baozun_Seeding__c.field-meta.xml
<CustomField>
    <fullName>RTV_Baozun_Seeding__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Baozun Seeding</label>
    <referenceTo>RTV_BaoZun_Seeding__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Seeding_Status__c.field-meta.xml
<CustomField>
    <fullName>Seeding_Status__c</fullName>
    <label>Seeding Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST to LF</fullName>
                <default>true</default>
                <label>POST to LF</label>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/recordTypes/RTV_Baozun_Order_Inbound.recordType-meta.xml
<RecordType>
    <fullName>RTV_Baozun_Order_Inbound</fullName>
    <active>true</active>
    <label>RTV Baozun Order Inbound</label>
</RecordType>

force-app/main/default/classes/RTV_Baozun_Order_Inbound.cls
public with sharing class RTV_Baozun_Order_Inbound {
    //order id
    public final String orderId = ApexPages.currentPage().getParameters().get('id');
    //order
    public RTV_Order__c order{get; set;}
    //控制inbound按钮
    public Boolean isInbound{get; set;}

    //文件内容
    public transient Blob fileBody{get;set;}
    //文件名
    public String fileName{get;set;}

    //附件
    private Attachment attach;

    public RTV_Baozun_Order_Inbound()
    {
        this.order = [SELECT ID,Name,Application_QTY__c,RTV_Baozun_Seeding__r.Name FROM RTV_Order__c WHERE ID =:this.orderId];

        this.isInbound = true;
    }

    /**
     * 关闭页面
     */
    public Pagereference cancel()
    {
        PageReference returnPage = new PageReference('/' + this.orderId);
        returnPage.setRedirect(true);
        return returnPage;  
    }
    /**
     * 入库方法
     */
    public void inbound()
    {
        RTV_Order__c newOrder = new RTV_Order__c();
        newOrder.id = this.orderId;
        newOrder.Status__c = 'Inbound';
        newOrder.Seeding_Status__c = 'Inbound';
        update newOrder;

        this.isInbound = false;

        RMS_CommonUtil.pageAddMessage(ApexPages.severity.CONFIRM, '入库成功');
    }
    /**
     * 上传附件
     */
    public void upload()
    {
        // 检查input
        if (fileBody == null) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, '请选择上传文件'));
            return;
        }
        attach = new Attachment();
        attach.parentid = this.order.id;
        attach.body = this.fileBody;
        attach.name = this.fileName;
        insert attach;

        RMS_CommonUtil.pageAddMessage(ApexPages.severity.CONFIRM, '附件上传成功');
    }
}