force-app/main/default/objects/RTV_Defective__c/RTV_Defective__c.object-meta.xml
<CustomObject>
    <label>RTV DEF Program</label>
    <nameField>
        <label>Defective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Defective__c.field-meta.xml
<CustomField>
    <fullName>RTV_Defective__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV Defective(AC/AP)</label>
    <referenceTo>RTV_Defective__c</referenceTo>
    <relationshipLabel>RTV Orders(AC/AP)</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Defective_FW__c.field-meta.xml
<CustomField>
    <fullName>RTV_Defective_FW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Defective(FW)</label>
    <referenceTo>RTV_Defective__c</referenceTo>
    <relationshipLabel>RTV Orders(FW)</relationshipLabel>
    <relationshipName>RTV_Orders_FTW</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/FOB_CNY__c.field-meta.xml
<CustomField>
    <fullName>FOB_CNY__c</fullName>
    <label>FOB(CNY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/FOB_USD__c.field-meta.xml
<CustomField>
    <fullName>FOB_USD__c</fullName>
    <label>FOB(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RTV_Order_UploadFOB.cls
public with sharing class RTV_Order_UploadFOB {
    /** 参数summary */
    public final Id defId = ApexPages.currentPage().getParameters().get('Id');
    
    /** 上传的csv文件正文 */
    public transient Blob fileUploadBody {get; set;}
    public String fileUploadName {get; set;}
    
    /** 文件编码 */
    public List<ApexPages.SelectOption> fileCharsetOpts {get{return RMS_CSV_Iterator.CHARSET_OPTIONS;}}
    public String fileCharset = fileCharsetOpts.get(0).getValue();
    public String getFileCharset() {return fileCharset;}
    public void setFileCharset(String value) {this.fileCharset=value;}

    /** csv的必须列 */
    private static String[] Csv_Fields = new String[]{
        'Defective Name', 'Finance Code', 'Start Date', 'End Date', 'Order Code', 'Status', 'Item Code', 'FOB(CNY)', 'FOB(USD)'};

    // 已经存在OrderItem列表
    private Map<String,RTV_Order_Item__c> orderItemMap;
    // 更新OrderItem列表
    private List<RTV_Order_Item__c> updateOrderItem;

    /** 上传 */
    public void upload()
    {
        this.orderItemMap = new Map<String,RTV_Order_Item__c>();
        this.updateOrderItem = new List<RTV_Order_Item__c>();

        // 检查input
        if (this.fileUploadBody == null) {
            RMS_CommonUtil.pageAddMessage(ApexPages.severity.ERROR, '请选择上传文件！');
            return;
        }

        Savepoint savePot = Database.setSavepoint();
        try {
            this.doUpload();
        } 
        // 捕捉dml错误 (包括自定义的validate rule)
        catch(Exception err) {
            RMS_CommonUtil.pageAddMessage(ApexPages.severity.ERROR, err.getMessage());
            Database.rollback(savePot);
        }
    }

    /** 执行上传方法 */
    public void doUpload()
    {
        // 创建csv迭代器
        RMS_CSV_Iterator csvIter = new RMS_CSV_Iterator(this.fileUploadBody, this.fileCharset);
        csvIter.skipTitleLineIgnoreCase(Csv_Fields);
        
        // 检索order前，先遍历一次csv缩小检索范围
        List<RMS_CSV_Iterator.OneLineInfo> csvTable = new List<RMS_CSV_Iterator.OneLineInfo>();
        Set<String> itemCode = new Set<String>();
        while (csvIter.next()) {
            RMS_CSV_Iterator.OneLineInfo tr = csvIter.getOneLineInfo();
            
            // 记录该行内容
            csvTable.add(tr);
            itemCode.add(tr.get('Item Code'));
        }

        this.queryOrderItem(itemCode);

        // 遍历csv
        for (RMS_CSV_Iterator.OneLineInfo tr: csvTable) {
            // 更新order Item
            updateOrderItem(tr);
        }

        if(this.updateOrderItem.size()>0)
        {
            update updateOrderItem;

            RMS_CommonUtil.pageAddMessage(ApexPages.severity.CONFIRM, '更新成功！');
        }
        else {
            RMS_CommonUtil.pageAddMessage(ApexPages.severity.CONFIRM, '无相关信息！');
        }
    }

    /** 检索Order Item */
    public void queryOrderItem(Set<String> itemCode)
    {
        for(RTV_Order_Item__c item:[SELECT ID,Name,FOB_CNY__c,FOB_USD__c ,RTV_Order__R.Name
                                    FROM RTV_Order_Item__c 
                                    WHERE RTV_Order__R.RTV_Defective__c =:this.defId 
                                    OR RTV_Order__R.RTV_Defective_FW__c =:this.defId])
        {
            this.orderItemMap.put(item.RTV_Order__R.Name+item.name,item);
        }
    }

    /** 更新OrderItem */
    public void updateOrderItem(RMS_CSV_Iterator.OneLineInfo tr)
    {
        RTV_Order_Item__c item = this.orderItemMap.get(tr.get('Order Code')+tr.get('Item Code'));
        if(item != null)
        {
            item.FOB_CNY__c = Integer.valueOf(tr.get('FOB(CNY)'));
            item.FOB_USD__c = Integer.valueOf(tr.get('FOB(USD)'));
            updateOrderItem.add(item);
        }
    }

    /** 返回上一页 */
    public PageReference cancel() {
        PageReference returnPage = new PageReference('/' + this.defId);
        returnPage.setRedirect(true);
        return returnPage;
    }
}