force-app/main/default/objects/RTV_Defective__c/RTV_Defective__c.object-meta.xml
<CustomObject>
    <label>RTV DEF Program</label>
    <nameField>
        <label>Defective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Defective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;Pending&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Off Policy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCAPP</fullName>
            </value>
            <value>
                <fullName>FTW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Defective__c.field-meta.xml
<CustomField>
    <fullName>RTV_Defective__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>RTV Defective(AC/AP)</label>
    <referenceTo>RTV_Defective__c</referenceTo>
    <relationshipLabel>RTV Orders(AC/AP)</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/RTV_Defective_FW__c.field-meta.xml
<CustomField>
    <fullName>RTV_Defective_FW__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RTV Defective(FW)</label>
    <referenceTo>RTV_Defective__c</referenceTo>
    <relationshipLabel>RTV Orders(FW)</relationshipLabel>
    <relationshipName>RTV_Orders_FTW</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/RTV_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Order Item for one SKU</description>
    <label>RTV Order Item</label>
    <nameField>
        <label>Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order_Item__c/fields/FOB_CNY__c.field-meta.xml
<CustomField>
    <fullName>FOB_CNY__c</fullName>
    <label>FOB(CNY)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/FOB_USD__c.field-meta.xml
<CustomField>
    <fullName>FOB_USD__c</fullName>
    <label>FOB(USD)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/Material_Code__c.field-meta.xml
<CustomField>
    <fullName>Material_Code__c</fullName>
    <label>Material Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Order_Item__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <description>lookup master object: RTV Order</description>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV Order Items</relationshipLabel>
    <relationshipName>RTV_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Test_RTV_Order_UploadFOB.cls
@IsTest(isParallel=true)
public with sharing class Test_RTV_Order_UploadFOB {
    @isTest
    public static void test() {
        RTV_Defective__c def = new RTV_Defective__c();
        def.name = 'def';
        def.Type__c = 'FTW';
        def.Start_Date__c = Date.today();
        def.End_Date__c = Date.today().addDays(30);
        insert def;

        RTV_Order__c order = new RTV_Order__c();
        order.RTV_Defective_FW__c =def.ID;
        order.Status__c = 'Ready';
        order.Name = RMS_CommonUtil.order_getCode('xxx', '01)xx', 'xxx');
        insert order;

        RTV_Order_Item__c item = new RTV_Order_Item__c();
        item.RTV_Order__c = order.id;
        item.Material_Code__c = '111111';
        item.FOB_CNY__c = 100;
        item.FOB_USD__c = 100;
        item.name = 'item1111';
        insert item;

        RTV_Order_UploadFOB ctrl = new RTV_Order_UploadFOB();
        ctrl.upload();
        ctrl.fileUploadBody = Blob.valueof(
            '\r' +
            'Defective Name,Finance Code,Start Date,End Date,Order Code,Status,Item Code,FOB(CNY),FOB(USD)\r' + 
            def.name + ',1100,'+def.Start_Date__c+','+def.End_Date__c+','+order.Name+','+Order.Status__c+','+
            item.name+',200,200'+'\r'
        );
        ctrl.fileUploadName = 'xxxx';
        ctrl.getFileCharset();
        ctrl.setFileCharset('UTF-8');
        ctrl.upload();
        ctrl.cancel();
        
        ApexPages.currentPage().getParameters().put('id', def.Id);
        RTV_Order_UploadFOB ctrl2 = new RTV_Order_UploadFOB();
        ctrl2.cancel();

    }
}