force-app/main/default/objects/RTV_LF_Order__c/RTV_LF_Order__c.object-meta.xml
<CustomObject>
    <label>RTV LF Order</label>
    <nameField>
        <label>LF Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV LF Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_LF_Order__c/fields/LF_Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>LF_Order_Auth_Code__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>LF Order Auth Code</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_LF_Order__c/fields/RTV_Order__c.field-meta.xml
<CustomField>
    <fullName>RTV_Order__c</fullName>
    <label>RTV Order</label>
    <referenceTo>RTV_Order__c</referenceTo>
    <relationshipLabel>RTV LF Orders</relationshipLabel>
    <relationshipName>RTV_LF_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/RTV_Order__c.object-meta.xml
<CustomObject>
    <description>Return Order record for one Sold-to &amp; Ship-to</description>
    <label>RTV Order</label>
    <nameField>
        <label>Order Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Order__c/fields/Order_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Auth_Code__c</fullName>
    <externalId>true</externalId>
    <label>Order Auth Code</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Return_Summary__c.field-meta.xml
<CustomField>
    <fullName>Return_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>As the detail of return summary</description>
    <label>Return Summary</label>
    <referenceTo>RTV_Summary__c</referenceTo>
    <relationshipLabel>RTV Orders</relationshipLabel>
    <relationshipName>RTV_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTV_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Detail Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
            <value>
                <fullName>POST to LF</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Inspected</fullName>
            </value>
            <value>
                <fullName>Insp Wait Approval</fullName>
            </value>
            <value>
                <fullName>Insp Confirmed</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTV_Summary__c/RTV_Summary__c.object-meta.xml
<CustomObject>
    <description>Return order summary for one wholesale</description>
    <label>RTV Summary</label>
    <nameField>
        <label>Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Summary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Order Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Remove</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>POST to LF</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RTV_DeliveryPDF_Export.cls
@IsTest(isParallel=true)
public class Test_RTV_DeliveryPDF_Export {
    @IsTest
    private static void test() {
        RTV_Summary__c summary = new RTV_Summary__c();
        insert summary;
        
        RTV_Order__c order = new RTV_Order__c();
        order.Return_Summary__c = summary.Id;
        order.Status__c = 'POST to LF';
        insert order;
        
        RTV_LF_Order__c lfOrder = new RTV_LF_Order__c();
        lfOrder.LF_Order_Auth_Code__c = RMS_CommonUtil.order_getLFCode(order.Order_Auth_Code__c, 'FW');
        lfOrder.RTV_Order__c = order.Id;
        insert lfOrder;
        
        ApexPages.currentPage().getParameters().put('summaryId', summary.Id);
        RTV_DeliveryPDF_Export ctrl = new RTV_DeliveryPDF_Export();
        
        ctrl.updateHaveReadDelivery();
        ctrl.test();
        System.debug(ctrl.orders);
        System.debug(ctrl.printType);
    }
}