force-app/main/default/objects/RTV_DEF_Expected_Result__c/RTV_DEF_Expected_Result__c.object-meta.xml
<CustomObject>
    <label>RTV DEF Expected Result</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>RTV DEF Expected Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV DEF Expected Result</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Action_after_return__c.field-meta.xml
<CustomField>
    <fullName>Action_after_return__c</fullName>
    <label>Action after return</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Estimated_claim_from_factory__c.field-meta.xml
<CustomField>
    <fullName>Estimated_claim_from_factory__c</fullName>
    <label>Estimated claim from factory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Landing_Cost__c.field-meta.xml
<CustomField>
    <fullName>Landing_Cost__c</fullName>
    <description>Landing Cost(FOB+Freight/Duty)</description>
    <inlineHelpText>FOB+Freight/Duty</inlineHelpText>
    <label>Landing Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/No_of_Target_return_SKU__c.field-meta.xml
<CustomField>
    <fullName>No_of_Target_return_SKU__c</fullName>
    <label>No. of Target return SKU#</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Original_Wholesale_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Wholesale_Price__c</fullName>
    <description>Original Wholesale Price(After Discount)</description>
    <inlineHelpText>After Discount</inlineHelpText>
    <label>Original Wholesale Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/P_L_Impact__c.field-meta.xml
<CustomField>
    <fullName>P_L_Impact__c</fullName>
    <label>P/L Impact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Return_Product_Descripton__c.field-meta.xml
<CustomField>
    <fullName>Return_Product_Descripton__c</fullName>
    <label>Return Product Descripton</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Return_Product_offer_season__c.field-meta.xml
<CustomField>
    <fullName>Return_Product_offer_season__c</fullName>
    <label>Return Product offer season</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/RTV_DEF_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Program__c</fullName>
    <label>RTV DEF Program</label>
    <referenceTo>RTV_Defective__c</referenceTo>
    <relationshipLabel>RTV DEF Expected Result</relationshipLabel>
    <relationshipName>RTV_DEF_Expected_Result</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <label>Total Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/RTV_Defective__c.object-meta.xml
<CustomObject>
    <label>RTV DEF Program</label>
    <nameField>
        <label>Defective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Defective__c/fields/Actual_Amount__c.field-meta.xml
<CustomField>
    <fullName>Actual_Amount__c</fullName>
    <label>Actual Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Background__c.field-meta.xml
<CustomField>
    <fullName>Background__c</fullName>
    <defaultValue>(&quot;defective goods,custom returned them to Converse as per policy&quot;)</defaultValue>
    <label>Background</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Budget_Amount__c.field-meta.xml
<CustomField>
    <fullName>Budget_Amount__c</fullName>
    <label>Budget Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>(&quot;CNY&quot;)</defaultValue>
    <label>Currency</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Defective_Auth_Code__c.field-meta.xml
<CustomField>
    <fullName>Defective_Auth_Code__c</fullName>
    <label>Finance Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Program_mechanism__c.field-meta.xml
<CustomField>
    <fullName>Program_mechanism__c</fullName>
    <label>Program mechanism</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Program_Objective__c.field-meta.xml
<CustomField>
    <fullName>Program_Objective__c</fullName>
    <label>Program Objective</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Program_Rate__c.field-meta.xml
<CustomField>
    <fullName>Program_Rate__c</fullName>
    <label>Program Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/fields/Requested_by__c.field-meta.xml
<CustomField>
    <fullName>Requested_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RTV_DEF_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTV_DEF_OffPolicy_Export.cls
public inherited sharing class RTV_DEF_OffPolicy_Export {
    public RTV_Defective__c program {get; set;}
    public String programId = ApexPages.currentPage().getParameters().get('id');
    public List<RTV_DEF_Expected_Result__c> listlines {get; set;}
    public RTV_DEF_Expected_Result__c expect1 {get; set;}
    public RTV_DEF_Expected_Result__c expect2 {get; set;}
    public RTV_DEF_Expected_Result__c expect3 {get; set;}
    public RTV_DEF_Expected_Result__c expect4 {get; set;}
    public RTV_DEF_Expected_Result__c expect5 {get; set;}
    
    public RTV_DEF_OffPolicy_Export() {
        this.program = [
            SELECT Id, 
            Name,Start_Date__c,End_Date__c,Budget_Amount__c,Program_Rate__c,Requested_by__r.Name,CreatedDate,Defective_Auth_Code__c,Actual_Amount__c,
            Currency__c,Job_Title__c,Department__c,
            Program_Objective__c,Background__c,Program_mechanism__c
            FROM RTV_Defective__c
            WHERE Id = :this.programId limit 1
        ];

        this.listlines = [
                SELECT Return_Product_Descripton__c,No_of_Target_return_SKU__c,Return_Product_offer_season__c,Total_Units__c,Original_Wholesale_Price__c,
                Landing_Cost__c,P_L_Impact__c,Estimated_claim_from_factory__c,Action_after_return__c
                FROM RTV_DEF_Expected_Result__c
                WHERE RTV_DEF_Program__c = :this.programId
        ];
        Integer size = this.listlines.size();

        RTV_DEF_Expected_Result__c total = new RTV_DEF_Expected_Result__c();
        total.Return_Product_Descripton__c = 'TTL';
        total.Total_Units__c = 0;
        total.Original_Wholesale_Price__c = 0;
        total.Landing_Cost__c = 0;
        total.P_L_Impact__c = 0;
        total.Estimated_claim_from_factory__c = 0;
        for( RTV_DEF_Expected_Result__c item:this.listlines){
            if(item.Total_Units__c!=null){
                total.Total_Units__c += item.Total_Units__c;
            }
            if(item.Original_Wholesale_Price__c!=null){
                total.Original_Wholesale_Price__c += item.Original_Wholesale_Price__c;
            }
            if(item.Landing_Cost__c!=null){
                total.Landing_Cost__c += item.Landing_Cost__c;
            }
            if(item.P_L_Impact__c!=null){
                total.P_L_Impact__c += item.P_L_Impact__c;
            }
            if(item.Estimated_claim_from_factory__c!=null){
                total.Estimated_claim_from_factory__c += item.Estimated_claim_from_factory__c;
            }   
        }

        if(size>0){
            this.expect1 = this.listlines.get(0);
        }else {
            this.expect1 = new RTV_DEF_Expected_Result__c();
        }
        if(size>1){
            this.expect2 = this.listlines.get(1);
        }else{
            this.expect2 = new RTV_DEF_Expected_Result__c();
            if(size==1){
                this.expect2=total;
            }
        }
        if(size>2){
            this.expect3 = this.listlines.get(2);
        }else{
            this.expect3 = new RTV_DEF_Expected_Result__c();
            if(size==2){
                this.expect3=total;
            }
        }
        if(size>3){
            this.expect4 = this.listlines.get(3);
        }else{
            this.expect4 = new RTV_DEF_Expected_Result__c();
            if(size==3){
                this.expect4=total;
            }
        }
        if(size>4){
            this.expect5 = this.listlines.get(4);
        }else{
            this.expect5 = new RTV_DEF_Expected_Result__c();
            if(size==4){
                this.expect5=total;
            }
        }

    }
}