force-app/main/default/objects/RTV_DEF_Expected_Result__c/RTV_DEF_Expected_Result__c.object-meta.xml
<CustomObject>
    <label>RTV DEF Expected Result</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>RTV DEF Expected Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RTV DEF Expected Result</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Estimated_claim_from_factory__c.field-meta.xml
<CustomField>
    <fullName>Estimated_claim_from_factory__c</fullName>
    <label>Estimated claim from factory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Landing_Cost__c.field-meta.xml
<CustomField>
    <fullName>Landing_Cost__c</fullName>
    <description>Landing Cost(FOB+Freight/Duty)</description>
    <inlineHelpText>FOB+Freight/Duty</inlineHelpText>
    <label>Landing Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Original_Wholesale_Price__c.field-meta.xml
<CustomField>
    <fullName>Original_Wholesale_Price__c</fullName>
    <description>Original Wholesale Price(After Discount)</description>
    <inlineHelpText>After Discount</inlineHelpText>
    <label>Original Wholesale Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/P_L_Impact__c.field-meta.xml
<CustomField>
    <fullName>P_L_Impact__c</fullName>
    <label>P/L Impact</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Return_Product_Descripton__c.field-meta.xml
<CustomField>
    <fullName>Return_Product_Descripton__c</fullName>
    <label>Return Product Descripton</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/RTV_DEF_Program__c.field-meta.xml
<CustomField>
    <fullName>RTV_DEF_Program__c</fullName>
    <label>RTV DEF Program</label>
    <referenceTo>RTV_Defective__c</referenceTo>
    <relationshipLabel>RTV DEF Expected Result</relationshipLabel>
    <relationshipName>RTV_DEF_Expected_Result</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RTV_DEF_Expected_Result__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <label>Total Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTV_Defective__c/RTV_Defective__c.object-meta.xml
<CustomObject>
    <label>RTV DEF Program</label>
    <nameField>
        <label>Defective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RTV DEF Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTV_Defective__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCAPP</fullName>
            </value>
            <value>
                <fullName>FTW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RTV_DEF_OffPolicy_Export.cls
@IsTest(isParallel=true)
public with sharing class Test_RTV_DEF_OffPolicy_Export {
    @IsTest
    static void test()
    {
        
        RTV_Defective__c program = new RTV_Defective__c();
        program.name = 'program';
        program.Type__c = 'FTW';
        program.Start_Date__c = Date.today();
        program.End_Date__c = Date.today().addDays(20);
        insert program;
        Apexpages.currentPage().getParameters().put('id', program.id);
        new RTV_DEF_OffPolicy_Export();

        RTV_DEF_Expected_Result__c result = new RTV_DEF_Expected_Result__c();
        result.RTV_DEF_Program__c = program.id;
        result.Return_Product_Descripton__c = 'aaabbbccc';
        result.Total_Units__c = 111;
        result.Original_Wholesale_Price__c = 111;
        result.Landing_Cost__c = 111;
        result.P_L_Impact__c = 111;
        result.Estimated_claim_from_factory__c = 111;
        insert result;

        new RTV_DEF_OffPolicy_Export();
        RTV_DEF_Expected_Result__c result1 = new RTV_DEF_Expected_Result__c();
        result1.RTV_DEF_Program__c = program.id;
        result1.Return_Product_Descripton__c = 'aaabbbccc';
        result1.Total_Units__c = 111;
        result1.Original_Wholesale_Price__c = 111;
        result1.Landing_Cost__c = 111;
        result1.P_L_Impact__c = 111;
        result1.Estimated_claim_from_factory__c = 111;
        insert result1;

        new RTV_DEF_OffPolicy_Export();

        RTV_DEF_Expected_Result__c result2 = new RTV_DEF_Expected_Result__c();
        result2.RTV_DEF_Program__c = program.id;
        result2.Return_Product_Descripton__c = 'aaabbbccc';
        result2.Total_Units__c = 111;
        result2.Original_Wholesale_Price__c = 111;
        result2.Landing_Cost__c = 111;
        result2.P_L_Impact__c = 111;
        result2.Estimated_claim_from_factory__c = 111;
        insert result2;

        new RTV_DEF_OffPolicy_Export();   
    }
}